// TC: TC_A83906
// Outcomes List Page - Post-Approval UX: Auto-Close Modal and Refresh List

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Outcomes List Page - Post-Approval UX: Auto-Close Modal and Refresh List", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.waitForLoadState('load');
  selector = MK.onSetGV(`//BUTTON[@type=\'button\'][normalize-space() = "Reset Filters"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.getByRole('button', { name: "Reset Filters" }).click();
  }
  await page.getByRole('link', { name: "Test Student #0001" }).click();
  await page.waitForLoadState('load');
  selector = MK.onSetGV(`//A[@role=\'button\'][normalize-space() = "Muuk Product Specialist"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.getByRole('link', { name: "Muuk Product Specialist" }).hover();
  await page.locator("//SPAN[normalize-space() = \"Unapproved\"]").hover();
  await page.locator("//A[normalize-space() = \"Muuk Product Specialist\"]/ancestor::div[contains(@class,\"tt-card\")]//button").click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete Entry" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this entry?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Entry" }).click();
  await page.waitForLoadState('load');
  }
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Login As" }).click();
  await page.waitForTimeout(2000);
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.getByRole('link', { name: "Profile" }).click();
  await page.getByRole('heading', { name: "Post Graduation" }).hover();
  await page.getByRole('link', { name: "Add Experience or Status" }).click();
  await page.getByRole('heading', { name: "Report Status" }).hover();
  await page.locator("//P[normalize-space() = \"Post Graduation\"]").hover();
  await page.locator("//P[normalize-space() = \"Please tell us about your plans\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Accepted Job\"]").click();
  await page.getByRole('heading', { name: "Job - Offer Accepted" }).hover();
  await page.locator("//SPAN[normalize-space() = \"(*) indicates a required field.\"]").hover();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Employer *\"]").hover();
  await page.getByPlaceholder("Employer").fill("12twenty,");
  await page.waitForTimeout(1000);
  await page.keyboard.press("ArrowDown");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Job Title *\"]").hover();
  await page.getByPlaceholder("Job Title").fill("Muuk Product Specialist ");
  await page.locator("//LABEL[contains(normalize-space(),\"Detailed Industry\")]").hover();
  await page.locator("SELECT[name='Job.JobIndustryId'][id='Job.JobIndustryId']").click();
  await page.keyboard.press("Accounting - Accounting");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Detailed Function *\"]").hover();
  await page.locator("SELECT[name='Job.JobFunctionId'][id='Job.JobFunctionId']").click();
  await page.keyboard.press("Accounting - Assurance");
  await page.locator("//LABEL[normalize-space() = \"Location If you are working remotely, please specify the location you will be working from.\"]").hover();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Location Type *\"]").hover();
  await page.locator("SELECT[name='Job.LocationTypeId'][id='Job.LocationTypeId']").click();
  await page.keyboard.press("100% Remote");
  await page.locator("//LABEL[normalize-space() = \"Location not yet determined\"]").click();
  await page.locator("//LABEL[normalize-space() = \"When If you do not know the exact day, please approximate.\"]").hover();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Offer Received Date\"]").hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(8).click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Offer Accepted Date *\"]").hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Start Date *\"]").hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(16).click();
  await page.locator("//LABEL[normalize-space() = \"Compensation Currency Receiving\"]").hover();
  await page.getByRole('heading', { name: "Primary Compensation" }).hover();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Base Salary *\"]").hover();
  await page.locator("INPUT[type='text'][id='Job.Salary.BaseSalary'][name='Job.Salary.BaseSalary']").fill("75000");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Expected Commission\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Do not expect to receive Expected Commission\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Expected Bonus *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Did not receive an Expected Bonus\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Guaranteed Bonus *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Did not receive Guaranteed Bonus\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Other Guaranteed Compensation *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Did not receive Other Guaranteed Compensation\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Carried Interest *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Did not receive Carried Interest\"]").click();
  await page.getByRole('heading', { name: "Sign On Compensation" }).hover();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Signing Bonus *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Did not receive Signing Bonus\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Relocation Reimbursement\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Did not receive Relocation Reimbursement\"]").click();
  await page.waitForTimeout(1000);
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Tuition Reimbursement\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Did not receive Tuition Reimbursement\"]").click();
  await page.getByRole('heading', { name: "Other Compensation" }).hover();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Stock or Equity Value *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Did not receive Stock or Equity Value\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Does your compensation include health insurance?\")]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Does your compensation include health insurance?\")]/ancestor::div[contains(@class,\"inline\")]//label[normalize-space()=\"No\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Does your compensation include tuition reimbursement\")]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Does your compensation include tuition reimbursement\")]/ancestor::div[contains(@class,\"inline\")]//label[normalize-space()=\"No\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Did you negotiate any elements of this offer?\")]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Did you negotiate any elements of this offer?\")]/ancestor::div[contains(@class,\"inline\")]//label[normalize-space()=\"No\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Other\"]").hover();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Job Source *\"]").click();
  await page.locator("SELECT[name='Job.CustomJobSourceId'][id='Job.CustomJobSourceId']").click();
  await page.keyboard.press("Former Employer");
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a full-time position?\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a full-time position?\")]/ancestor::div[contains(@class,\"FullTimeJob\")]//label[normalize-space()=\"Yes\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Did this job come as a result of an internship you had with this employer?\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Did this job come as a result of an internship you had with this employer?\")]/ancestor::div[contains(@class,\"FullTimeJob\")]//label[normalize-space()=\"No\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a freelance position?\")]").hover();
  await page.getByRole('heading', { name: "104 Steps" }).click();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a faculty position?\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a faculty position?\")]/ancestor::div[contains(@class,\"FullTimeJob\")]//label[normalize-space()=\"No\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a temporary/contract job?\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a temporary/contract job?\")]/ancestor::div[contains(@class,\"FullTimeJob\")]//label[normalize-space()=\"No\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a post-graduation internship?\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a post-graduation internship?\")]/ancestor::div[contains(@class,\"FullTimeJob\")]//label[normalize-space()=\"No\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Is the employer a startup?\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Is the employer a startup?\")]/ancestor::div[contains(@class,\"FullTimeJob\")]//label[normalize-space()=\"No\"]").click();
  await page.locator("//label[normalize-space() = \"Satisfaction\"]").hover();
  await page.locator("//label[contains(normalize-space(),\"Star Rating Attribute - Required\")]").hover();
  await page.locator("td.ant-table-cell.drag-visible.column-center.ant-table-cell-row-hover>div.ant-row.css-eqeg24").click();
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Submit" }).click();
  await page.waitForTimeout(5000);
  await page.getByRole('heading', { name: "Success" }).hover();
  await page.locator("//DIV[normalize-space() = \"You have successfully saved your job entry for \\'Muuk Product Specialist\\' at \\'12twenty, Inc.\\'.Would you also like to add an interview for this job? Add Interview Questions\"]").hover();
  await page.getByRole('link', { name: "Add Interview Questions" }).hover();
  await page.getByRole('link', { name: "No thanks. That's all for now!" }).click();
  await page.waitForLoadState('load');
  await expect(page.locator("//SPAN[normalize-space() = \"Offer Accepted\"]")).toHaveText("Offer Accepted");
  await expect(page.locator("//SPAN[normalize-space() = \"NOT SHARED\"]")).toHaveText("NOT SHARED");
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").click();
  await page.getByRole('link', { name: "Log Out" }).click();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('link', { name: "Notifications 99+" }).click();
  await page.locator("//SPAN[normalize-space() = \"Outcomes\"]").click();
  selector = MK.onSetGV(`//BUTTON[@type=\'button\'][normalize-space() = "Reset Filters"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.getByRole('button', { name: "Reset Filters" }).click();
  }
  await page.getByRole('button', { name: "More Filters" }).click();
  await page.getByPlaceholder("Search filters").fill("Is Appr");
  await page.locator("//SPAN[normalize-space() = \"Is Approved\"]").click();
  await page.locator("//LABEL[normalize-space() = \"No\"]").click();
  await page.locator("//SPAN[contains(normalize-space(),\"Is Approved\")]").click();
  await page.getByRole('link', { name: "Muuk Product Specialist" }).click();
  await page.locator("//SPAN[normalize-space() = \"Muuk Product Specialist\"]").hover();
  await page.locator("BUTTON[type='button']").nth(1).click();
  await page.getByRole('link', { name: "Approve" }).click();
  await page.getByRole('heading', { name: "Approve Job" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to approve this job?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Approve" }).click();
  await page.locator("//SPAN[normalize-space() = \"Job approved successfully.\"]").hover();
  await page.locator("//SPAN[contains(normalize-space(),\"Is Approved\")]").click();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").click();
  await page.locator("//SPAN[contains(normalize-space(),\"Is Approved\")]").click();
  await page.getByRole('link', { name: "Muuk Product Specialist" }).click();
  await page.waitForTimeout(2000);
  await page.locator("BUTTON[type='button']").nth(1).click();
  await page.getByRole('link', { name: "Unapprove" }).click();
  await page.getByRole('heading', { name: "Unapprove Job" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to unapprove this job?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Unapprove" }).click();
  await page.locator("//SPAN[normalize-space() = \"Job unapproved successfully.\"]").hover();
  await page.locator("//SPAN[contains(normalize-space(),\"Is Approved\")]").click();
  await page.locator("//SPAN[normalize-space() = \"Is Approved\"]").nth(1).hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").click();
  await page.locator("//SPAN[contains(normalize-space(),\"Is Approved\")]").click();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByRole('link', { name: "Test Student #0001" }).click();
  await page.getByRole('link', { name: "Muuk Product Specialist" }).hover();
  await page.locator("//SPAN[normalize-space() = \"Unapproved\"]").hover();
  await page.locator("//A[normalize-space() = \"Muuk Product Specialist\"]/ancestor::div[contains(@class,\"tt-card\")]//button").click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete Entry" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this entry?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Entry" }).click();
  await page.waitForLoadState('load');
});
