// TC: TC_A81139
// 12TU Pre-Event Survey

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("12TU Pre-Event Survey", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Events" }).click();
  await page.getByRole('link', { name: "Host an Event" }).click();
  await page.getByRole('heading', { name: "Host an Event" }).hover();
  await page.getByRole('heading', { name: "General Info" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Event Name*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Event Type*\"]").hover();
  await page.getByPlaceholder("Event Name").fill("Muuktest QA Test Event");
  await page.locator("SELECT[id='EventTypeId'][name='EventTypeId']").click();
  await page.keyboard.press("Career Center Workshop");
  await page.locator("//LABEL[normalize-space() = \"Event Format\"]").hover();
  await page.locator("SELECT[id='EventFormatId'][name='EventFormatId']").click();
  await page.keyboard.press("On Campus");
  await page.locator("//LABEL[normalize-space() = \"Location*\"]").hover();
  await page.getByPlaceholder("Location").fill("Room 2");
  await page.locator("//label[contains(text(),\"Is Student Registration Required\")]/following-sibling::div/label[normalize-space()=\"Yes\"]").click();
  await page.locator("//LABEL[normalize-space() = \"# of Attendees Permitted*\"]").hover();
  await page.getByPlaceholder("# of Attendees Permitted").fill("10");
  await page.locator("//LABEL[contains(normalize-space(),\"Enable Waitlist\")]").hover();
  await page.locator("//label[contains(text(),\"Enable Waitlist\")]/following-sibling::div/label[normalize-space()=\"No\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Auto-Promote Waitlisted Students*\"]").hover();
  await page.locator("//label[contains(text(),\"Auto-Promote Waitlisted Students\")]/following-sibling::div/label[normalize-space()=\"Yes\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Target Audience\"]").hover();
  await page.getByPlaceholder("Briefly describe who this event is meant for").fill("Everyone");
  await page.locator("//LABEL[normalize-space() = \"Dress Attire*\"]").hover();
  await page.locator("SELECT[id='DressAttireId'][name='DressAttireId']").selectOption("number:1");
  await page.getByPlaceholder("Employer Name").fill("Amazon.com");
  await page.locator("//STRONG[normalize-space() = \"Amazon.com\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Presenter\"]").click();
  await page.getByPlaceholder("Presenter").fill("Tester");
  await page.locator("//LABEL[normalize-space() = \"Industry\"]").hover();
  await page.locator("SELECT[id='ConsolidatedIndustryId'][name='ConsolidatedIndustryId']").click();
  await page.keyboard.press("Construction & Manufactury");
  await page.locator("//LABEL[normalize-space() = \"Work Authorization Requirement*\"]").hover();
  await page.getByRole('button', { name: "-- Work Authorization Requirement --" }).click();
  await page.locator("//LABEL[normalize-space() = \"All Work Authorizations Accepted\"]").click();
  await page.getByRole('heading', { name: "Event Dates" }).click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.waitForTimeout(1000);
  await page.locator("tr>td.day").nth(24).click();
  await page.getByPlaceholder("H:MMpm").fill("11:15am");
  await page.getByPlaceholder("H:MMpm").fill("1:15pm");
  await page.locator("//LABEL[normalize-space() = \"Student Registration*\"]").click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.waitForTimeout(1000);
  await page.locator("DIV[role='tooltip']").nth(5).click();
  await page.getByRole('heading', { name: "106 Steps" }).fill("12:15am");
  await page.locator("//SPAN[normalize-space() = \"to\"]").nth(1).click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.waitForTimeout(1000);
  await page.locator("tr>td.day").nth(24).click();
  await page.getByPlaceholder("H:MMpm").fill("1:00am");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Invite-Only for Employers\"]").click();
  await page.locator("//label[contains(text(),\"Invite-Only for Employers\")]/following-sibling::div//label[normalize-space()=\"No\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Student Publish Date *\"]").hover();
  await page.getByRole('heading', { name: "Zona horaria UTC ahora" }).click();
  await page.waitForTimeout(1000);
  await page.locator("DIV[role='tooltip']").nth(5).click();
  await page.getByPlaceholder("H:MMpm").click();
  await page.getByPlaceholder("H:MMpm").fill("12:15am");
  await page.getByRole('heading', { name: "Additional Registration Method" }).click();
  await page.getByPlaceholder("Other Information").fill("No other information");
  fileName = MK.onSetGV(`Test_Resume_01.pdf`, null);
  var fileInput = await page.$("INPUT[type='file']");
  var filePath ="./test/"+fileName;
  if(fileInput){
  await fileInput.setInputFiles(filePath);
  }
  else{
  throw new Error('Element to upload file is not present.');
  }
  await page.locator("//SPAN[normalize-space() = \"Test_Resume_01.pdf\"]").hover();
  await page.getByRole('link', { name: "Add Document Type" }).click();
  await page.locator("SELECT[name='CoreApplicationDocumentTypeId']").click();
  await page.keyboard.press("Resume");
  await page.getByRole('heading', { name: "Registration Survey" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Enable Survey\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Off\"]").click();
  await page.getByRole('link', { name: "Add a Question" }).click();
  await page.locator("//LABEL[normalize-space() = \"Question\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Type\"]").hover();
  await page.locator("span.multiline-lookup>input.form-control.ng-untouched.ng-scope.ng-valid-maxlength.ng-not-empty.ng-dirty.ng-valid-parse.ng-valid.ng-valid-required").fill("What is your favorite color?");
  await page.locator("//label[normalize-space()=\"Type\"]/following-sibling::div//select").click();
  await page.keyboard.press("Dropdown (Single Select)");
  await page.locator("//LABEL[normalize-space() = \"Options\"]").hover();
  await page.locator("div.controls.form-controls>textarea.ng-untouched.ng-scope.ng-not-empty.ng-dirty.ng-valid-parse.ng-valid.ng-valid-required").fill("`Re");
  await page.getByRole('link', { name: "Add a Question" }).click();
  await page.locator("//LABEL[normalize-space() = \"Question\"]").hover();
  await page.locator("span.multiline-lookup>input.form-control.ng-untouched.ng-scope.ng-valid-maxlength.ng-not-empty.ng-dirty.ng-valid-parse.ng-valid.ng-valid-required").fill("What is your favorite food?");
  await page.locator("//LABEL[normalize-space() = \"Type\"]").hover();
  await page.locator("//label[normalize-space()=\"Type\"]/following-sibling::div//select").nth(1).click();
  await page.keyboard.press("Dropdown (Multiple Select)");
  await page.getByRole('heading', { name: "106 Steps" }).fill("60000");
  await page.getByRole('link', { name: "Add a Question" }).click();
  await page.locator("//LABEL[normalize-space() = \"Question\"]").nth(2).hover();
  await page.getByPlaceholder("Buscar").fill("Are you a vegetarian?");
  await page.locator("//LABEL[normalize-space() = \"Type\"]").nth(1).hover();
  await page.locator("//label[normalize-space()=\"Type\"]/following-sibling::div//select").nth(2).click();
  await page.keyboard.press("Yes/No");
  await page.getByRole('link', { name: "Add a Question" }).click();
  await page.locator("//LABEL[normalize-space() = \"Question\"]").nth(3).hover();
  await page.getByPlaceholder("Search").fill("Please sign your name");
  await page.locator("//LABEL[normalize-space() = \"Type\"]").nth(3).hover();
  await page.locator("//label[normalize-space()=\"Type\"]/following-sibling::div//select").nth(3).click();
  await page.keyboard.press("Free Text Response");
  await page.getByRole('heading', { name: "Eligibility" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Student Group*\"]").hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Select all\"]").nth(1).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Degree Level\"]").click();
  await page.getByRole('button', { name: "Use My Information" }).click();
  await page.getByPlaceholder("Contact Phone").fill("9153455681");
  await page.getByRole('heading', { name: "Admin" }).click();
  await page.locator("//LABEL[normalize-space() = \"Event Source\"]").click();
  await page.locator("SELECT[id='SourceId'][name='SourceId']").click();
  await page.keyboard.press("Career Center Event");
  await page.locator("//LABEL[normalize-space() = \"Employer Registrants Visibility\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Allow employers to view student registrants\"]").click();
  await page.getByRole('heading', { name: "Event Dates" }).click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.getByRole('heading', { name: "18 Steps" }).click();
  await page.getByPlaceholder("H:MMpm").fill("11:15am");
  await page.getByPlaceholder("H:MMpm").fill("1:15pm");
  await page.locator("//LABEL[normalize-space() = \"Student Registration*\"]").click();
  await page.getByRole('heading', { name: "106 Steps" }).fill("12:15am");
  await page.locator("//SPAN[normalize-space() = \"to\"]").nth(1).click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.getByRole('heading', { name: "18 Steps" }).click();
  await page.getByPlaceholder("H:MMpm").fill("9:00am");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Student Publish Date *\"]").hover();
  await page.getByPlaceholder("H:MMpm").click();
  await page.getByPlaceholder("H:MMpm").fill("12:15am");
  await page.getByRole('button', { name: "Save" }).click();
  await page.waitForTimeout(10000);
  await page.getByRole('heading', { name: "Muuktest QA Test Event" }).hover();
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.student.fullaccess@campuswide.com");
  await page.getByPlaceholder("Password").fill("BoH5dORH7xg%");
  await page.getByRole('button', { name: "Student/Alumni Log In" }).click();
  await page.waitForTimeout(1000);
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Events" }).click();
  await page.getByRole('link', { name: "Advanced Search" }).click();
  await page.locator("//SPAN[normalize-space() = \"Muuktest QA Test Event\"]").nth(3).click();
  await page.getByRole('button', { name: "Register Now" }).click();
  indexPages = MK.onSetGV(`2`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('heading', { name: "Survey" }).hover();
  await page.locator("//LABEL[normalize-space() = \"What is your favorite color?\"]").hover();
  await page.locator("SELECT[id='Q0']").selectOption("Green");
  await page.locator("//LABEL[normalize-space() = \"What is your favorite food?\"]").hover();
  await page.getByRole('button', { name: "-- Select a value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Pasta\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Pizza\"]").click();
  await page.locator("//LABEL[normalize-space() = \"What is your favorite food?\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Are you a vegetarian?\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").click();
  await page.getByPlaceholder("Please sign your name").fill("e2e Test Student");
  await page.getByRole('link', { name: "Continue" }).click();
  await page.getByRole('heading', { name: "Registration Documents" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Upload New\"]").click();
  fileName = MK.onSetGV(`Test_Resume_01.pdf`, null);
  var fileInput = await page.$("INPUT[type='file']");
  var filePath ="./test/"+fileName;
  if(fileInput){
  await fileInput.setInputFiles(filePath);
  }
  else{
  throw new Error('Element to upload file is not present.');
  }
  await page.locator("//SPAN[normalize-space() = \"Test_Resume_01.pdf\"]").hover();
  await page.getByRole('link', { name: "Back" }).hover();
  await page.getByRole('link', { name: "Continue" }).click();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to register for this event?\"]").hover();
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Back" }).hover();
  await page.getByRole('link', { name: "Register" }).click();
  await page.getByRole('heading', { name: "Registration Complete" }).hover();
  await page.getByRole('link', { name: "Go Back to Event Page" }).click();
  await page.getByRole('button', { name: "Cancel Registration" }).hover();
  await page.getByRole('button', { name: "Edit Registration" }).hover();
  await page.waitForTimeout(3000);
  await page.getByRole('link', { name: "Events" }).click();
  await page.locator("//SPAN[normalize-space() = \"Muuktest QA Test Event\"]").nth(3).click();
  await page.getByRole('link', { name: "Analytics" }).click();
  await page.getByRole('heading', { name: "Impressions" }).hover();
  await page.getByRole('heading', { name: "Views" }).hover();
  await page.getByRole('heading', { name: "Registrants" }).hover();
  await page.getByRole('heading', { name: "Attended" }).hover();
  await page.getByRole('link', { name: "Registered Students (1)" }).click();
  await page.getByRole('link', { name: "e2e Test Student" }).hover();
  await page.locator("//a[normalize-space()=\"e2e Test Student\"]//ancestor::tr//button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Edit Registration" }).click();
  await page.locator("p.ng-scope>select.ng-pristine.ng-untouched.ng-valid.ng-not-empty.ng-valid-required").hover();
  await page.getByRole('button', { name: "Pizza, Pasta" }).hover();
  await page.getByRole('link', { name: "Cancel" }).click();
  await page.locator("//a[normalize-space()=\"e2e Test Student\"]//ancestor::tr//button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Cancel Registration" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.locator("BUTTON[type='button']").nth(3).click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete Event" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this event?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Event" }).click();
  await page.waitForLoadState('load');
  await page.reload();
  await page.reload();
});
