// TC: TC_A83061
// Mentorship Requests - Accept, Decline, and Request Limit Enforcement

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Mentorship Requests - Accept, Decline, and Request Limit Enforcement", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Mentorship" }).click();
  await page.waitForLoadState('load');
  selector = MK.onSetGV(`//A[@role=\'button\'][normalize-space() = "Mentorship Program 1"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.locator("//A[normalize-space() = \"Mentorship Program 1\"]/ancestor::tr//td[@class=\"select-checkbox\"]").click();
  await page.locator("BUTTON[type='button']").nth(7).click();
  await page.getByRole('link', { name: "Delete Selected" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to cancel this mentorship pair? This action will permanently delete the record and cannot be undone.\"]").nth(1).hover();
  await page.getByRole('button', { name: "OK" }).click();
  }
  await page.waitForLoadState('load');
  selector = MK.onSetGV(`//A[@role=\'button\'][normalize-space() = "Mentorship Program 1"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.locator("//A[normalize-space() = \"Mentorship Program 1\"]/ancestor::tr//td[@class=\"select-checkbox\"]").click();
  await page.locator("BUTTON[type='button']").nth(7).click();
  await page.getByRole('link', { name: "Delete Selected" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to cancel this mentorship pair? This action will permanently delete the record and cannot be undone.\"]").nth(1).hover();
  await page.getByRole('button', { name: "OK" }).click();
  }
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("Stacey Davis");
  await page.getByRole('link', { name: "Stacey Davis" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Profile" }).click();
  await page.getByRole('heading', { name: "Mentorships" }).hover();
  await page.getByRole('button', { name: "Edit" }).click();
  await page.getByRole('button', { name: "Mentorship Program 1" }).click();
  await page.locator("//LABEL[normalize-space() = \"Select all\"]").click();
  await page.locator("//LABEL[normalize-space() = \"E2E Tests Campuswide Mentorship Program\"]").click();
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("//dt[normalize-space()=\"Mentorship Programs\"]/following-sibling::dd")).toContainText("Mentorship Program 1");
  await page.getByRole('heading', { name: "General" }).hover();
  await page.getByRole('button', { name: "Edit" }).click();
  await page.locator("//LABEL[contains(normalize-space(),\"User Role*\")]").hover();
  await page.locator("SELECT[name='RoleId']").click();
  await page.keyboard.press("Full Access - Mentor");
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("//dt[normalize-space()=\"User Role\"]/following-sibling::dd")).toHaveText("Full Access - Mentor");
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("Ryan Branson");
  await page.getByRole('link', { name: "Ryan Branson" }).click();
  await page.getByRole('link', { name: "Profile" }).click();
  await page.getByRole('heading', { name: "Mentorships" }).hover();
  await page.getByRole('button', { name: "Edit" }).click();
  await page.getByRole('button', { name: "Mentorship Program 1" }).click();
  await page.locator("//LABEL[normalize-space() = \"Select all\"]").click();
  await page.locator("//LABEL[normalize-space() = \"E2E Tests Campuswide Mentorship Program\"]").click();
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("//dt[normalize-space()=\"Mentorship Programs\"]/following-sibling::dd")).toContainText("Mentorship Program 1");
  await page.getByRole('heading', { name: "General" }).hover();
  await page.getByRole('button', { name: "Edit" }).click();
  await page.locator("//LABEL[contains(normalize-space(),\"User Role*\")]").hover();
  await page.locator("SELECT[name='RoleId']").click();
  await page.keyboard.press("Full Access - Mentor");
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("//dt[normalize-space()=\"User Role\"]/following-sibling::dd")).toHaveText("Full Access - Mentor");
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("Jared Jackson");
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: "Jared Jackson" }).click();
  await page.getByRole('link', { name: "Profile" }).click();
  await page.getByRole('heading', { name: "Mentorships" }).hover();
  await page.getByRole('button', { name: "Edit" }).click();
  await page.getByRole('button', { name: "Mentorship Program 1" }).click();
  await page.locator("//LABEL[normalize-space() = \"Select all\"]").click();
  await page.locator("//LABEL[normalize-space() = \"E2E Tests Campuswide Mentorship Program\"]").click();
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("//dt[normalize-space()=\"Mentorship Programs\"]/following-sibling::dd")).toContainText("Mentorship Program 1");
  await page.getByRole('heading', { name: "General" }).hover();
  await page.getByRole('button', { name: "Edit" }).click();
  await page.locator("//LABEL[contains(normalize-space(),\"User Role*\")]").hover();
  await page.locator("SELECT[name='RoleId']").click();
  await page.keyboard.press("Full Access - Mentee");
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("//dt[normalize-space()=\"User Role\"]/following-sibling::dd")).toHaveText("Full Access - Mentee");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Login As" }).click();
  await page.waitForTimeout(2000);
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.setViewportSize({ width: 1920, height: 1080 });
  await expect(page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name")).toHaveText("Jared Jackson");
  await page.getByRole('link', { name: "Mentorship" }).click();
  await page.waitForLoadState('load');
  await page.locator("//SPAN[normalize-space() = \"Mentorship Programs\"]").click();
  await page.locator("button.selected-filter__clear>i.fa.fa-undo").click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Mentorship Program 1\"]").click();
  await page.locator("//SPAN[normalize-space() = \"Mentorship Programs\"]").click();
  await page.getByRole('link', { name: "Ryan Branson" }).click();
  await page.getByRole('button', { name: "Request Ryan as a mentor" }).click();
  await page.getByRole('heading', { name: "Request" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Message *\"]").hover();
  await page.locator("SPAN[role='presentation']").nth(1).click();
  await page.keyboard.down("End");
  await page.keyboard.press("Shift");
  await page.keyboard.up("Home");
  await page.keyboard.press("Shift");
  await page.keyboard.type("Backspace");
  await page.getByRole('link', { name: "Request" }).click();
  await page.getByRole('link', { name: "Mentorship" }).click();
  await page.getByRole('link', { name: "Stacey Davis" }).click();
  await page.getByRole('link', { name: "Mentorship" }).click();
  await page.getByRole('link', { name: "Manage" }).click();
  await page.locator("//SPAN[normalize-space() = \"Ryan Branson\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"PENDING\"]").hover();
  await page.locator("//B[normalize-space() = \"log out\"]").click();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("Ryan Branson");
  await page.getByRole('link', { name: "Ryan Branson" }).click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Login As" }).click();
  await page.waitForTimeout(2000);
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.setViewportSize({ width: 1920, height: 1080 });
  await expect(page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name")).toHaveText("Ryan Branson");
  await page.getByRole('link', { name: "Mentorship" }).click();
  await page.locator("//SPAN[normalize-space() = \"Jared Jackson\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"PENDING\"]").hover();
  await page.getByRole('heading', { name: "120 Steps" }).click();
  await page.getByRole('link', { name: "Accept" }).click();
  await page.getByRole('heading', { name: "Accept" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Message (Optional)\"]").hover();
  await page.getByRole('link', { name: "Accept" }).click();
  await expect(page.getByRole('link', { name: "Mentorship Program 1" })).toHaveText("Mentorship Program 1");
  await page.locator("//a[normalize-space()=\"Mentorship Program 1\"]//ancestor::div[contains(@class,\"tt-card\")]//button").click();
  await page.getByRole('link', { name: "Complete Mentorship Tasks" }).click();
  await expect(page.getByRole('heading', { name: "Tasks (0/1)" })).toContainText("Tasks (0/");
  await expect(page.locator("//LABEL[normalize-space() = \"Task 1\"]")).toContainText("Task 1");
  await page.locator('input[type="checkbox"]').click();
  await expect(page.getByRole('heading', { name: "Tasks (0/1)" })).toContainText("Tasks (1/");
  await page.getByRole('link', { name: "OK" }).click();
  await page.locator("//a[normalize-space()=\"Mentorship Program 1\"]//ancestor::div[contains(@class,\"tt-card\")]//button").click();
  await page.getByRole('link', { name: "Complete Mentorship Tasks" }).click();
  await expect(page.getByRole('heading', { name: "Tasks (0/1)" })).toContainText("Tasks (1/");
  await page.getByRole('link', { name: "OK" }).click();
  await page.locator("//B[normalize-space() = \"log out\"]").click();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('link', { name: "Mentorship" }).click();
  await page.getByRole('link', { name: "Mentorship Program 1" }).hover();
  await expect(page.locator("//SPAN[contains(normalize-space(),\"Mentee: \")]")).toHaveText("Mentee: Jared Jackson");
  await expect(page.locator("//SPAN[contains(normalize-space(),\"Mentor: \")]")).toHaveText("Mentor: Ryan Branson");
  await expect(page.locator("//A[normalize-space() = \"Mentorship Program 1\"]/ancestor::tr//span[contains(@class,\"badge\")]")).toHaveText("ACTIVE");
  await page.locator("//A[normalize-space() = \"Mentorship Program 1\"]/ancestor::tr//td[@class=\"select-checkbox\"]").click();
  await page.locator("BUTTON[type='button']").nth(7).click();
  await page.getByRole('link', { name: "Delete Selected" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to cancel this mentorship pair? This action will permanently delete the record and cannot be undone.\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("Jared Jackson");
  await page.getByRole('link', { name: "Jared Jackson" }).click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Login As" }).click();
  await page.waitForTimeout(2000);
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await expect(page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name")).toHaveText("Jared Jackson");
  await page.getByRole('link', { name: "Mentorship" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Stacey Davis" }).click();
  await page.locator("//button[normalize-space() = \"Request Stacey as a mentor\"]").click();
  await page.getByRole('heading', { name: "Request" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Message *\"]").hover();
  await page.locator("SPAN[role='presentation']").nth(1).click();
  await page.keyboard.down("End");
  await page.keyboard.press("Shift");
  await page.keyboard.up("Home");
  await page.keyboard.press("Shift");
  await page.keyboard.type("Backspace");
  await page.getByRole('link', { name: "Request" }).click();
  await page.getByRole('link', { name: "Mentorship" }).click();
  await page.getByRole('link', { name: "Manage" }).click();
  await page.locator("//B[normalize-space() = \"log out\"]").click();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("Stacey Davis");
  await page.getByRole('link', { name: "Stacey Davis" }).click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Login As" }).click();
  await page.waitForTimeout(2000);
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await expect(page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name")).toHaveText("Stacey Davis");
  await page.getByRole('link', { name: "Mentorship" }).click();
  await page.locator("//SPAN[normalize-space() = \"Jared Jackson\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"PENDING\"]").hover();
  await page.getByRole('heading', { name: "120 Steps" }).click();
  await page.getByRole('link', { name: "Decline" }).click();
  await page.getByRole('heading', { name: "Decline" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Message (Optional)\"]").hover();
  await page.getByRole('link', { name: "Decline" }).click();
  await page.reload();
  await page.waitForLoadState('load');
  await expect(page.locator("td.table-non-primary-col.center>span.badge.alert")).toHaveText("DECLINED");
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('link', { name: "Mentorship" }).click();
  await page.getByRole('link', { name: "Mentorship Program 1" }).hover();
  await expect(page.locator("//SPAN[contains(normalize-space(),\"Mentee: \")]")).toHaveText("Mentee: Jared Jackson");
  await expect(page.locator("//SPAN[contains(normalize-space(),\"Mentor: \")]")).toHaveText("Mentor: Stacey Davis");
  await expect(page.locator("//A[normalize-space() = \"Mentorship Program 1\"]/ancestor::tr//span[contains(@class,\"badge\")]")).toHaveText("DECLINED");
  await page.locator("//A[normalize-space() = \"Mentorship Program 1\"]/ancestor::tr//td[@class=\"select-checkbox\"]").click();
  await page.locator("BUTTON[type='button']").nth(7).click();
  await page.getByRole('link', { name: "Delete Selected" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to cancel this mentorship pair? This action will permanently delete the record and cannot be undone.\"]").nth(1).hover();
  await page.getByRole('button', { name: "OK" }).click();
});
