// TC: TC_A78122
// Employers - Judge Directory - Students add Judge via outcome and admin approves

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Employers - Judge Directory - Students add Judge via outcome and admin approves", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eLawQAStudentURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.student.fullaccess@law.com");
  await page.getByPlaceholder("Password").fill("BoH5dORH7xg%");
  await page.getByRole('button', { name: "Student/Alumni Log In" }).click();
  await page.waitForTimeout(3000);
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Profile" }).click();
  await page.getByRole('link', { name: "Home" }).click();
  await page.getByRole('link', { name: "Add Experience or Status" }).click();
  await page.getByRole('heading', { name: "Report Status" }).hover();
  await page.locator("//P[normalize-space() = \"Post JD\"]").hover();
  await page.locator("//P[normalize-space() = \"Please tell us about your plans\"]").hover();
  await page.getByRole('button', { name: "Judicial Clerkship" }).click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Court *\"]").hover();
  await page.getByPlaceholder("Judge Name").fill("Muuktest Test Judge");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Court *\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Detailed Employment Type\"]").hover();
  await page.getByPlaceholder("Court Name").fill("MT Test Court QA");
  await page.locator("SELECT[id='Fields_EmploymentTypeId'][name='Fields.EmploymentTypeId']").selectOption("15002603121613");
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Start Date *\"]").hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(34).click();
  await page.locator("//LABEL[normalize-space() = \"End Date\"]").hover();
  await page.getByPlaceholder("MM/DD/YYYY").fill("12/12/2026");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Did you receive your job offer before you received your bar results? *\"]").click();
  await page.locator("SELECT[id='Fields_DidReceiveOfferBeforeBarId'][name='Fields.DidReceiveOfferBeforeBarId']").selectOption("1");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Estimated Total Compensation *\"]").hover();
  await page.locator("INPUT[id='Fields_TotalCompensation'][name='Fields.TotalCompensation'][type='text']").fill("2000");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Stipend *\"]").hover();
  await page.locator("INPUT[id='Fields_StipendAmount'][name='Fields.StipendAmount'][type='text']").fill("0");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Job Source *\"]").hover();
  await page.locator("SELECT[name='Fields.CustomJobSourceId'][id='Fields.CustomJobSourceId']").selectOption("100011010338735");
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").click();
  await page.locator('input[type="radio"]').click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Are you still seeking another job?\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(1).click();
  await page.locator('input[type="radio"]').click();
  await page.locator("SELECT[id='Fields_LawJobFundingSourceId'][name='Fields.LawJobFundingSourceId']").selectOption("4");
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(1).click();
  await page.locator('input[type="radio"]').click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Employment Requirement *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").click();
  await page.locator('input[type="radio"]').click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Employment Requirement *\"]").hover();
  await page.locator("SELECT[id='Fields_EmploymentRequirementId'][name='Fields.EmploymentRequirementId']").click();
  await page.locator("SELECT[id='Fields_EmploymentRequirementId'][name='Fields.EmploymentRequirementId']").selectOption("1");
  await page.locator("SELECT[name='Fields.LocationTypeId'][id='Fields.LocationTypeId']").selectOption("1");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Job Country *\"]").hover();
  await page.getByPlaceholder("Country").fill("United States (USA)");
  await page.locator("//DIV[normalize-space() = \"United States (USA)\"]").click();
  await page.getByPlaceholder("City").fill("San Diego - CA");
  await page.locator("//DIV[normalize-space() = \"San Diego - CA\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Address 1 *\"]").hover();
  await page.locator("INPUT[id='Fields_Address1'][name='Fields.Address1'][type='text']").fill("123 Test");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Postal Code *\"]").hover();
  await page.locator("INPUT[id='Fields_PostalCode'][name='Fields.PostalCode'][type='text']").fill("92101");
  await page.locator("INPUT[id='Fields_EmployerWebsiteUrl'][name='Fields.EmployerWebsiteUrl'][type='text']").fill("test123.com");
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Home" }).click();
  await page.waitForTimeout(10000);
  await page.getByRole('link', { name: "Judicial Clerkship" }).hover();
  await page.locator("//A[normalize-space() = \"Judicial Clerkship\"]/ancestor::div[2]//SPAN[normalize-space() = \"Offer Accepted\"]").hover();
  await page.locator("//A[normalize-space() = \"Judicial Clerkship\"]/ancestor::div[2]//SPAN[normalize-space() = \"At Graduation\"]").hover();
  await page.locator("//A[normalize-space() = \"Judicial Clerkship\"]/ancestor::div[2]//SPAN[normalize-space() = \"NOT SHARED\"]").hover();
  await page.waitForTimeout(2000);
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@law.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.locator("//SPAN[normalize-space() = \"e2e Test Admin\"]").hover();
  await page.getByRole('link', { name: "Notifications 21" }).click();
  await page.locator("//SPAN[normalize-space() = \"Outcomes\"]").click();
  await page.locator("//span[normalize-space() = \"e2e Test Student\"]").hover();
  await page.locator("//DIV[normalize-space() = \"Muuktest Test Judge\"]").hover();
  await page.locator("//DIV[normalize-space() = \"Muuktest Test Judge\"]/ancestor::tr//td[@class=\"select-checkbox\"]").click();
  await page.locator("BUTTON[type='button']").nth(12).click();
  await page.getByRole('link', { name: "Approve Selected (1)" }).click();
  await page.locator("//SPAN[normalize-space() = \"Successfully approved 1 job(s).\"]").hover();
  await page.getByRole('link', { name: "Employers" }).click();
  selector = MK.onSetGV(`//BUTTON[@type=\'button\'][normalize-space() = "Reset Filters"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.getByRole('button', { name: "Reset Filters" }).click();
  }
  await page.locator("//SPAN[normalize-space() = \"Approval Status\"]").click();
  await page.locator("button.selected-filter__remove>i.far.fa-trash-alt").click();
  await page.getByPlaceholder("Employer Name or Court").fill("Test");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Muuktest Test Judge" }).click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "View Audit Log" }).click();
  await page.locator("button.btn.btn-icon.ng-scope>i.far.fa-plus-square").click();
  await page.waitForTimeout(2000);
  await page.locator("//SPAN[normalize-space() = \"Rejected\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Approved\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"×\"]").click();
  await page.getByRole('link', { name: "Hires" }).click();
  await page.getByRole('link', { name: "Locations" }).click();
  await page.locator("//SPAN[normalize-space() = \"San Diego - CA\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"United States (USA)\"]").hover();
  await page.getByRole('link', { name: "Home" }).click();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("e2e Test Student");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "e2e Test Student" }).click();
  await page.getByRole('link', { name: "Home" }).click();
  await page.getByRole('link', { name: "Judicial Clerkship" }).hover();
  await page.locator("//DIV[normalize-space() = \"MT Test Court QA\"]").hover();
  await page.locator("//A[normalize-space() = \"Judicial Clerkship\"]/following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Edit" }).hover();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete Entry" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this entry?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Entry" }).click();
  await page.waitForTimeout(3000);
  await page.reload();
  await page.waitForTimeout(3000);
});
