// TC: TC_A79039
// 12TU Candidate Search - Employers can view applicants, download resumes, filter

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("12TU Candidate Search - Employers can view applicants, download resumes, filter", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("Cydney");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Cydney Moore" }).click();
  await page.getByRole('link', { name: "Home" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Profile" }).click();
  selector = MK.onSetGV(`(//dt[contains(text(),"Allow Employers to contact me with job opportunities")]//following-sibling::dd)[1]//span[normalize-space()="Yes"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.getByRole('button', { name: "Edit" }).click();
  await page.locator("//LABEL[contains(normalize-space(),\"Allow Employers to contact me with job opportunities\")]/following::LABEL[normalize-space() = \"No\"]").click();
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("//dt[normalize-space()=\"Allow Employers to contact me with job opportunities\"]/following-sibling::dd")).toHaveText("No");
  }
  await page.waitForLoadState('load');
  await page.locator("dl.dl-horizontal>dt.ng-binding.ng-scope").nth(35).hover();
  await expect(page.locator("dd.ng-scope>span.ng-binding.ng-scope").nth(30)).toHaveText("No");
  await page.getByRole('link', { name: "Application Materials" }).click();
  selector = MK.onSetGV(`//A[@role=\'button\'][normalize-space() = "e2e Test Resume"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.locator("(//a[normalize-space()=\"e2e Test Resume\"])[2]/following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Delete Resume" }).click();
  await page.getByRole('heading', { name: "Delete Resume" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this resume?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Resume" }).click();
  }
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Login As" }).click();
  await page.waitForTimeout(5000);
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.getByRole('link', { name: "Application Materials" }).click();
  await page.getByRole('heading', { name: "Resumes" }).hover();
  await page.getByRole('link', { name: "Add New" }).click();
  await page.getByRole('heading', { name: "Add New Resume" }).hover();
  await page.locator("INPUT[type='text'][name='documentName'][id='applicationDocumentName']").fill("e2e Test Resume");
  fileName = MK.onSetGV(`Test_Resume_01.pdf`, null);
  var fileInput = await page.$("INPUT[type='file']");
  var filePath ="./test/"+fileName;
  if(fileInput){
  await fileInput.setInputFiles(filePath);
  }
  else{
  throw new Error('Element to upload file is not present.');
  }
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: "Submit" }).click();
  await page.getByRole('link', { name: "e2e Test Resume" }).hover();
  await page.locator("//SPAN[normalize-space() = \"Cydney Moore\"]").click();
  await page.getByRole('link', { name: "Account Settings" }).click();
  await page.getByRole('heading', { name: "Connections" }).hover();
  await expect(page.locator("dl.dl-horizontal.wide>dd.ng-binding")).toHaveText("No");
  await page.getByRole('link', { name: "Edit" }).click();
  await page.locator("//LABEL[contains(normalize-space(),\"Allow Employers to contact me with job opportunities\")]").hover();
  await page.getByRole('heading', { name: "87 Steps" }).click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.getByRole('heading', { name: "Success!" }).hover();
  await page.locator("//DIV[normalize-space() = \"Your changes have successfully been saved.\"]").nth(1).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.reload();
  await page.waitForTimeout(2000);
  await expect(page.locator("dl.dl-horizontal.wide>dd.ng-binding")).toHaveText("Yes");
  await page.locator("//B[normalize-space() = \"log out\"]").click();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("e2e Test ");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "e2e Test Student" }).click();
  await page.getByRole('link', { name: "Home" }).click();
  await page.getByRole('link', { name: "Profile" }).click();
  selector = MK.onSetGV(`(//dt[contains(text(),"Allow Employers to contact me with job opportunities")]//following-sibling::dd)[1]//span[normalize-space()="Yes"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.getByRole('button', { name: "Edit" }).click();
  await page.locator("//LABEL[contains(normalize-space(),\"Allow Employers to contact me with job opportunities\")]/following::LABEL[normalize-space() = \"No\"]").click();
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("//dt[normalize-space()=\"Allow Employers to contact me with job opportunities\"]/following-sibling::dd")).toHaveText("No");
  }
  await page.locator("dl.dl-horizontal>dt.ng-binding.ng-scope").nth(35).hover();
  await expect(page.locator("//dt[normalize-space()=\"Allow Employers to contact me with job opportunities\"]/following-sibling::dd")).toHaveText("No");
  await page.getByRole('link', { name: "Application Materials" }).click();
  await page.waitForLoadState('load');
  selector = MK.onSetGV(`//A[@role=\'button\'][normalize-space() = "QA Resume"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.getByRole('link', { name: "QA Resume" }).hover();
  await page.locator("(//a[normalize-space()=\"QA Resume\"])[2]/following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Delete Resume" }).click();
  await page.getByRole('heading', { name: "Delete Resume" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this resume?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Resume" }).click();
  }
  await page.getByRole('heading', { name: "Resumes" }).hover();
  await page.getByRole('link', { name: "Add New" }).click();
  await page.getByRole('heading', { name: "Add New Resume" }).hover();
  await page.locator("INPUT[type='text'][name='documentName'][id='applicationDocumentName']").fill("QA Resume");
  fileName = MK.onSetGV(`Test_Resume_01.pdf`, null);
  var fileInput = await page.$("INPUT[type='file']");
  var filePath ="./test/"+fileName;
  if(fileInput){
  await fileInput.setInputFiles(filePath);
  }
  else{
  throw new Error('Element to upload file is not present.');
  }
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Submit" }).click();
  await page.getByRole('link', { name: "Profile" }).click();
  await page.getByRole('heading', { name: "Account Settings" }).hover();
  await page.getByRole('button', { name: "Edit" }).click();
  await page.locator("//h3[normalize-space() = \"Edit Account Settings\"]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Allow Employers to contact me with job opportunities\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Allow Employers to contact me with job opportunities\")]/following::LABEL[normalize-space() = \"Yes\"]").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.locator("dl.dl-horizontal>dt.ng-binding.ng-scope").nth(35).hover();
  await expect(page.locator("dd.ng-scope>span.ng-binding.ng-scope").nth(30)).toHaveText("Yes");
  await page.locator("div.side-nav-with-link-and-submenu-container>button.btn.btn-icon.sub-menu-icon").nth(7).click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByRole('link', { name: "Employers" }).click();
  await page.locator("//SPAN[normalize-space() = \"Email\"]").click();
  await page.locator("//SPAN[normalize-space() = \"Email\"]").nth(1).hover();
  await page.getByPlaceholder("Email").fill("e2e.employeruser.subscription.admin@walmart.com");
  await page.locator("//SPAN[normalize-space() = \"Email\"]").click();
  await page.waitForTimeout(3000);
  await page.locator("//td[contains(normalize-space(),\"e2e.employeruser.subscription.admin@walmart.com\")]").hover();
  await page.getByRole('link', { name: "Marylin Yahne" }).click();
  await page.getByRole('heading', { name: "Other Permissions Edit" }).hover();
  selector = MK.onSetGV(`(//dt[normalize-space()="Candidate Search"]/following-sibling::dd)[1][normalize-space()="Yes"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await expect(page.locator("//dt[normalize-space()=\"Candidate Search\"]/following-sibling::dd")).toHaveText("Yes");
  await page.getByRole('link', { name: "Edit" }).click();
  await page.getByRole('heading', { name: "Edit Access Permissions" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Candidate Search\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Candidate Search\"]/following::label[normalize-space()=\"No\"]").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.waitForTimeout(3000);
  await expect(page.locator("//dt[normalize-space()=\"Candidate Search\"]/following-sibling::dd")).toHaveText("No");
  }
  await page.waitForTimeout(2000);
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('e2e-tests-campuswide.qa-12twenty.com/hire');
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Email Address").fill("e2e.employeruser.subscription.admin@walmart.com");
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.waitForTimeout(2000);
  await page.locator("button.btn.btn-school.submit-login-form>span").click();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").hover();
  await page.getByRole('link', { name: "Candidates" }).click();
  await page.getByRole('heading', { name: "Request for Candidate Search Access" }).click();
  await page.getByRole('button', { name: "Request Access" }).click();
  await page.getByRole('heading', { name: "Success!" }).hover();
  await page.locator("//DIV[normalize-space() = \"Your request has been submitted.\"]").nth(1).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").click();
  await page.getByRole('link', { name: "Log Out" }).click();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('link', { name: "Notifications 99+" }).click();
  await page.locator("//SPAN[normalize-space() = \"Employer Partner Requests\"]").click();
  await page.locator("//SPAN[@title=''][normalize-space() = \"Verified by 12twenty\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Verified by 12twenty\"]/following::button[@title=\"Reject\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Verified by 12twenty\"]/following::button[@title=\"Approve\"]").click();
  await page.locator("//SPAN[normalize-space() = \"\\'Candidate Search\\' successfully approved.\"]").hover();
  await page.waitForTimeout(2000);
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('e2e-tests-campuswide.qa-12twenty.com/hire');
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Email Address").fill("e2e.employeruser.subscription.admin@walmart.com");
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.waitForTimeout(2000);
  await page.locator("button.btn.btn-school.submit-login-form>span").click();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").hover();
  await page.waitForTimeout(2000);
  await page.getByRole('link', { name: "Candidates" }).click();
  await page.getByRole('button', { name: "Get Results" }).click();
  await page.locator("//SPAN[normalize-space() = \"Cydney Moore\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Cydney.Moore@campuswide.com\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"e2e Test Student\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"e2e.student.fullaccess@campuswide.com\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Keyword Search:\"]").hover();
  await page.getByPlaceholder("Search Keywords in Resume").fill("start date");
  await page.getByRole('button', { name: "Get Results" }).click();
  await page.waitForTimeout(10000);
  await page.waitForLoadState('load');
  await page.getByRole('button', { name: "Get Results" }).click();
  await page.getByPlaceholder("Search Keywords in Resume").fill("rumer");
  await page.getByRole('button', { name: "Get Results" }).click();
  await page.waitForLoadState('load');
  await page.locator("//DIV[normalize-space() = \"No results found.\"]").click();
  await page.getByPlaceholder("Search Keywords in Resume").fill("");
  await page.locator("//LABEL[normalize-space() = \"Graduation Year:\"]").hover();
  await page.getByRole('button', { name: "All" }).click();
  await page.locator("//LABEL[normalize-space() = \"2030\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Graduation Year:\"]").click();
  await page.getByRole('button', { name: "Get Results" }).click();
  await page.waitForTimeout(10000);
  await page.locator("//SPAN[normalize-space() = \"e2e Test Student\"]").hover();
  await expect(page.locator("//SPAN[normalize-space() = \"e2e Test Student\"]/following::span")).toContainText("2030");
  await page.locator("//SPAN[normalize-space() = \"e2e.student.fullaccess@campuswide.com\"]").hover();
  await page.getByRole('button', { name: "All" }).click();
  await page.locator("//LABEL[normalize-space() = \"2030\"]").click();
  await page.locator("//LABEL[normalize-space() = \"2028\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Graduation Year:\"]").click();
  await page.getByRole('button', { name: "Get Results" }).click();
  await page.waitForLoadState('load');
  await page.locator("//SPAN[normalize-space() = \"Cydney Moore\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Cydney.Moore@campuswide.com\"]").hover();
  await expect(page.locator("//SPAN[normalize-space() = \"Cydney Moore\"]/following::span")).toContainText("2028");
  await page.getByRole('link', { name: "Clear Filters" }).click();
  await page.getByRole('button', { name: "Action" }).click();
  await page.getByRole('link', { name: "Download Selected Resume(s) to PDF (2)" }).click();
  await page.waitForTimeout(10000);
  indexPages = MK.onSetGV(`2`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForTimeout(5000);
  await page.waitForTimeout(5000);
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForLoadState('load');
  await page.locator("//SPAN[normalize-space() = \"Cydney Moore\"]/ancestor::tr//button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "View Resume" }).click();
  await page.waitForTimeout(10000);
  indexPages = MK.onSetGV(`2`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForTimeout(2000);
  await page.locator("//SPAN[normalize-space() = \"Cydney Moore\"]/ancestor::tr//button[@aria-label=\"Options\"]").click();
  selector = MK.onSetGV(`//A[@role=\'button\'][@title=\'Download Resume\'][normalize-space() = "Download Resume"]`, null);
  textContent = MK.onSetGV(`Cydney Moore`, null);
  const [download] = await Promise.all([
  page.waitForEvent('download'),
  page.click(selector)
  ]);
  fileName = download.suggestedFilename();
  snippetLog(`File was downloaded: ${fileName}`);
  if (fileName.includes(textContent)) {
  snippetLog('Filename contains ' + textContent);
  } else {
  throw new Error(`Filename does not contain "${textContent}"`);
  }
  await page.waitForTimeout(2000);
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForTimeout(2000);
  await page.reload();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("e2e Test ");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "e2e Test Student" }).click();
  await page.getByRole('link', { name: "Home" }).click();
  await page.getByRole('link', { name: "Profile" }).click();
  await page.locator("dl.dl-horizontal>dt.ng-binding.ng-scope").nth(35).hover();
  await expect(page.locator("//dt[normalize-space()=\"Allow Employers to contact me with job opportunities\"]/following-sibling::dd")).toHaveText("Yes");
  await page.getByRole('heading', { name: "Account Settings" }).hover();
  await page.getByRole('button', { name: "Edit" }).click();
  await page.locator("//h3[normalize-space() = \"Edit Account Settings\"]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Allow Employers to contact me with job opportunities\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Allow Employers to contact me with job opportunities\")]/following::LABEL[normalize-space() = \"No\"]").click();
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("//dt[normalize-space()=\"Allow Employers to contact me with job opportunities\"]/following-sibling::dd")).toHaveText("No");
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForTimeout(1000);
  await page.reload();
  await page.getByRole('button', { name: "Get Results" }).click();
  await page.locator("//SPAN[normalize-space() = \"Cydney Moore\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Cydney.Moore@campuswide.com\"]").hover();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('heading', { name: "Account Settings" }).hover();
  await page.getByRole('button', { name: "Edit" }).click();
  await page.locator("//h3[normalize-space() = \"Edit Account Settings\"]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Allow Employers to contact me with job opportunities\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Allow Employers to contact me with job opportunities\")]/following::LABEL[normalize-space() = \"Yes\"]").click();
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("//dt[normalize-space()=\"Allow Employers to contact me with job opportunities\"]/following-sibling::dd")).toHaveText("Yes");
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForTimeout(1000);
  await page.reload();
  await page.getByRole('button', { name: "Get Results" }).click();
  await page.locator("//SPAN[normalize-space() = \"Cydney Moore\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Cydney.Moore@campuswide.com\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"e2e Test Student\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"e2e.student.fullaccess@campuswide.com\"]").hover();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").click();
  await page.getByRole('link', { name: "Log Out" }).click();
  await page.getByRole('button', { name: "Employer Log In" }).hover();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.locator("dl.dl-horizontal>dt.ng-binding.ng-scope").nth(35).hover();
  await expect(page.locator("//dt[normalize-space()=\"Allow Employers to contact me with job opportunities\"]/following-sibling::dd")).toHaveText("Yes");
  await page.getByRole('heading', { name: "Account Settings" }).hover();
  await page.getByRole('button', { name: "Edit" }).click();
  await page.locator("//h3[normalize-space() = \"Edit Account Settings\"]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Allow Employers to contact me with job opportunities\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Allow Employers to contact me with job opportunities\")]/following::LABEL[normalize-space() = \"No\"]").click();
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("//dt[normalize-space()=\"Allow Employers to contact me with job opportunities\"]/following-sibling::dd")).toHaveText("No");
  await page.getByRole('link', { name: "Application Materials" }).click();
  await page.getByRole('link', { name: "QA Resume" }).hover();
  await page.locator("(//a[normalize-space()=\"QA Resume\"])[2]/following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Delete Resume" }).click();
  await page.getByRole('heading', { name: "Delete Resume" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this resume?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Resume" }).click();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("Cydney");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Cydney Moore" }).click();
  await page.getByRole('link', { name: "Profile" }).click();
  await page.getByRole('button', { name: "Edit" }).click();
  await page.locator("//LABEL[contains(normalize-space(),\"Allow Employers to contact me with job opportunities\")]/following::LABEL[normalize-space() = \"No\"]").click();
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("//dt[normalize-space()=\"Allow Employers to contact me with job opportunities\"]/following-sibling::dd")).toHaveText("No");
  await page.getByRole('button', { name: "Edit" }).click();
  await page.locator("//LABEL[contains(normalize-space(),\"Allow Employers to contact me with job opportunities\")]/following::LABEL[normalize-space() = \"No\"]").click();
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("//dt[normalize-space()=\"Allow Employers to contact me with job opportunities\"]/following-sibling::dd")).toHaveText("No");
  await page.getByRole('link', { name: "Application Materials" }).click();
  await page.getByRole('link', { name: "e2e Test Resume" }).hover();
  await page.locator("(//a[normalize-space()=\"e2e Test Resume\"])[2]/following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Delete Resume" }).click();
  await page.getByRole('heading', { name: "Delete Resume" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this resume?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Resume" }).click();
  await page.locator("div.side-nav-with-link-and-submenu-container>button.btn.btn-icon.sub-menu-icon").nth(7).click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByRole('link', { name: "Employers" }).click();
  await page.locator("//SPAN[normalize-space() = \"Email\"]").click();
  await page.locator("//SPAN[normalize-space() = \"Email\"]").nth(1).hover();
  await page.getByPlaceholder("Email").fill("e2e.employeruser.subscription.admin@walmart.com");
  await page.locator("//SPAN[normalize-space() = \"Email\"]").click();
  await page.waitForTimeout(3000);
  await page.locator("//td[contains(normalize-space(),\"e2e.employeruser.subscription.admin@walmart.com\")]").hover();
  await page.getByRole('link', { name: "Marylin Yahne" }).click();
  await page.getByRole('heading', { name: "Other Permissions Edit" }).hover();
  await expect(page.locator("//dt[normalize-space()=\"Candidate Search\"]/following-sibling::dd")).toHaveText("Yes");
  await page.getByRole('link', { name: "Edit" }).click();
  await page.getByRole('heading', { name: "Edit Access Permissions" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Candidate Search\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Candidate Search\"]/following::label[normalize-space()=\"No\"]").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.waitForTimeout(3000);
  await expect(page.locator("//dt[normalize-space()=\"Candidate Search\"]/following-sibling::dd")).toHaveText("No");
});
