// TC: TC_A78156
// Employers - Judge Directory - Add&#x2F;edit&#x2F;reject Judge

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Employers - Judge Directory - Add&#x2F;edit&#x2F;reject Judge", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto('https://e2e-tests-law.admin.qa-12twenty.com/dashboard', { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@law.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.locator("//SPAN[normalize-space() = \"e2e Test Admin\"]").hover();
  await page.getByRole('link', { name: "Employers" }).click();
  await page.getByRole('link', { name: "Judges" }).click();
  await page.getByRole('button', { name: "More Filters" }).click();
  await page.getByPlaceholder("Search filters").fill("Stat");
  await page.getByRole('button', { name: "Approval Status" }).click();
  await page.locator("//LABEL[normalize-space() = \"Approved\"]").click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('heading', { name: "Employers" }).click();
  await page.getByRole('link', { name: "Add Employer" }).click();
  await page.getByRole('heading', { name: "Add New Employer" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Employer Type\"]").hover();
  await page.locator("INPUT[name='EmployerName']").fill("Muuktest Judge");
  await page.locator("SELECT[id='TypeId'][name='TypeId']").selectOption("number:2");
  await page.locator("//LABEL[normalize-space() = \"Court\"]").hover();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Student Employment Employer\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").click();
  await page.locator('input[type="radio"]').click();
  await page.locator("//LABEL[normalize-space() = \"Account Manager*\"]").hover();
  await page.locator("SELECT[id='AccountManagerId'][name='AccountManagerId']").selectOption("number:540016054866960");
  await page.locator("//LABEL[normalize-space() = \"Website\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Outreach Priority*\"]").hover();
  await page.getByPlaceholder("Website").fill("test.com");
  await page.locator("SELECT[id='OutreachPriorityId'][name='OutreachPriorityId']").selectOption("number:1");
  await page.locator("//LABEL[normalize-space() = \"Employment Type\"]").hover();
  await page.locator("SELECT[id='NalpEmploymentType'][name='NalpEmploymentType']").selectOption("number:44");
  await page.locator("SELECT[id='JudgeTypeId'][name='JudgeTypeId']").selectOption("number:245");
  await page.locator("//LABEL[normalize-space() = \"Court Level\"]").hover();
  await page.locator("SELECT[id='CourtLevelId'][name='CourtLevelId']").selectOption("number:4");
  await page.locator("//LABEL[normalize-space() = \"Court - Detail\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Salutation\"]").hover();
  await page.getByPlaceholder("Court - Detail").fill("Details - Test");
  await page.locator("SELECT[id='SalutationId'][name='SalutationId']").selectOption("number:245");
  await page.locator("//LABEL[normalize-space() = \"Last Name\"]").hover();
  await page.getByPlaceholder("Last Name").fill("Tester");
  await page.locator("//LABEL[normalize-space() = \"Phone Number\"]").hover();
  await page.getByPlaceholder("Phone Number").fill("8589965522");
  await page.locator("//LABEL[normalize-space() = \"Fax Number\"]").hover();
  await page.getByPlaceholder("Fax Number").fill("8008554411");
  await page.getByPlaceholder("Email Address").fill("qajudge@test.com");
  await page.locator("//LABEL[normalize-space() = \"Street Address 1\"]").hover();
  await page.getByPlaceholder("Street Address 1").fill("123 Test Lane");
  await page.locator("//LABEL[normalize-space() = \"City\"]").hover();
  await page.getByPlaceholder("City").fill("San Diego - CA");
  await page.locator("//STRONG[normalize-space() = \"San Diego - CA\"]").click();
  await page.locator("//LABEL[normalize-space() = \"State\"]").hover();
  await page.getByPlaceholder("State").fill("California");
  await page.locator("//DIV[normalize-space() = \"California\"]").nth(2).click();
  await page.locator("//LABEL[normalize-space() = \"Practice Areas\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Zip Code\"]").hover();
  await page.getByPlaceholder("Zip Code").fill("92561");
  await page.getByRole('button', { name: "None-selected" }).click();
  await page.locator("//LABEL[normalize-space() = \"Government Regulation - Corporate law\"]").click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Government Regulation - Corporate and Securities\"]").click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Industry-Focused Services - Pharmacy Industry\"]").click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Litigation - Appellate Practice\"]").click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Practice Areas\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Overview\"]").hover();
  await page.getByRole('button', { name: "None-selected" }).click();
  await page.locator("//LABEL[normalize-space() = \"Org Capacity: Minority owned/lead organization\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Planning & Accountability: Recurring culture & climate survey\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Demographic Data Available?\"]").click();
  await page.locator("SELECT[id='PublicDemographicsTypeId'][name='PublicDemographicsTypeId']").selectOption("number:1");
  await page.locator("//LABEL[normalize-space() = \"Demographic Data URL\"]").click();
  await page.getByPlaceholder("Demographic Data URL").fill("testdemographicinfo.com");
  await page.locator("//LABEL[normalize-space() = \"Linkedin Profile\"]").hover();
  await page.getByPlaceholder("Linkedin Profile").fill("https://linkedin.com/company/12twenty-inc-/");
  await page.locator("//LABEL[normalize-space() = \"Twitter Profile\"]").hover();
  await page.getByPlaceholder("Twitter Profile").fill("https://twitter.com/12twentyinc");
  await page.locator("//LABEL[normalize-space() = \"Facebook Profile\"]").hover();
  await page.getByPlaceholder("Facebook Profile").fill("https://www.facebook.com/12twenty");
  await page.getByPlaceholder("Instagram Profile").fill("https://www.instagram.com/12twentyinc");
  await page.getByRole('button', { name: "Save" }).click();
  await page.getByRole('link', { name: "Judges" }).click();
  await page.getByRole('heading', { name: "Employers" }).click();
  await page.getByRole('link', { name: "Muuktest Judge" }).hover();
  await page.getByRole('link', { name: "Muuktest Judge" }).click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.getByRole('heading', { name: "Edit Muuktest Judge" }).hover();
  await page.locator("SELECT[id='OutreachPriorityId'][name='OutreachPriorityId']").selectOption("number:4");
  await page.locator("SELECT[id='NalpEmploymentType'][name='NalpEmploymentType']").click();
  await page.locator("SELECT[id='NalpEmploymentType'][name='NalpEmploymentType']").selectOption("number:6");
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.getByRole('link', { name: "Activities" }).click();
  await page.getByRole('link', { name: "Locations" }).click();
  await page.getByRole('link', { name: "Events" }).click();
  await page.getByRole('link', { name: "OCI and Job Listings" }).click();
  await page.getByRole('link', { name: "Experiences" }).click();
  await page.getByRole('link', { name: "Evaluations" }).click();
  await page.getByRole('link', { name: "Home" }).click();
  await page.locator("//a[normalize-space()=\"Site Management\"]/following-sibling::button").click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.locator("//a[normalize-space()=\"e2e Test Student\"]/ancestor::tr//button").click();
  await page.getByRole('link', { name: "Login as user..." }).click();
  await page.getByRole('heading', { name: "Login as e2e Test Student" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('e2e-tests-law.qa-12twenty.com/on-login?returnUrl=%2Fdashboard');
  await page.getByRole('link', { name: "Employers" }).click();
  await page.getByRole('link', { name: "Judges" }).click();
  await page.getByRole('link', { name: "Muuktest Judge" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('link', { name: "Target Employers" }).click();
  await page.getByRole('link', { name: "Muuktest Judge" }).hover();
  await page.getByRole('link', { name: "javascript:void(0)" }).click();
  await page.getByRole('link', { name: "Employers" }).click();
  await page.getByRole('link', { name: "Muuktest Judge" }).click();
  await page.locator("a.linkedin.ng-scope>i.fab.fa-linkedin").click();
  await page.waitForTimeout(3000);
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('linkedin.com/');
  await page.getByRole('heading', { name: "Join LinkedIn" }).hover();
  await page.locator("a.twitter.ng-scope>i.fab.fa-twitter").click();
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('x.com/12twentyinc');
  await page.locator("a.facebook.ng-scope>i.fab.fa-facebook-square").click();
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('facebook.com/12twenty');
  await page.locator("//SPAN[normalize-space() = \"See more from 12twenty | West Hollywood CA\"]").nth(1).hover();
  await page.locator("a.instagram.ng-scope>i.fab.fa-instagram").click();
  await page.waitForTimeout(3000);
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('instagram.com/');
  await page.waitForTimeout(3000);
  await page.getByRole('link', { name: "Employers" }).click();
  await page.getByRole('link', { name: "Muuktest Judge" }).click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Reject" }).click();
  await page.getByRole('heading', { name: "Reject Employer" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to reject this employer?\"]").nth(1).hover();
  await page.locator("//DIV[normalize-space() = \"Cancel Reject\"]").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Reject" }).click();
  await page.getByRole('link', { name: "Employers" }).click();
  await page.getByRole('link', { name: "Judges" }).click();
});
