// TC: TC_A84040
// Outcomes – Validate Industry is required on Accepted Job submission

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Outcomes – Validate Industry is required on Accepted Job submission", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideStudentURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.student.fullaccess@campuswide.com");
  await page.getByPlaceholder("Password").fill("BoH5dORH7xg%");
  await page.getByRole('button', { name: "Student/Alumni Log In" }).click();
  await page.waitForTimeout(1000);
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Profile" }).click();
  await page.getByRole('link', { name: "Home" }).click();
  await page.getByRole('heading', { name: "e2e Test Student" }).hover();
  await page.getByRole('heading', { name: "Post Graduation" }).hover();
  await page.getByRole('link', { name: "Add Experience or Status" }).click();
  await page.getByRole('heading', { name: "Report Status" }).hover();
  await page.getByRole('button', { name: "Accepted Job" }).click();
  await page.getByRole('heading', { name: "Job - Offer Accepted" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Basics\"]").hover();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Employer *\"]").hover();
  await page.getByPlaceholder("Employer").fill("12twenty, Inc.");
  await page.locator("//DIV[normalize-space() = \"12twenty, Inc.\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Job Title *\"]").hover();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Detailed Industry *\"]").hover();
  await page.getByPlaceholder("Job Title").fill("Product Specialist");
  await page.locator("SELECT[name='Job.JobIndustryId'][id='Job.JobIndustryId']").click();
  await page.keyboard.press("Technology/Engeneering/Science");
  await page.locator("//LABEL[contains(normalize-space(),\"Detailed Function\")]").hover();
  await page.locator("SELECT[name='Job.JobFunctionId'][id='Job.JobFunctionId']").click();
  await page.keyboard.press("Administrative");
  await page.locator("//LABEL[contains(normalize-space(),\"Location Type\")]").click();
  await page.locator("SELECT[name='Job.LocationTypeId'][id='Job.LocationTypeId']").click();
  await page.keyboard.press("On Site");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Country *\"]").hover();
  await page.getByPlaceholder("Country").fill("United States (USA)");
  await page.locator("//DIV[normalize-space() = \"United States (USA)\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"City *\"]").hover();
  await page.getByPlaceholder("City").click();
  await page.keyboard.press("Grand Rapids - MI");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Address 1 *\"]").hover();
  await page.locator("INPUT[id='Job_Address1'][name='Job.Address1'][type='text']").fill("123 Main Street");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Postal Code *\"]").hover();
  await page.locator("INPUT[id='Job_PostalCode'][name='Job.PostalCode'][type='text']").fill("12345");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Offer Received Date\"]").hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(16).click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Offer Accepted Date *\"]").hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Start Date *\"]").hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(18).click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Base Salary *\"]").hover();
  await page.locator("INPUT[type='text'][id='Job.Salary.BaseSalary'][name='Job.Salary.BaseSalary']").fill("75000");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Expected Commission\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Do not expect to receive Expected Commission\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Expected Bonus *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Did not receive an Expected Bonus\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Guaranteed Bonus *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Did not receive Guaranteed Bonus\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Other Guaranteed Compensation *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Did not receive Other Guaranteed Compensation\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Carried Interest *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Did not receive Carried Interest\"]").click();
  await page.getByRole('heading', { name: "Sign On Compensation" }).hover();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Signing Bonus *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Did not receive Signing Bonus\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Relocation Reimbursement\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Did not receive Relocation Reimbursement\"]").click();
  await page.waitForTimeout(1000);
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Tuition Reimbursement\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Did not receive Tuition Reimbursement\"]").click();
  await page.getByRole('heading', { name: "Other Compensation" }).hover();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Stock or Equity Value *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Did not receive Stock or Equity Value\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Does your compensation include health insurance?\")]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Does your compensation include health insurance?\")]/ancestor::div[contains(@class,\"inline\")]//label[normalize-space()=\"No\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Does your compensation include tuition reimbursement\")]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Does your compensation include tuition reimbursement\")]/ancestor::div[contains(@class,\"inline\")]//label[normalize-space()=\"No\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Did you negotiate any elements of this offer?\")]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Did you negotiate any elements of this offer?\")]/ancestor::div[contains(@class,\"inline\")]//label[normalize-space()=\"No\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Other\"]").hover();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Job Source *\"]").click();
  await page.locator("SELECT[name='Job.CustomJobSourceId'][id='Job.CustomJobSourceId']").click();
  await page.keyboard.press("Alumni Contact");
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a full-time position?\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a full-time position?\")]/ancestor::div[contains(@class,\"FullTimeJob\")]//label[normalize-space()=\"Yes\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Did this job come as a result of an internship you had with this employer?\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Did this job come as a result of an internship you had with this employer?\")]/ancestor::div[contains(@class,\"FullTimeJob\")]//label[normalize-space()=\"No\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a freelance position?\")]").hover();
  await page.getByRole('heading', { name: "104 Steps" }).click();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a faculty position?\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a faculty position?\")]/ancestor::div[contains(@class,\"FullTimeJob\")]//label[normalize-space()=\"No\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a temporary/contract job?\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a temporary/contract job?\")]/ancestor::div[contains(@class,\"FullTimeJob\")]//label[normalize-space()=\"No\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a post-graduation internship?\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a post-graduation internship?\")]/ancestor::div[contains(@class,\"FullTimeJob\")]//label[normalize-space()=\"No\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Is the employer a startup?\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Is the employer a startup?\")]/ancestor::div[contains(@class,\"FullTimeJob\")]//label[normalize-space()=\"No\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Employer *\"]").hover();
  await page.getByPlaceholder("Employer").fill("Google");
  await page.locator("//DIV[normalize-space() = \"Google Inc.\"]").click();
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Submit" }).click();
  await page.locator("//DIV[normalize-space() = \"The following fields were not filled out:\"]").hover();
  await page.locator("//LI[contains(normalize-space(),\"Industry\")]").hover();
  await page.getByRole('link', { name: "OK" }).click();
  await page.locator("//SPAN[normalize-space() = \"*Required\"]").hover();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Detailed Industry *\"]").click();
  await page.locator("SELECT[name='Job.JobIndustryId'][id='Job.JobIndustryId']").click();
  await page.waitForTimeout(1000);
  await page.waitForTimeout(1000);
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Detailed Industry *\"]").click();
  await page.locator("//label[normalize-space() = \"Satisfaction\"]").hover();
  await page.locator("//label[contains(normalize-space(),\"Star Rating Attribute - Required\")]").hover();
  await page.locator("td.ant-table-cell.drag-visible.column-center.ant-table-cell-row-hover>div.ant-row.css-eqeg24").click();
  await page.getByRole('button', { name: "Submit" }).click();
  await page.getByRole('heading', { name: "Success" }).hover();
  await page.locator("//DIV[normalize-space() = \"You have successfully saved your job entry for \\'Product Specialist\\' at \\'Google Inc.\\'.Would you also like to add an interview for this job? Add Interview Questions\"]").hover();
  await page.getByRole('link', { name: "Add Interview Questions" }).hover();
  await page.getByRole('link', { name: "No thanks. That's all for now!" }).click();
  await page.getByRole('link', { name: "Product Specialist" }).click();
  await page.getByRole('heading', { name: "Job Details" }).hover();
  await page.locator("//SPAN[normalize-space() = \"Product Specialist\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Office and Administrative Support\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Technology/Engineering/Science - Software Products\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Technology/Engineering/Science\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"×\"]").click();
  await page.locator("//A[normalize-space() = \"Product Specialist\"]/following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete Entry" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this entry?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Entry" }).click();
  await page.waitForLoadState('load');
});
