// TC: TC_A82518
// Notifications - Verify Email notifications can be edited, disabled, links work

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Notifications - Verify Email notifications can be edited, disabled, links work", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.locator("div.side-nav-with-link-and-submenu-container>button.btn.btn-icon.sub-menu-icon").nth(7).click();
  await page.getByRole('link', { name: "Site Settings" }).click();
  await page.getByRole('link', { name: "Mentorships" }).click();
  await page.getByRole('link', { name: "E2E Tests Campuswide Mentorship Program" }).hover();
  await page.locator("//A[normalize-space() = \"E2E Tests Campuswide Mentorship Program\"]//following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('heading', { name: "3 Steps" }).click();
  await page.locator("//label[contains(normalize-space(),\"Pending Request Reminder (Hours)\")]//following::INPUT[@name=\"numHoursBeforeSendRequestReminder\"]").fill("1");
  await page.getByRole('button', { name: "Save Changes" }).click();
  await page.reload();
  await page.getByRole('link', { name: "E2E Tests Campuswide Mentorship Program" }).hover();
  await page.locator("//A[normalize-space() = \"E2E Tests Campuswide Mentorship Program\"]//following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('heading', { name: "3 Steps" }).click();
  selector = MK.onSetGV(`//label[contains(normalize-space(),"Pending Request Reminder (Hours)")]//following::INPUT[@name="numHoursBeforeSendRequestReminder"]`, null);
  textContent = MK.onSetGV(`1`, null);
  await page.waitForLoadState('load');
  snippetLog('Selector: ' + selector);
  snippetLog('Value: ' + textContent);
  await expect(page.locator(selector)).toHaveValue(textContent);
  await page.locator("//label[contains(normalize-space(),\"Pending Request Reminder (Hours)\")]//following::INPUT[@name=\"numHoursBeforeSendRequestReminder\"]").fill("0");
  await page.getByRole('button', { name: "Save Changes" }).click();
  await page.reload();
  await page.getByRole('link', { name: "E2E Tests Campuswide Mentorship Program" }).hover();
  await page.locator("//A[normalize-space() = \"E2E Tests Campuswide Mentorship Program\"]//following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('heading', { name: "3 Steps" }).click();
  textContent = MK.onSetGV(`0`, null);
  snippetLog('Selector: ' + selector);
  snippetLog('Value: ' + textContent);
  await expect(page.locator(selector)).toHaveValue(textContent);
  await page.locator("//label[contains(normalize-space(),\"Pending Request Reminder (Hours)\")]//following::INPUT[@name=\"numHoursBeforeSendRequestReminder\"]").click();
  await page.waitForTimeout(1000);
  await page.keyboard.press("End");
  await page.getByRole('button', { name: "Save Changes" }).click();
  await page.getByRole('link', { name: "E2E Tests Campuswide Mentorship Program" }).hover();
  await page.locator("//A[normalize-space() = \"E2E Tests Campuswide Mentorship Program\"]//following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('heading', { name: "3 Steps" }).click();
  await page.waitForLoadState('load');
  textContent = MK.onSetGV(`0`, null);
  snippetLog('Selector: ' + selector);
  snippetLog('Value: ' + textContent);
  await expect(page.locator(selector)).toHaveValue(textContent);
  await page.getByRole('link', { name: "Cancel" }).click();
  await page.getByRole('link', { name: "Notifications" }).click();
  await page.getByRole('heading', { name: "Email Notification Templates" }).hover();
  await page.getByRole('link', { name: "Admin-Assigned Match (to Mentee)" }).click();
  await expect(page.locator("//dt[normalize-space()=\"Email Enabled\"]/following-sibling::dd")).toHaveText("Yes");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.locator("//LABEL[normalize-space() = \"On\"]").click();
  await page.getByRole('button', { name: "Save" }).click();
  await page.getByRole('button', { name: "OK" }).click();
  await expect(page.locator("//dt[normalize-space()=\"Email Enabled\"]/following-sibling::dd")).toHaveText("No");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.locator("//LABEL[normalize-space() = \"Off\"]").click();
  await page.getByRole('button', { name: "Save" }).click();
  await page.getByRole('button', { name: "OK" }).click();
  await expect(page.locator("//dt[normalize-space()=\"Email Enabled\"]/following-sibling::dd")).toHaveText("Yes");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.waitForLoadState('load');
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Send Me a Test Email" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('button', { name: "OK" }).click();
  await page.waitForLoadState('load');
  await page.getByPlaceholder("Description").fill("Test");
  await page.getByPlaceholder("Subject Line").click();
  await page.getByRole('button', { name: "Substitution Tags" }).click();
  await page.getByRole('link', { name: "Graduation Term" }).click();
  await page.locator("SPAN[id='cke_1_top'][role='presentation']").click();
  await page.keyboard.press("PageUp");
  await page.keyboard.type("End");
  await page.getByRole('button', { name: "Add Hyperlink" }).click();
  await page.getByRole('heading', { name: "88 Steps" }).click();
  await page.getByRole('heading', { name: "87 Steps" }).click();
  await page.getByRole('button', { name: "Save" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('button', { name: "OK" }).click();
  await expect(page.locator("//dt[normalize-space()=\"Description\"]/following-sibling::dd")).toHaveText("Test");
  await expect(page.locator("//dt[normalize-space()=\"Body\"]/following-sibling::dd//p")).toHaveText("Hi {{MentorFirstName}}, - [link title|http://example.com] - {{MenteeFirstName}}");
  await page.reload();
  await page.waitForLoadState('load');
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "View Audit Log" }).click();
  await page.getByRole('heading', { name: "Mentorship Request Audit Log" }).click();
  await page.locator("button.btn.btn-icon.ng-scope>i.far.fa-plus-square").click();
  await expect(page.locator("//dt[normalize-space()=\"Description\"]//following::div[contains(@class,\"audit-log-diff-description-data\")]//div")).toHaveText("None");
  await expect(page.locator("//dt[normalize-space()=\"Description\"]//following::div[contains(@class,\"audit-log-diff-description-data\")]//div").nth(1)).toHaveText("Test");
  await expect(page.locator("//dt[normalize-space()=\"Subject\"]//following::div[contains(@class,\"audit-log-diff-description-data\")]//div")).toHaveText("New Mentorship Request");
  await expect(page.locator("//dt[normalize-space()=\"Subject\"]//following::div[contains(@class,\"audit-log-diff-description-data\")]//div").nth(1)).toHaveText("New Mentorship Request - {{Student.GraduationTerm}}");
  await expect(page.locator("//dt[normalize-space()=\"Body\"]//following::div[contains(@class,\"audit-log-diff-description-data\")]//div")).toHaveText("Hi {{MentorFirstName}},You have a new pending {{MentorshipProgramName}} request from {{MenteeFirstName}} {{MenteeLastName}}!{{MenteeFirstName}} {{MenteeLastName}}: {{MentorshipRequestMessage}}{{AcceptOrDeclineMentorshipLinks}}{{SnoozeMentorshipLinks}}You may also review this request [via the platform|{{MentorshipLinkModule}}]!");
  await expect(page.locator("//dt[normalize-space()=\"Body\"]//following::div[contains(@class,\"audit-log-diff-description-data\")]//div").nth(1)).toHaveText("Hi {{MentorFirstName}}, - [link title|http://example.com] - {{MenteeFirstName}}You have a new pending {{MentorshipProgramName}} request from {{MenteeFirstName}} {{MenteeLastName}}!{{MenteeFirstName}} {{MenteeLastName}}: {{MentorshipRequestMessage}}{{AcceptOrDeclineMentorshipLinks}}{{SnoozeMentorshipLinks}}You may also review this request [via the platform|{{MentorshipLinkModule}}]!");
  await page.locator("//SPAN[normalize-space() = \"×\"]").click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.getByPlaceholder("Description").fill("");
  await page.getByPlaceholder("Subject Line").click();
  await page.keyboard.press("Shift");
  await page.keyboard.up("Home");
  await page.keyboard.press("Shift");
  await page.keyboard.type("Backspace");
  await page.locator("SPAN[id='cke_1_top'][role='presentation']").click();
  await page.keyboard.press("PageUp");
  await page.keyboard.down("End");
  await page.keyboard.press("Shift");
  await page.keyboard.up("Home");
  await page.keyboard.press("Shift");
  await page.keyboard.type("Backspace");
  await page.getByRole('button', { name: "Launch Email Studio" }).click();
  await page.getByRole('link', { name: "Cancel" }).click();
  await page.getByRole('button', { name: "Save" }).click();
  await page.getByRole('button', { name: "OK" }).click();
});
