// TC: TC_A83741
// Appointments - Hybrid: Preferred Location Required When Switching Appointment Type

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Appointments - Hybrid: Preferred Location Required When Switching Appointment Type", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Appointments" }).click();
  selector = MK.onSetGV(`//DIV[normalize-space() = "Test Student #0001 (e2e Test Admin) – 3:30pm- 4pm"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.locator("//DIV[normalize-space() = \"Test Student #0001 (e2e Test Admin) – 3:30pm- 4pm\"]").click();
  await page.locator("BUTTON[type='button']").nth(10).click();
  await page.getByRole('link', { name: "Cancel Appointment" }).click();
  await page.getByRole('heading', { name: "Cancel the Appointment" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure about this cancellation? Once canceled, this time slot will be re-open to other students, Re-booking the same slot will not be guaranteed.\"]").nth(1).hover();
  await page.getByRole('button', { name: "No, return to the appointment" }).hover();
  await page.getByRole('button', { name: "Yes, cancel it" }).click();
  }
  selector = MK.onSetGV(`//DIV[normalize-space() = "e2e Test Admin – 3:30pm- 6:30pm"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.locator("//DIV[normalize-space() = \"e2e Test Admin – 3:30pm- 6:30pm\"]").click();
  await page.getByRole('heading', { name: "Appointment Block" }).hover();
  await page.locator("BUTTON[type='button']").nth(1).click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.getByRole('heading', { name: "Edit Appointment Block" }).hover();
  await page.locator("//DIV[normalize-space() = \"This block is part of a recurring appointment block series.\"]").hover();
  await page.getByRole('link', { name: "Delete Block" }).click();
  await page.getByRole('heading', { name: "Delete Recurring Block" }).hover();
  await page.locator("//P[normalize-space() = \"Would you like to permanently delete only this block, or this and all future blocks in the series?\"]").hover();
  await page.getByRole('link', { name: "Delete Only This" }).hover();
  await page.getByRole('link', { name: "Delete Following" }).hover();
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Delete Following" }).click();
  await page.getByRole('heading', { name: "Delete All Following Appointment Blocks" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure about this deletion? This and all future time blocks will be deleted.\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Yes, delete all" }).click();
  }
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Block" }).click();
  await page.waitForLoadState('domcontentloaded');
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").click();
  await page.waitForTimeout(3000);
  await page.getByPlaceholder("H:MMpm").click();
  await page.waitForTimeout(6000);
  await page.locator("//LABEL[normalize-space() = \"Occurs*\"]").hover();
  await page.locator("SELECT[id='FrequencyId'][name='FrequencyId']").click();
  await page.keyboard.press("Weekly");
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.locator("//SPAN[normalize-space() = \"to\"]").nth(1).hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.new.day").nth(7).click();
  await page.locator("//LABEL[normalize-space() = \"Occurs On*\"]").hover();
  await page.locator("//LABEL[@title='Monday'][normalize-space() = \"M\"]").click();
  await page.locator("//LABEL[@title='Tuesday'][normalize-space() = \"T\"]").click();
  await page.locator("//LABEL[@title='Wednesday'][normalize-space() = \"W\"]").click();
  await page.locator("//LABEL[normalize-space() = \"T\"][@title=\"Thursday\"]").click();
  await page.locator("//LABEL[@title='Friday'][normalize-space() = \"F\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Type *\"]").hover();
  await page.getByRole('button', { name: "-- Select Type(s) --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Select all\"]").nth(1).click();
  await page.locator("//LABEL[normalize-space() = \"Type *\"]").click();
  await page.getByRole('heading', { name: "Location" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Hybrid\"]").click();
  await page.locator("//LABEL[@id='DetailedAppointmentBlockVirtualLocationTypeId-label'][normalize-space() = \"Virtual Location Type*\"]").hover();
  await page.locator("SELECT[name='DetailedAppointmentBlockVirtualLocationTypeId']").click();
  await page.keyboard.press("Select from a list");
  await page.waitForTimeout(1000);
  await page.locator("//LABEL[@id='VirtualPicklistLocationIds-label'][normalize-space() = \"Location*\"]").hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.getByRole('heading', { name: "58 Steps" }).click();
  await page.locator("//LABEL[@id='DetailedAppointmentBlockInPersonLocationTypeId-label'][normalize-space() = \"In-Person Location Type*\"]").click();
  await page.locator("SELECT[name='DetailedAppointmentBlockInPersonLocationTypeId']").click();
  await page.keyboard.press("Select from a list");
  await page.waitForTimeout(1000);
  await page.locator("//LABEL[@id='VirtualPicklistLocationIds-label'][normalize-space() = \"Location*\"]").hover();
  await page.locator("//BUTTON[normalize-space() = \"-- Select a Value --\"]").click();
  await page.locator("(//LABEL[normalize-space() = \"Location*\"])[2]/following::LABEL[normalize-space() = \"Select all\"]").click();
  await page.getByRole('heading', { name: "Eligibility" }).hover();
  await page.getByRole('button', { name: "-- All Student Groups --" }).click();
  await page.getByRole('heading', { name: "61 Steps" }).click();
  await page.locator("//LABEL[normalize-space() = \"Student Group\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Current Adviser\\'s Students Only*\"]").click();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(1).click();
  await page.waitForTimeout(2000);
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Create Block" }).click();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByRole('heading', { name: "Students & Alumni" }).hover();
  selector = MK.onSetGV(`//BUTTON[@type=\'button\'][normalize-space() = "Reset Filters"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.getByRole('button', { name: "Reset Filters" }).click();
  }
  await page.getByRole('link', { name: "Test Student #0001" }).click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Login As" }).click();
  await page.waitForTimeout(2000);
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.setViewportSize({ width: 1920, height: 1080 });
  selector = MK.onSetGV(`//A[@role=\'button\'][normalize-space() = \'Bypass "On Next Login" (Admin Only)\']`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.locator("//A[@role='button'][normalize-space() = 'Bypass \"On Next Login\" (Admin Only)']").click();
  }
  await page.getByRole('link', { name: "Appointments" }).click();
  await page.getByRole('button', { name: "List" }).click();
  await page.getByRole('link', { name: "List" }).click();
  await page.locator("a.event-date.ng-scope>tt-date-time-display.ng-binding.ng-isolate-scope").click();
  await page.getByRole('heading', { name: "Appointment Block" }).hover();
  await page.getByRole('link', { name: "View Available Slots" }).click();
  await page.locator("//LABEL[normalize-space() = \"Preferred Appointment Type*\"]").hover();
  await page.locator("SELECT[name='SelectedAppointmentType']").click();
  await page.keyboard.press("General Career Coaching");
  await page.locator("//LABEL[normalize-space() = \"Time*\"]").hover();
  await page.getByRole('link', { name: "3:30pm PDT" }).click();
  await page.locator("//LABEL[@id='LocationTypeId-label'][normalize-space() = \"Location Type*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"In-Person\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Preferred Location*\")]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Preferred Location*\")]/following::select").click();
  await page.waitForTimeout(1000);
  await page.keyboard.press("Room 101");
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Book Appointment" }).click();
  await page.waitForTimeout(10000);
  await page.locator("//dt[normalize-space()=\"Time\"]").hover();
  await expect(page.locator("//dt[normalize-space()=\"Time\"]/following-sibling::dd//tt-date-time-display")).toContainText("3:30pm - 4:00pm PDT");
  await page.locator("//dt[normalize-space()=\"Career Adviser\"]").hover();
  await expect(page.locator("//dt[normalize-space()=\"Career Adviser\"]/following-sibling::dd//div[@class=\"adviser-summary\"]")).toHaveText("e2e Test Admin");
  await page.locator("//dt[normalize-space()=\"Preferred Type\"]").hover();
  await expect(page.locator("//dt[normalize-space()=\"Preferred Type\"]/following-sibling::dd")).toHaveText("General Career Coaching");
  await page.locator("//dt[normalize-space()=\"Location\"]").hover();
  await expect(page.locator("//dt[normalize-space()=\"Location\"]/following-sibling::dd")).toHaveText("Room 101");
  await page.locator("//SPAN[normalize-space() = \"×\"]").nth(1).click();
  await page.reload();
  await page.waitForLoadState('load');
  await page.locator("//TT-DATE-TIME-DISPLAY[normalize-space()=\"3:30pm - 4:00pm PDT\"]").hover();
  await expect(page.locator("//TT-DATE-TIME-DISPLAY[normalize-space()=\"3:30pm - 4:00pm PDT\"]/following::p[contains(@class,\"student\")]")).toHaveText("Test Student #0001");
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('link', { name: "Appointments" }).click();
  await page.locator("//DIV[normalize-space() = \"Test Student #0001 (e2e Test Admin) – 3:30pm- 4pm\"]").click();
  await page.locator("//dt[normalize-space()=\"Time\"]").hover();
  await expect(page.locator("//dt[normalize-space()=\"Time\"]/following-sibling::dd//tt-date-time-display")).toContainText("3:30pm - 4:00pm PDT");
  await page.locator("//dt[normalize-space()=\"Career Adviser\"]").hover();
  await expect(page.locator("//dt[normalize-space()=\"Career Adviser\"]/following-sibling::dd//div[@class=\"adviser-summary\"]")).toHaveText("e2e Test Admin");
  await page.locator("//dt[normalize-space()=\"Preferred Type\"]").hover();
  await expect(page.locator("//dt[normalize-space()=\"Preferred Type\"]/following-sibling::dd")).toHaveText("General Career Coaching");
  await page.locator("//dt[normalize-space()=\"Location\"]").hover();
  await expect(page.locator("//dt[normalize-space()=\"Location\"]/following-sibling::dd")).toHaveText("Room 101");
  await page.locator("BUTTON[type='button']").nth(10).click();
  await page.getByRole('link', { name: "Cancel Appointment" }).click();
  await page.getByRole('heading', { name: "Cancel the Appointment" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure about this cancellation? Once canceled, this time slot will be re-open to other students, Re-booking the same slot will not be guaranteed.\"]").nth(1).hover();
  await page.getByRole('button', { name: "No, return to the appointment" }).hover();
  await page.getByRole('button', { name: "Yes, cancel it" }).click();
  await page.locator("//DIV[normalize-space() = \"e2e Test Admin – 3:30pm- 6:30pm\"]").click();
  await page.getByRole('heading', { name: "Appointment Block" }).hover();
  await page.locator("BUTTON[type='button']").nth(1).click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.getByRole('heading', { name: "Edit Appointment Block" }).hover();
  await page.locator("//DIV[normalize-space() = \"This block is part of a recurring appointment block series.\"]").hover();
  await page.getByRole('link', { name: "Delete Block" }).click();
  await page.getByRole('heading', { name: "Delete Recurring Block" }).hover();
  await page.locator("//P[normalize-space() = \"Would you like to permanently delete only this block, or this and all future blocks in the series?\"]").hover();
  await page.getByRole('link', { name: "Delete Only This" }).hover();
  await page.getByRole('link', { name: "Delete Following" }).hover();
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Delete Following" }).click();
  await page.getByRole('heading', { name: "Delete All Following Appointment Blocks" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure about this deletion? This and all future time blocks will be deleted.\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Yes, delete all" }).click();
});
