// TC: TC_A83922
// Interview Experience - Clicking Student Name Opens Resume Slideout for Employers

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Interview Experience - Clicking Student Name Opens Resume Slideout for Employers", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Job Listings & Interviews" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Register for Interviews" }).click();
  await page.locator("//LABEL[normalize-space() = \"Employer*\"]").hover();
  await page.getByPlaceholder("Employer").fill("12twenty,");
  await page.waitForTimeout(1000);
  await page.keyboard.press("ArrowDown");
  await page.locator("//LABEL[normalize-space() = \"OCI Round* :\"]").hover();
  await page.locator("SELECT[name='OciRoundId']").click();
  await page.waitForTimeout(2000);
  await page.waitForTimeout(1000);
  await page.getByRole('heading', { name: "Interview Periods Please Note: Once period dates for individual OCI registrations have been customized, periods can no longer be added or removed from the round. OCI periods can be added or removed from a round, even if there are active OCI registrations, unless period dates have been customized for individual OCI registrations" }).hover();
  await page.locator("//DIV[normalize-space() = \"e2e Test Period\"]").hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(25).click();
  await page.getByRole('heading', { name: "Interview Date Preferences Preferred Interview Dates cannot be the same." }).hover();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"First Choice *\"]").hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.locator("//SPAN[normalize-space() = \"Time Preference *\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Time Preference *\"]/following::select").click();
  await page.keyboard.press("Morning");
  await page.getByRole('heading', { name: "Interview Preferences" }).hover();
  await page.locator("//LABEL[normalize-space() = \"# of Total Interview Slots*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"# of Interview Rooms Requested*\"]").hover();
  await page.getByPlaceholder("# of Total Interview Slots").fill("1");
  await page.locator("//LABEL[normalize-space() = \"Length of Interview*\"]").hover();
  await page.getByPlaceholder("# of Interview Rooms Requested").fill("1");
  await page.getByPlaceholder("Length of Interview").fill("30");
  await page.locator("//LABEL[contains(normalize-space(),\"Rotating Schedule\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Rotating Schedule\")]/ancestor::div[contains(@class,\"form-group\")]//label[normalize-space()=\"No\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Are you hiring for multiple positions?\"]").hover();
  await page.locator("//LABEL[@id=\"IsHiringForMultiplePositions-label\"][normalize-space() = \"Are you hiring for multiple positions?\"]/following-sibling::div//label[normalize-space()=\"No\"]").click();
  await page.getByRole('button', { name: "Use My Information" }).click();
  await page.locator("//LABEL[normalize-space() = \"OCI Contact Title*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"OCI Contact Phone*\"]").hover();
  await page.getByPlaceholder("OCI Contact Title").fill("MBA Recruiter");
  await page.locator("//LABEL[normalize-space() = \"OCI Contact Address*\"]").hover();
  await page.getByPlaceholder("OCI Contact Phone").fill("2223334444");
  await page.getByPlaceholder("OCI Contact Address").fill("1234");
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save Draft" }).hover();
  await page.getByRole('button', { name: "Next" }).click();
  await page.locator("//DIV[normalize-space() = \"Approve this request for On-Campus Interviews?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Ok" }).click();
  await page.getByRole('heading', { name: "TBD" }).hover();
  await page.getByRole('link', { name: "12twenty, Inc." }).hover();
  await page.locator("//SPAN[normalize-space() = \"Registration - Active\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Job Posting - Non-Existent\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Schedule Not Released\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Date Needed\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Job Posting Status: There is no job posting associated with this OCI registration. Please post job details as early as possible.\"]").hover();
  await page.getByRole('link', { name: "Post a Job" }).click();
  await page.getByRole('heading', { name: "Create Job Posting" }).click();
  await page.getByRole('heading', { name: "Job Details" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Job Title*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Type of Job\"]").hover();
  await page.getByPlaceholder("Job Title").fill("Senior Associate");
  await page.getByRole('button', { name: "-- Type of Job --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Full-Time Job\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Type of Job\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Location Type*\"]").hover();
  await page.locator("SELECT[id='LocationTypeId'][name='LocationTypeId']").click();
  await page.keyboard.press("Remote/Telecommute");
  await page.locator("//LABEL[normalize-space() = \"Industry*\"]").hover();
  await page.getByRole('button', { name: "-- Industry --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Accounting - Accounting\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Job Function*\"]").click();
  await page.getByRole('button', { name: "-- Job Function --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Accounting - Assurance\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Job Function*\"]").click();
  await page.getByRole('heading', { name: "Job Description" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Job Description*\"]").hover();
  await page.getByRole('heading', { name: "61 Steps" }).click();
  await page.locator("//LABEL[@id='contactToAdd-label'][normalize-space() = \"Interviewer*\"]").hover();
  await page.locator("SELECT[name='contactToAdd']").click();
  await page.keyboard.press("Jane Doe");
  await page.getByRole('heading', { name: "Primary Job Contact" }).hover();
  await page.getByRole('button', { name: "Use My Information" }).click();
  await page.locator("//LABEL[normalize-space() = \"Job Posting Contact Title*\"]").hover();
  await page.getByPlaceholder("Job Posting Contact Title").fill("MBA Recruiter");
  await page.locator("//LABEL[normalize-space() = \"Job Posting Contact Phone*\"]").hover();
  await page.getByPlaceholder("Job Posting Contact Phone").fill("2223334444");
  await page.locator("//LABEL[normalize-space() = \"Job Posting Contact Address*\"]").hover();
  await page.getByPlaceholder("Job Posting Contact Address").fill("1234");
  await page.getByRole('heading', { name: "Eligibility" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Student Group*\"]").hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Student Group*\"]//following::LABEL[normalize-space() = \"Select all\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Student Group*\"]").click();
  await page.getByRole('heading', { name: "Career Center Administrator" }).hover();
  await page.locator("//LABEL[normalize-space() = \"# of Total Interview Slots*\"]").hover();
  await page.getByPlaceholder("# of Total Interview Slots").fill("1");
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save Draft" }).hover();
  await page.getByRole('button', { name: "Next" }).click();
  await page.getByRole('heading', { name: "Job Posting" }).hover();
  await page.locator("//DIV[normalize-space() = \"Approve this job posting?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Ok" }).click();
  await page.getByRole('heading', { name: "Senior Associate" }).hover();
  await page.getByRole('link', { name: "Applicants (0)" }).click();
  await page.getByRole('link', { name: "Schedule" }).click();
  await page.locator("//SPAN[normalize-space() = \"The Employer has not been notified of the interview date\"]").hover();
  await page.getByRole('link', { name: "Add Schedule" }).click();
  await page.getByRole('heading', { name: "Add Schedule(s)" }).hover();
  await page.locator("//SPAN[normalize-space() = \"Pacific Time (US & Canada) (UTC-08:00)\"]").nth(1).hover();
  await page.locator("//DIV[normalize-space() = \"Add Schedule Options\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Create your own schedule\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Time*\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"to\"]").hover();
  await page.getByPlaceholder("H:MMpm").click();
  await page.keyboard.press("Shift");
  await page.keyboard.up("Home");
  await page.keyboard.press("Shift");
  await page.getByPlaceholder("H:MMpm").fill("60000");
  await page.waitForTimeout(1000);
  await page.getByPlaceholder("H:MMpm").fill("60000");
  await page.waitForTimeout(1000);
  await page.locator("//DIV[normalize-space() = \"If you would also like to add schedules now, complete the fields below.\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Duration of Slots (min)\"]").hover();
  await page.locator("INPUT[type='number']").fill("30");
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.getByRole('heading', { name: "Interview Preferences" }).hover();
  await page.locator("div.col-xs-4.interview-info>dl.dl-horizontal").hover();
  await page.getByRole('heading', { name: "1 Schedule, 2 Slots" }).hover();
  await page.getByRole('button', { name: "Actions" }).click();
  await page.getByRole('link', { name: "Assign Interviewer" }).click();
  await page.getByRole('heading', { name: "Assign Interviewer" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Interviewer Name\"]").hover();
  await page.getByRole('button', { name: "-- Interviewer Name --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Jane Doe\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Interviewer Name\"]").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Assign" }).click();
  await page.waitForLoadState('load');
  await expect(page.locator("//dt[normalize-space()=\"Interviewer\"]//following-sibling::dd")).toHaveText("Jane Doe");
  await page.locator("h3.time-slot-time>tt-date-time-display.ng-binding.ng-isolate-scope").hover();
  await page.locator("//tt-date-time-display[normalize-space()=\"10:30pm - 11:00pm PDT\"]/following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Add New Applicant" }).click();
  await page.getByRole('heading', { name: "Add Student" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Student*\"]").hover();
  await page.getByPlaceholder("Name or Student Id").click();
  await page.waitForTimeout(1000);
  await page.keyboard.press("ArrowDown");
  await page.getByRole('heading', { name: "Add Student" }).click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Add" }).click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Apply" }).click();
  await page.waitForLoadState('load');
  await expect(page.locator("//div[normalize-space()=\"Alexa Kane\"]/ancestor::div[@class=\"entity-short-summary\"]//span[contains(@class,\"badge\")]")).toHaveText("Not Notified");
  await page.locator("//tt-date-time-display[normalize-space()=\"10:30pm - 11:00pm PDT\"]/following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Notify Interview Time" }).click();
  await page.getByRole('heading', { name: "Notify" }).hover();
  await page.locator("//DIV[normalize-space() = \"Do you want to notify Alexa Kane about their scheduled interview with an email?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Confirm" }).click();
  await page.getByRole('heading', { name: "Success!" }).hover();
  await page.locator("//DIV[normalize-space() = \"Alexa Kane was successfully notified of their schedule interview.\"]").nth(1).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.waitForLoadState('load');
  await expect(page.locator("//div[normalize-space()=\"Alexa Kane\"]/ancestor::div[@class=\"entity-short-summary\"]//span[contains(@class,\"badge\")]")).toHaveText("Notified");
  await page.locator("//SPAN[normalize-space() = \"12twenty Meeting\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"12twenty Meeting\"]/following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Copy Meeting URL" }).click();
  await page.getByRole('heading', { name: "Select Link to Copy" }).hover();
  await page.locator("//SPAN[normalize-space() = \"Admin Link\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Jane Doe\"]").hover();
  await page.locator("a.ng-binding.ng-isolate-scope>i.far.fa-copy.copy-url-icon").nth(1).click();
  await page.locator("//SPAN[normalize-space() = \"The link was copied to the clipboard\"]").hover();
  selector = MK.onSetGV(`//span[normalize-space()="Jane Doe"]/following-sibling::tt-clipboard-button`, null);
  await context.grantPermissions([
  'clipboard-read',
  'clipboard-write'
  ]);
  await page.locator(selector).click;
  await page.waitForTimeout(500);
  copiedText = await page.evaluate(async () => {
  return await navigator.clipboard.readText();
});
