// TC: TC_A83403
// Events - Pre-registration survey response included in export

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Events - Pre-registration survey response included in export", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Events" }).click();
  await page.getByRole('link', { name: "Host an Event" }).click();
  await page.getByRole('heading', { name: "General Info" }).hover();
  await page.getByPlaceholder("Event Name").fill("Muuktest Registration Survey");
  await page.locator("//LABEL[normalize-space() = \"Event Type*\"]").hover();
  await page.locator("SELECT[id='EventTypeId'][name='EventTypeId']").click();
  await page.keyboard.press("Mock Interview");
  await page.locator("//LABEL[normalize-space() = \"Location*\"]").hover();
  await page.getByPlaceholder("Location").fill("Location 1");
  await page.locator("//LABEL[normalize-space() = \"# of Attendees Permitted*\"]").hover();
  await page.getByPlaceholder("# of Attendees Permitted").fill("10");
  await page.locator("//LABEL[normalize-space() = \"Dress Attire*\"]").hover();
  await page.locator("SELECT[id='DressAttireId'][name='DressAttireId']").click();
  await page.keyboard.press("Business Professional");
  await page.locator("//LABEL[normalize-space() = \"Work Authorization Requirement*\"]").hover();
  await page.getByRole('button', { name: "-- Work Authorization Requirement --" }).click();
  await page.locator("//LABEL[normalize-space() = \"All Work Authorizations Accepted\"]").click();
  await page.getByRole('heading', { name: "Event Dates" }).click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(17).click();
  await page.getByPlaceholder("H:MMpm").fill("1:15pm");
  await page.getByPlaceholder("H:MMpm").fill("1:45pm");
  await page.locator("//LABEL[normalize-space() = \"Student Registration*\"]").click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").fill("12:15am");
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").fill("11:55pm");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Student Publish Date *\"]").click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").fill("12:15am");
  await page.getByRole('heading', { name: "Event Description" }).hover();
  await page.getByRole('heading', { name: "19 Steps" }).click();
  await page.getByRole('heading', { name: "Registration Survey" }).click();
  await page.locator("//LABEL[normalize-space() = \"Off\"]").click();
  await page.getByRole('link', { name: "Add a Question" }).click();
  await page.locator("//LABEL[normalize-space() = \"Question\"]").hover();
  await page.locator("span.multiline-lookup>input.form-control.ng-untouched.ng-scope.ng-valid-maxlength.ng-not-empty.ng-dirty.ng-valid-parse.ng-valid.ng-valid-required").fill("Select meal option");
  await page.locator("//LABEL[normalize-space() = \"Type\"]").hover();
  await page.locator("//label[normalize-space()=\"Type\"]/following-sibling::div//select").click();
  await page.keyboard.press("Dropdown (Single Select)");
  await page.locator("//LABEL[normalize-space() = \"Options\"]").hover();
  await page.locator("div.controls.form-controls>textarea.ng-untouched.ng-scope.ng-not-empty.ng-dirty.ng-valid-parse.ng-valid.ng-valid-required").fill("`Bee");
  await page.getByRole('heading', { name: "Eligibility" }).hover();
  await page.getByRole('heading', { name: "Eligibility" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Student Group*\"]").hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Select all\"]").nth(1).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Degree Level\"]").click();
  await page.getByRole('button', { name: "Use My Information" }).click();
  await page.getByPlaceholder("Contact Phone").fill("9153455681");
  await page.getByRole('heading', { name: "Admin" }).click();
  await page.locator("//LABEL[normalize-space() = \"Event Source\"]").click();
  await page.locator("SELECT[id='SourceId'][name='SourceId']").click();
  await page.keyboard.press("Career Center Event");
  await page.locator("//LABEL[normalize-space() = \"Employer Registrants Visibility\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Allow employers to view student registrants\"]").click();
  await page.getByRole('heading', { name: "Event Dates" }).click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(17).click();
  await page.getByPlaceholder("H:MMpm").fill("1:15pm");
  await page.getByPlaceholder("H:MMpm").fill("1:45pm");
  await page.locator("//LABEL[normalize-space() = \"Student Registration*\"]").click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").fill("12:15am");
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").fill("11:55pm");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Student Publish Date *\"]").click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").fill("12:15am");
  await page.getByRole('button', { name: "Save" }).click();
  await page.waitForTimeout(5000);
  await page.getByRole('link', { name: "Schedule" }).click();
  await page.locator("//DIV[normalize-space() = \"No schedules have been created yet\"]").hover();
  await page.locator("//DIV[normalize-space() = \"Add Schedule\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Create your own schedule\"]").click();
  await page.locator("//SPAN[normalize-space() = \"to\"]").hover();
  await page.waitForTimeout(1000);
  await page.getByPlaceholder("H:MMpm").click();
  await page.waitForTimeout(1000);
  await page.getByPlaceholder("H:MMpm").click();
  await page.keyboard.press("1:45pm");
  await page.waitForTimeout(1000);
  await page.locator("//DIV[normalize-space() = \"If you would also like to add schedules now, complete the fields below.\"]").click();
  await page.locator("INPUT[type='number']").fill("10");
  await page.locator("//DIV[normalize-space() = \"If you would also like to add schedules now, complete the fields below.\"]").click();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByRole('button', { name: "Actions" }).click();
  await page.getByRole('link', { name: "Edit Schedule" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('link', { name: "Save" }).click();
  await page.locator("BUTTON[type='button']").nth(13).click();
  await page.getByRole('link', { name: "12twenty" }).click();
  await page.locator("//SPAN[normalize-space() = \"12twenty Meeting\"]").hover();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  selector = MK.onSetGV(`//BUTTON[@type=\'button\'][normalize-space() = "Reset Filters"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.getByRole('button', { name: "Reset Filters" }).click();
  }
  await page.getByRole('link', { name: "Test Student #0003" }).click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Login As" }).click();
  await page.waitForTimeout(2000);
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.getByRole('link', { name: "Events" }).click();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").hover();
  await page.getByPlaceholder("Employer, Event Name, or Keyword").fill("Muuktest Registration Survey");
  await page.locator("//SPAN[normalize-space() = \"Muuktest Registration Survey\"]").nth(3).click();
  await page.getByRole('link', { name: "Select Time Slot" }).click();
  await page.getByRole('heading', { name: "Survey" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Select meal option\"]").hover();
  await page.locator("SELECT[id='Q0']").selectOption("Beef");
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Continue" }).click();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to register for this event?\"]").hover();
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Back" }).hover();
  await page.getByRole('link', { name: "Register" }).click();
  await page.getByRole('heading', { name: "Registration Complete" }).hover();
  await page.getByRole('link', { name: "Go Back to Event Page" }).click();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").click();
  await page.getByRole('link', { name: "Log Out" }).click();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('link', { name: "Events" }).click();
  await page.locator("//SPAN[normalize-space() = \"Muuktest Registration Survey\"]").nth(3).click();
  await page.getByRole('link', { name: "Registered Students (1)" }).click();
  await expect(page.getByRole('link', { name: "Test Student #0001" })).toHaveText("` + textContent + `");
  await page.locator("button.btn.dropdown-toggle.ng-binding.btn-icon>span.glyphicon.glyphicon-option-vertical.ng-scope").nth(1).click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Schedule" }).click();
  await page.locator("BUTTON[type='button']").nth(16).click();
  await page.getByRole('link', { name: "Unregister Student" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByRole('heading', { name: "19 Steps" }).click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete Event" }).hover();
  await page.getByRole('button', { name: "Delete Event" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Home" }).click();
  await page.getByRole('link', { name: "Events" }).click();
  await page.reload();
  await page.waitForLoadState('load');
});
