// TC: TC_A83602
// Employer Tags - Admin can add values and students can assign, delete, filter for values

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Employer Tags - Admin can add values and students can assign, delete, filter for values", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.locator("//*[normalize-space() = \"Site Management\"]//button[contains(@data-toggle,\"collapse\")]").click();
  await page.getByRole('link', { name: "Site Settings" }).click();
  await page.getByRole('link', { name: "Employer Relations" }).click();
  await page.locator("//LABEL[normalize-space() = \"Enable Student Employer Tagging\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"On\"]").nth(3).hover();
  await page.getByRole('link', { name: "Picklists" }).click();
  await page.getByRole('link', { name: "Student Employer Tags" }).click();
  await page.getByRole('heading', { name: "Student Employer Tags" }).hover();
  await page.locator("//SPAN[normalize-space() = \"Action\"]").click();
  await page.getByRole('link', { name: "Add New Option" }).click();
  await page.getByRole('heading', { name: "Student Employer Tags Option" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Option Name*\"]").hover();
  await page.getByPlaceholder("Option Name").fill("Test Tag 1 - Manually Added");
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.locator("//SPAN[@title='Test Tag 1 - Manually Added'][normalize-space() = \"Test Tag 1 - Manually Added\"]").hover();
  await page.locator("BUTTON[type='button']").nth(6).click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.getByPlaceholder("Option Name").fill("Test Tag 1");
  await page.getByRole('button', { name: "Save" }).click();
  await page.locator("//SPAN[normalize-space() = \"Action\"]").click();
  await page.getByRole('link', { name: "Bulk Upload Options" }).click();
  await page.locator("//P[normalize-space() = \"To upload picklist options, please download the picklist template, add your new values, and upload the file below.\"]").click();
  await page.locator("//DIV[normalize-space() = \"Drop file to attach, or browse\"]").hover();
  await page.locator("//DIV[normalize-space() = \"Allowed file types: csv\"]").hover();
  fileName = MK.onSetGV(`e2e_StudentEmployerTags_template.csv`, null);
  var fileInput = await page.$("INPUT[type='file']");
  var filePath ="./test/"+fileName;
  if(fileInput){
  await fileInput.setInputFiles(filePath);
  }
  else{
  throw new Error('Element to upload file is not present.');
  }
  await page.locator("//SPAN[normalize-space() = \"e2e_StudentEmployerTags_template.csv\"]").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Upload" }).click();
  await page.waitForLoadState('load');
  await page.locator("//SPAN[@title='Test Tag 1'][normalize-space() = \"Test Tag 1\"]").hover();
  await page.locator("//SPAN[@title='Test Tag 2'][normalize-space() = \"Test Tag 2\"]").hover();
  await page.locator("//SPAN[@title='Test Tag 3'][normalize-space() = \"Test Tag 3\"]").hover();
  await page.locator("BUTTON[type='button']").nth(8).click();
  await page.getByRole('link', { name: "Merge" }).click();
  await page.locator("//DIV[@role='alert'][normalize-space() = \"Warning: Merging one option into another will update historical data as well. This action cannot be undone.\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Option Name:\"]").hover();
  await page.locator("//DIV[normalize-space() = \"Test Tag 3\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Merge Into:\"]").hover();
  await page.getByRole('button', { name: "-- Please Select an Option --" }).click();
  await page.getByPlaceholder("Search options...").fill("Test Tag 2");
  await page.locator("//LABEL[normalize-space() = \"Test Tag 2\"]").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Merge" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("e2e");
  await page.locator("BUTTON[type='button']").nth(4).click();
  await page.getByRole('link', { name: "e2e Test Student" }).hover();
  await page.locator("//a[normalize-space()=\"e2e Test Student\"]/ancestor::tr//button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Login as user..." }).click();
  await page.getByRole('heading', { name: "Login as e2e Test Student" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.waitForTimeout(2000);
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.getByRole('link', { name: "Employers" }).click();
  selector = MK.onSetGV(`//BUTTON[@type=\'button\'][normalize-space() = "Reset Filters"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.getByRole('button', { name: "Reset Filters" }).click();
  }
  await page.locator("tr.ng-scope.ng-isolate-scope>td.select-checkbox").click();
  await page.locator("button.btn.dropdown-toggle.ng-binding.btn-icon>span.glyphicon.glyphicon-option-vertical.ng-scope").click();
  await page.getByRole('link', { name: "Add Tag (1)" }).click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Test Tag 1\"]").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.getByRole('link', { name: "12twenty, Inc." }).hover();
  await page.getByRole('link', { name: "12twenty, Inc." }).click();
  await page.locator("//SPAN[normalize-space() = \"TEST TAG 1\"]").hover();
  await page.getByRole('link', { name: "Employers" }).click();
  await page.getByRole('button', { name: "More Filters" }).click();
  await page.getByPlaceholder("Search filters").fill("tag");
  await page.getByRole('button', { name: "Student Employer Tags" }).click();
  await page.locator("//SPAN[normalize-space() = \"Student Employer Tags\"]").nth(1).hover();
  await page.locator("//LABEL[normalize-space() = \"Test Tag 1\"]").click();
  await page.locator("//SPAN[normalize-space() = \"Student Employer Tags\"]").click();
  await expect(page.locator("//div[@class=\"results-header-right\"]//DIV[contains(normalize-space(),\"Results:\")]")).toHaveText("Results: 1");
  await expect(page.getByRole('link', { name: "12twenty, Inc." })).toHaveText("` + textContent + `");
  await page.locator("tr.ng-scope.ng-isolate-scope>td.select-checkbox").click();
  await page.locator("button.btn.dropdown-toggle.ng-binding.btn-icon>span.glyphicon.glyphicon-option-vertical.ng-scope").click();
  await page.getByRole('link', { name: "Remove Tag (1)" }).click();
  await page.getByRole('heading', { name: "Remove Company Tag (1)" }).hover();
  await page.locator("//LABEL[@id='undefined-label'][normalize-space() = \"Company Tags\"]").hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Test Tag 1\"]").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.locator("//SPAN[normalize-space() = \"Tag removed from 1 employer(s).\"]").hover();
  await page.getByRole('link', { name: "Employers" }).click();
  await page.reload();
  await page.reload();
  await page.getByRole('button', { name: "Reset Filters" }).click();
  await page.getByRole('link', { name: "12twenty, Inc." }).click();
  await page.getByRole('link', { name: "Employers" }).click();
  await page.locator("tr.ng-scope.ng-isolate-scope>td.select-checkbox").click();
  await page.locator("tr.ant-table-row.ant-table-row-level-0>td.ant-table-cell.ant-table-cell-ellipsis.ant-table-cell-row-hover").click();
  await page.locator("tr.ant-table-row.ant-table-row-level-0>td.ant-table-cell.ant-table-cell-ellipsis.ant-table-cell-row-hover").click();
  await page.locator("tr.ant-table-row.ant-table-row-level-0>td.ant-table-cell.ant-table-cell-ellipsis.ant-table-cell-row-hover").nth(2).click();
  await page.locator("tr.ant-table-row.ant-table-row-level-0>td.ant-table-cell.ant-table-cell-ellipsis.ant-table-cell-row-hover").nth(2).click();
  await page.locator("button.btn.dropdown-toggle.ng-binding.btn-icon>span.glyphicon.glyphicon-option-vertical.ng-scope").click();
  await page.getByRole('link', { name: "Add Tag (5)" }).click();
  await page.getByRole('heading', { name: "Add Company Tag (5)" }).hover();
  await page.locator("//LABEL[@id='undefined-label'][normalize-space() = \"Company Tags\"]").hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Test Tag 1\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Test Tag 2\"]").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.getByRole('button', { name: "More Filters" }).click();
  await page.getByPlaceholder("Search filters").fill("tag");
  await page.getByRole('button', { name: "Student Employer Tags" }).click();
  await page.locator("//SPAN[normalize-space() = \"Student Employer Tags\"]").nth(1).hover();
  await page.locator("//LABEL[normalize-space() = \"Test Tag 1\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Test Tag 2\"]").click();
  await page.locator("//SPAN[normalize-space() = \"Student Employer Tags\"]").click();
  await expect(page.locator("//div[@class=\"results-header-right\"]//DIV[contains(normalize-space(),\"Results:\")]")).toHaveText("Results: 5");
  await page.getByRole('link', { name: "12twenty, Inc." }).click();
  await page.locator("//SPAN[normalize-space() = \"TEST TAG 1\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"TEST TAG 2\"]").hover();
  await page.getByRole('link', { name: "Employers" }).click();
  await page.locator("tr>th.select-checkbox").click();
  await page.locator("button.btn.dropdown-toggle.ng-binding.btn-icon>span.glyphicon.glyphicon-option-vertical.ng-scope").click();
  await page.getByRole('link', { name: "Remove Tag (5)" }).click();
  await page.getByRole('heading', { name: "Remove Company Tag (5)" }).hover();
  await page.locator("//LABEL[@id='undefined-label'][normalize-space() = \"Company Tags\"]").hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Test Tag 1\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Test Tag 2\"]").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.locator("//SPAN[normalize-space() = \"Tag removed from 5 employer(s).\"]").hover();
  await page.reload();
  await page.reload();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").click();
  await page.getByRole('link', { name: "Log Out" }).click();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('link', { name: "Site Settings" }).click();
  await page.getByRole('link', { name: "Employer Relations" }).click();
  await page.getByRole('link', { name: "Picklists" }).click();
  await page.getByRole('link', { name: "Student Employer Tags" }).click();
  await page.locator("BUTTON[type='button']").nth(6).click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete?" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to delete Test Tag 1?\"]").nth(1).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.locator("BUTTON[type='button']").nth(6).click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete?" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to delete Test Tag 2?\"]").nth(1).hover();
  await page.getByRole('button', { name: "OK" }).click();
});
