// TC: TC_A78709
// Events - Verify name tags can be printed and edited

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Events - Verify name tags can be printed and edited", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Events" }).click();
  await page.getByRole('link', { name: "Host an Event" }).click();
  await page.getByRole('heading', { name: "Host an Event" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Event Name*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Event Type*\"]").hover();
  await page.getByPlaceholder("Event Name").fill("Muuktest Tag Event");
  await page.locator("SELECT[id='EventTypeId'][name='EventTypeId']").selectOption("number:1499993124744");
  await page.locator("//LABEL[normalize-space() = \"Event Format\"]").hover();
  await page.locator("SELECT[id='EventFormatId'][name='EventFormatId']").selectOption("number:3");
  await page.locator("//DIV[normalize-space() = \"You will be able to add a virtual meeting URL on the following page\"]").nth(2).hover();
  await page.locator("//LABEL[normalize-space() = \"# of Attendees Permitted*\"]").hover();
  await page.getByPlaceholder("# of Attendees Permitted").fill("10");
  await page.locator("//LABEL[normalize-space() = \"Dress Attire*\"]").hover();
  await page.getByPlaceholder("Briefly describe who this event is meant for").fill("All students");
  await page.locator("SELECT[id='DressAttireId'][name='DressAttireId']").selectOption("number:2");
  await page.locator("//LABEL[normalize-space() = \"Employer Name\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Presenter\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Industry\"]").hover();
  await page.locator("SELECT[id='ConsolidatedIndustryId'][name='ConsolidatedIndustryId']").selectOption("number:101499994348783");
  await page.locator("//LABEL[normalize-space() = \"Work Authorization Requirement*\"]").hover();
  await page.locator("SELECT[id='ConsolidatedIndustryId'][name='ConsolidatedIndustryId']").selectOption("number:101499994348782");
  await page.locator("//LABEL[normalize-space() = \"Work Authorization Requirement*\"]").hover();
  await page.getByRole('button', { name: "-- Work Authorization Requirement --" }).click();
  await page.locator("//LABEL[normalize-space() = \"All Work Authorizations Accepted\"]").click();
  await page.getByRole('heading', { name: "Event Dates" }).click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(17).click();
  await page.getByPlaceholder("H:MMpm").fill("1:15pm");
  await page.getByPlaceholder("H:MMpm").fill("1:45pm");
  await page.locator("//LABEL[normalize-space() = \"Student Registration*\"]").click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").fill("12:15am");
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").fill("10:00pm");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Student Publish Date *\"]").click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").fill("12:15am");
  await page.getByRole('heading', { name: "Additional Registration Method" }).click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Select all\"]").nth(1).click();
  await page.locator("//LABEL[normalize-space() = \"Student Group*\"]").click();
  await page.getByRole('button', { name: "Use My Information" }).click();
  await page.locator("SELECT[id='SourceId'][name='SourceId']").selectOption("number:1030070311958");
  await page.locator("SELECT[id='custom_attribute_4'][name='custom_attribute_4']").selectOption("540016055100183");
  await page.locator("//LABEL[normalize-space() = \"Override Event Logo PNG, JPG, or GIF file type.150x150 minimum size recommended\"]").hover();
  await page.locator("div.uploaded-image-cmp>div.uploaded-image-no-image-container.ng-scope").click();
  fileName = MK.onSetGV(`logomuuk.jpg`, null);
  var fileInput = await page.$("INPUT[type='file']");
  var filePath ="./test/"+fileName;
  if(fileInput){
  await fileInput.setInputFiles(filePath);
  }
  else{
  throw new Error('Element to upload file is not present.');
  }
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "OK" }).click();
  await page.getByRole('heading', { name: "Event Dates" }).click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(17).click();
  await page.getByPlaceholder("H:MMpm").fill("1:15pm");
  await page.getByPlaceholder("H:MMpm").fill("1:45pm");
  await page.locator("//LABEL[normalize-space() = \"Student Registration*\"]").click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").fill("12:15am");
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").fill("11:55pm");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Student Publish Date *\"]").click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").fill("12:15am");
  await page.waitForTimeout(20000);
  await page.getByRole('button', { name: "Save" }).click();
  await page.getByRole('heading', { name: "Muuktest Tag Event" }).hover();
  await page.locator("//SPAN[normalize-space() = \"Please select a virtual meeting platform\"]").hover();
  await page.locator("BUTTON[type='button']").nth(3).click();
  await page.getByRole('link', { name: "12twenty" }).click();
  await page.getByRole('link', { name: "Registered Students (0)" }).click();
  await page.locator("//h3[normalize-space()=\"Registered Students\"]/following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Add Registrant" }).click();
  await page.getByRole('heading', { name: "Register Student" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Student*\"]").hover();
  await page.locator("INPUT[type='text'][placeholder=''][name='StudentId']").fill("Cydney Moore");
  await page.locator("//STRONG[normalize-space() = \"Cydney Moore\"]").click();
  await page.getByRole('link', { name: "Register" }).click();
  await page.getByRole('link', { name: "Register" }).click();
  await page.locator("//h3[normalize-space()=\"Registered Students\"]/following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Add Registrant" }).click();
  await page.locator("INPUT[type='text'][placeholder=''][name='StudentId']").fill("e2e Test Student");
  await page.locator("//STRONG[normalize-space() = \"e2e Test Student\"]").click();
  await page.getByRole('link', { name: "Register" }).click();
  await page.getByRole('link', { name: "Register" }).click();
  await page.locator("//h3[normalize-space()=\"Registered Students\"]/following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Add Registrant" }).click();
  await page.locator("INPUT[type='text'][placeholder=''][name='StudentId']").fill("Max ");
  await page.locator("//DIV[normalize-space() = \"Max Peterson (Max.Peterson@campuswide.com) – 2028\"]").nth(2).click();
  await page.getByRole('link', { name: "Register" }).click();
  await page.getByRole('link', { name: "Register" }).click();
  await page.getByRole('link', { name: "Cydney Moore" }).hover();
  await page.getByRole('link', { name: "Max Peterson" }).hover();
  await page.getByRole('link', { name: "e2e Test Student" }).hover();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Print Name Tags" }).click();
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.getByRole('heading', { name: "Muuktest Tag Event" }).hover();
  await page.getByRole('heading', { name: "Not Yet Printed" }).hover();
  await page.getByRole('heading', { name: "Printed" }).hover();
  await page.getByRole('heading', { name: "Muuktest Tag Event" }).hover();
  await page.locator("tr>th.select-checkbox").click();
  await page.locator("//h3[normalize-space()=\"Registered Students\"]/following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Generate Name Tags (3)" }).click();
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForTimeout(3000);
  await page.getByRole('link', { name: "e2e Test Student" }).hover();
  await page.locator("//A[normalize-space() = \"e2e Test Student\"]/following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Print Name Tag" }).click();
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('heading', { name: "Muuktest Tag Event" }).hover();
  await page.locator("//LABEL[normalize-space() = \"First Name\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Last Name\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Line 3\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Line 4\"]").hover();
  await page.getByRole('button', { name: "Print Name Tag" }).hover();
  await page.getByRole('link', { name: "Cydney Moore" }).click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Login As" }).click();
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('heading', { name: "My Calendar" }).hover();
  await page.getByRole('link', { name: "Muuktest Tag Event" }).click();
  await page.getByRole('heading', { name: "Muuktest Tag Event" }).hover();
  await page.locator("//dt[normalize-space()=\"Date and Time\"]").hover();
  await page.locator("dl.dl-horizontal>dt.ng-scope").hover();
  await page.locator("//dt[normalize-space()=\"Location\"]").hover();
  await page.locator("dl.dl-horizontal>dt.ng-scope").nth(1).hover();
  await page.locator("//P[contains(normalize-space(),\"Event Type: Career Center WorkshopEvent Description: Virtual\")]").hover();
  await page.getByRole('link', { name: "Events" }).click();
  await page.locator("//SPAN[normalize-space() = \"Muuktest Tag Event\"]").click();
  await page.getByRole('link', { name: "Registered Students (3)" }).click();
  await page.getByRole('link', { name: "e2e Test Student" }).hover();
  await page.locator("//A[normalize-space() = \"e2e Test Student\"]/following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Cancel Registration" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByRole('link', { name: "Max Peterson" }).hover();
  await page.locator("//A[normalize-space() = \"Max Peterson\"]/following::button[@aria-label=\"Options\"]").click();
  await page.locator("//A[normalize-space() = \"Max Peterson\"]/following::A[normalize-space() = \"Cancel Registration\"]").click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByRole('link', { name: "Cydney Moore" }).hover();
  await page.locator("//A[normalize-space() = \"Cydney Moore\"]/following::button[@aria-label=\"Options\"]").click();
  await page.locator("//A[normalize-space() = \"Cydney Moore\"]/following::A[normalize-space() = \"Cancel Registration\"]").click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete Event" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this event?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Event" }).click();
  await page.getByRole('heading', { name: "Events" }).hover();
  await page.reload();
  await page.reload();
});
