// TC: TC_A79933
// Users - Admin Groups - Create group and validate record visibility

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Users - Admin Groups - Create group and validate record visibility", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.waitForLoadState('load');
  selector = MK.onSetGV(`//BUTTON[@type=\'button\'][normalize-space() = "Reset Filters"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.getByRole('button', { name: "Reset Filters" }).click();
  }
  await page.getByRole('button', { name: "More Filters" }).click();
  await page.getByPlaceholder("Search filters").fill("id");
  await page.getByRole('button', { name: "12twenty ID" }).click();
  await page.locator("//SPAN[normalize-space() = \"12twenty ID\"]").nth(1).hover();
  await page.getByPlaceholder("12twenty ID").fill("540016054866989");
  await page.getByRole('link', { name: "Cydney Moore" }).click();
  await page.waitForLoadState('load');
  await page.waitForTimeout(2000);
  await page.getByRole('link', { name: "Profile" }).click();
  await page.waitForLoadState('load');
  selector = MK.onSetGV(`//dt[normalize-space()="Student Group"]//following-sibling::dd[1]//span//span[not(contains(text(),"e2e Test Group"))]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.getByRole('button', { name: "Edit" }).click();
  await page.locator("//LABEL[contains(normalize-space(),\"Student Group*\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Student Group*\")]/following::button").click();
  await page.locator("//LABEL[normalize-space() = \"e2e Test Group\"]").click();
  await page.getByRole('button', { name: "Save" }).click();
  }
  await expect(page.locator("//dt[normalize-space()=\"Student Group\"]//following-sibling::dd")).toContainText("e2e Test Group");
  await page.locator("//a[normalize-space()=\"Site Management\"]/following-sibling::button").click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByRole('link', { name: "Admins" }).click();
  await page.getByRole('link', { name: "Groups" }).click();
  selector = MK.onSetGV(`//DIV[normalize-space() = "Admin Test Group - Muuktest"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.locator("//DIV[normalize-space() = \"Admin Test Group - Muuktest\"]").hover();
  await page.locator("button.btn.dropdown-toggle.ng-binding.btn-icon>span.glyphicon.glyphicon-option-vertical.ng-scope").click();
  await page.getByRole('link', { name: "Delete Group" }).click();
  await page.getByRole('heading', { name: "Delete Admin Group" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this admin group?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Delete Admin Group" }).click();
  await page.waitForLoadState('load');
  }
  await page.getByRole('link', { name: "Add a new Group" }).click();
  await page.locator("//LABEL[normalize-space() = \"Student Groups\"]").hover();
  await page.getByPlaceholder("Admin Group Name").fill("Admin Test Group - Muuktest");
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"e2e Test Group\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Student Groups\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Major/Academic Program\"]").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Add" }).click();
  await page.locator("//DIV[normalize-space() = \"Admin Test Group - Muuktest\"]").hover();
  await page.locator("dl.dl-horizontal>dt").nth(1).hover();
  await page.locator("//SPAN[normalize-space() = \"e2e Test Group\"]").nth(1).hover();
  await page.getByRole('link', { name: "Users" }).click();
  await page.locator("//SPAN[normalize-space() = \"Admin Admin\"]").nth(1).hover();
  await page.locator("BUTTON[type='button']").nth(14).click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.getByRole('heading', { name: "Edit Admin Admin" }).hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Admin Test Group - Muuktest\"]").click();
  await page.getByRole('link', { name: "Save" }).click();
  await page.getByRole('heading', { name: "Success!" }).hover();
  await page.locator("//DIV[normalize-space() = \"You have successfully saved the user.\"]").nth(1).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.locator("//SPAN[normalize-space() = \"Admin Admin\"]").nth(1).hover();
  await page.locator("BUTTON[type='button']").nth(14).click();
  await page.getByRole('link', { name: "Login as user..." }).click();
  await page.getByRole('heading', { name: "Login as Admin Admin" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.waitForTimeout(2000);
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  selector = MK.onSetGV(`//BUTTON[@type=\'button\'][normalize-space() = "Reset Filters"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.getByRole('button', { name: "Reset Filters" }).click();
  }
  await page.locator("//DIV[normalize-space() = \"Results: 1\"]").click();
  await page.getByRole('link', { name: "Cydney Moore" }).hover();
  await page.locator("//B[normalize-space() = \"log out\"]").click();
  await page.waitForLoadState('load');
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.locator("//a[normalize-space()=\"Site Management\"]/following-sibling::button").click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByRole('link', { name: "Admins" }).click();
  await page.getByRole('link', { name: "Users" }).click();
  await page.locator("BUTTON[type='button']").nth(14).click();
  await page.locator("button.btn.dropdown-toggle.ng-binding.btn-icon>span.glyphicon.glyphicon-option-vertical.ng-scope").nth(1).click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.getByRole('heading', { name: "Edit Admin Admin" }).click();
  await page.getByRole('heading', { name: "Edit Admin Admin" }).hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Admin Test Group - Muuktest\"]").click();
  await page.getByRole('link', { name: "Save" }).click();
  await page.getByRole('heading', { name: "Success!" }).hover();
  await page.locator("//DIV[normalize-space() = \"You have successfully saved the user.\"]").nth(1).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.reload();
  await page.locator("button.btn.dropdown-toggle.ng-binding.btn-icon>span.glyphicon.glyphicon-option-vertical.ng-scope").nth(1).click();
  await page.getByRole('link', { name: "Login as user..." }).click();
  await page.getByRole('heading', { name: "Login as Admin Admin" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.waitForTimeout(2000);
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('e2e-tests-campuswide.admin.qa-12twenty.com/dashboard/');
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByRole('button', { name: "Reset Filters" }).click();
  await page.locator("//B[normalize-space() = \"log out\"]").click();
  await page.waitForLoadState('load');
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.locator("//a[normalize-space()=\"Site Management\"]/following-sibling::button").click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByRole('link', { name: "Admins" }).click();
  await page.getByRole('link', { name: "Groups" }).click();
  await page.locator("//DIV[normalize-space() = \"Admin Test Group - Muuktest\"]").hover();
  await page.locator("button.btn.dropdown-toggle.ng-binding.btn-icon>span.glyphicon.glyphicon-option-vertical.ng-scope").click();
  await page.getByRole('link', { name: "Delete Group" }).click();
  await page.getByRole('heading', { name: "Delete Admin Group" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this admin group?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Delete Admin Group" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByRole('button', { name: "More Filters" }).click();
  await page.getByPlaceholder("Search filters").fill("id");
  await page.getByRole('button', { name: "12twenty ID" }).click();
  await page.locator("//SPAN[normalize-space() = \"12twenty ID\"]").nth(1).hover();
  await page.getByPlaceholder("12twenty ID").fill("540016054866989");
  await page.getByRole('link', { name: "Cydney Moore" }).click();
  await page.getByRole('link', { name: "Profile" }).click();
  await page.getByRole('button', { name: "Edit" }).click();
  await page.locator("//LABEL[contains(normalize-space(),\"Student Group*\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Student Group*\")]/following::button").click();
  await page.locator("//LABEL[normalize-space() = \"e2e Test Group\"]").click();
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("//dt[normalize-space()=\"Student Group\"]//following-sibling::dd")).toContainText("e2e Test Group");
});
