// TC: TC_A80121
// Appointments - Settings - Add and delete a new appointment configuration

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Appointments - Settings - Add and delete a new appointment configuration", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Appointments" }).click();
  selector = MK.onSetGV(`//DIV[normalize-space() = "e2e Test Admin – 7am- 9am"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.locator("//DIV[normalize-space() = \"e2e Test Admin – 7am- 9am\"]").click();
  await page.locator("//H3[normalize-space() = \"Appointment Block\"]/ancestor::div[@class=\"modal-header\"]//button[@data-toggle=\"dropdown\"]").click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.getByRole('link', { name: "Delete Block" }).click();
  await page.getByRole('heading', { name: "Delete Appointment Block" }).click();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this appointment block?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Yes, delete it" }).click();
  await page.waitForLoadState('load');
  }
  await page.locator("//a[normalize-space()=\"Site Management\"]/following-sibling::button").click();
  await page.getByRole('link', { name: "Site Settings" }).click();
  await page.getByRole('link', { name: "Appointments" }).click();
  await page.getByRole('heading', { name: "Appointment Booking Settings New!" }).hover();
  selector = MK.onSetGV(`//DD[normalize-space()="General Career Coaching, Resume and Cover Letter Review"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.locator("button.btn.dropdown-toggle.ng-binding.btn-icon>span.glyphicon.glyphicon-option-vertical.ng-scope").click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this configuration?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Delete" }).click();
  await page.locator("//SPAN[normalize-space() = \"Successfully deleted configuration\"]").hover();
  }
  selector = MK.onSetGV(`//LABEL[normalize-space() = "Enable New Appointment Settings"]/following-sibling::div//toggle//div[contains(@class,"off")]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.locator("//LABEL[@id='undefined-label'][normalize-space() = \"Enable New Appointment Settings\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Enable New Appointment Settings\"]/following-sibling::div//toggle//div[contains(@class,\"off\")]").click();
  await page.getByRole('button', { name: "Save Changes" }).click();
  await page.getByRole('heading', { name: "Success!" }).hover();
  await page.locator("//DIV[normalize-space() = \"The configuration values have been successfully saved.\"]").nth(1).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.waitForLoadState('load');
  }
  await page.locator("//H3[contains(normalize-space(),\"Appointment Booking Settings\")]/following::button[contains(text(),\"New\")]").click();
  await page.locator("//LABEL[normalize-space() = \"Student Groups\"]").hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Group 1\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Student Groups\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Appointment Types\"]").hover();
  await page.getByRole('heading', { name: "41 Steps" }).click();
  await page.locator("//LABEL[normalize-space() = \"General Career Coaching\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Resume and Cover Letter Review\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Appointment Types\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Booking Start (Days Before)*\"]").hover();
  await page.getByPlaceholder("Booking Start (Days Before)").fill("2");
  await page.locator("//LABEL[normalize-space() = \"Booking Cutoff (Hours Before)*\"]").hover();
  await page.getByPlaceholder("Booking Cutoff (Hours Before)").fill("1");
  await page.locator("//LABEL[normalize-space() = \"Cancellation Cutoff (Hours Before)*\"]").hover();
  await page.getByRole('heading', { name: "Test ID: TC_A80121" }).fill("1");
  await page.locator("//LABEL[normalize-space() = \"Upcoming Appointment Limit*\"]").hover();
  await page.getByRole('heading', { name: "Appointments - Settings - Add and delete a new appointment configuration" }).fill("1");
  await page.locator("//LABEL[normalize-space() = \"Upcoming Appointment Limit Frequency*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Upcoming Appointment Limit Frequency*\"]//following::select").click();
  await page.waitForTimeout(1000);
  await page.keyboard.press("End");
  await page.locator("tr>th").hover();
  await page.locator("//SPAN[normalize-space() = \"15\"]").click();
  await page.locator("//SPAN[normalize-space() = \"60\"]").click();
  await page.locator("tr.ng-scope>td.ng-binding").nth(1).hover();
  await page.getByRole('heading', { name: "120 Steps" }).click();
  await page.getByRole('heading', { name: "Appointments - Settings - Add and delete a new appointment configuration" }).click();
  await page.getByRole('link', { name: "Save" }).click();
  await page.waitForTimeout(10000);
  await page.locator("//DT[normalize-space()=\"Student Groups\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Group 1\"]").nth(1).hover();
  await page.locator("//DT[normalize-space()=\"Appointment Types\"]").hover();
  await page.locator("//DD[normalize-space()=\"General Career Coaching, Resume and Cover Letter Review\"]").hover();
  await page.getByRole('link', { name: "Appointments" }).click();
  await page.getByRole('link', { name: "Block" }).click();
  await page.getByRole('heading', { name: "Create Appointment Block" }).hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(31).click();
  await page.waitForTimeout(1000);
  await page.getByPlaceholder("H:MMpm").fill("7:00am");
  await page.getByPlaceholder("H:MMpm").fill("60000");
  await page.locator("//LABEL[normalize-space() = \"Career Adviser *\"]").click();
  await page.locator("SELECT[id='AdviserId'][name='AdviserId']").click();
  await page.waitForTimeout(1000);
  await page.keyboard.press("Home");
  await page.keyboard.press("ArrowDown");
  await page.getByRole('button', { name: "-- Select Type(s) --" }).click();
  await page.locator("//LABEL[normalize-space() = \"General Career Coaching\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Resume and Cover Letter Review\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Type *\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Virtual\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Virtual Location Type*\"]").hover();
  await page.locator("SELECT[name='DetailedAppointmentBlockVirtualLocationTypeId']").click();
  await page.keyboard.press("ArrowDown");
  await page.getByRole('button', { name: "-- All Student Groups --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Group 1\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Student Group\"]").click();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(1).click();
  await page.waitForTimeout(10000);
  await page.getByRole('link', { name: "Create Block" }).click();
  await page.locator("//DIV[normalize-space() = \"e2e Test Admin – 7am- 9am\"]").hover();
  await page.waitForTimeout(10000);
  await page.locator("//a[normalize-space()=\"Site Management\"]/following-sibling::button").click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("Cydney");
  await page.waitForTimeout(1000);
  await page.locator("//a[normalize-space()=\"Cydney Moore\"]/ancestor::tr//button").click();
  await page.getByRole('link', { name: "Login as user..." }).click();
  await page.getByRole('heading', { name: "Login as Cydney Moore" }).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.waitForTimeout(2000);
  await page.getByRole('link', { name: "Appointments" }).click();
  await page.waitForTimeout(2000);
  await page.waitForLoadState('load');
  await page.getByRole('button', { name: "List" }).click();
  await page.getByRole('link', { name: "Week" }).click();
  await page.locator("//DIV[normalize-space() = \"e2e Test Admin – 7am- 9am\"]").click();
  await page.getByRole('link', { name: "View Available Slots" }).click();
  await page.getByRole('heading', { name: "Book Appointment" }).click();
  await page.locator("//LABEL[normalize-space() = \"Preferred Appointment Type*\"]").click();
  await page.locator("SELECT[name='SelectedAppointmentType']").click();
  await page.keyboard.press("ArrowDown");
  await page.locator("//LABEL[normalize-space() = \"Duration*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Preferred Appointment Type*\"]").click();
  await page.locator("SELECT[name='SelectedAppointmentType']").click();
  await page.keyboard.press("ArrowDown");
  await page.getByRole('link', { name: "Cancel" }).click();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.locator("//SPAN[normalize-space() = \"Site Settings\"]").click();
  await page.getByRole('link', { name: "Appointments" }).click();
  await page.locator("button.btn.dropdown-toggle.ng-binding.btn-icon>span.glyphicon.glyphicon-option-vertical.ng-scope").click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.getByPlaceholder("Booking Start (Days Before)").fill("3");
  await page.getByRole('link', { name: "Save" }).click();
  await page.locator("//SPAN[normalize-space() = \"Group 1\"]").nth(1).hover();
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.reload();
  await page.locator("//DIV[normalize-space() = \"e2e Test Admin – 7am- 9am\"]").hover();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.locator("button.btn.dropdown-toggle.ng-binding.btn-icon>span.glyphicon.glyphicon-option-vertical.ng-scope").click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.getByPlaceholder("Booking Start (Days Before)").fill("1");
  await page.getByRole('link', { name: "Save" }).click();
  await page.locator("//SPAN[normalize-space() = \"Group 1\"]").nth(1).hover();
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.reload();
  await page.reload();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.locator("button.btn.dropdown-toggle.ng-binding.btn-icon>span.glyphicon.glyphicon-option-vertical.ng-scope").click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this configuration?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Delete" }).click();
  await page.locator("//SPAN[normalize-space() = \"Successfully deleted configuration\"]").hover();
  await page.getByRole('link', { name: "Appointments" }).click();
  await page.locator("//DIV[normalize-space() = \"e2e Test Admin – 7am- 9am\"]").click();
  await page.locator("//H3[normalize-space() = \"Appointment Block\"]/ancestor::div[@class=\"modal-header\"]//button[@data-toggle=\"dropdown\"]").click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.getByRole('link', { name: "Delete Block" }).click();
  await page.getByRole('heading', { name: "Delete Appointment Block" }).click();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this appointment block?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Yes, delete it" }).click();
  await page.waitForLoadState('load');
});
