// TC: TC_A83655
// Mentorships - Admin Assigned Matching Only

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Mentorships - Admin Assigned Matching Only", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.locator("//*[normalize-space() = \"Site Management\"]//button[contains(@data-toggle,\"collapse\")]").click();
  await page.getByRole('link', { name: "Site Settings" }).click();
  await page.getByRole('link', { name: "Mentorships" }).click();
  await expect(page.getByRole('heading', { name: "Mentorship" })).toHaveText("Mentorship");
  await expect(page.getByRole('link', { name: "Admin-Assigned Matching Only" })).toContainText("Admin-Assigned Matching Only");
  await page.locator("//DIV[normalize-space() = \"Edit Inactivate\"]").nth(6).hover();
  await page.locator("//a[normalize-space()=\"Admin-Assigned Matching Only\"]/following::tt-action-dropdown").click();
  await page.getByRole('link', { name: "Edit" }).click();
  await expect(page.getByRole('heading', { name: "Edit Mentorship Program" })).toHaveText("Edit Mentorship Program");
  await expect(page.locator("//LABEL[@id='undefined-label'][normalize-space() = \"Admin-Assigned Matching Only\"]")).toHaveText("Admin-Assigned Matching Only");
  await page.locator("SPAN[role='tooltip'][title='']").nth(7).hover();
  await expect(page.getByRole('heading', { name: "Mentors" })).toHaveText("Mentors");
  await expect(page.locator("//LABEL[@id='undefined-label'][normalize-space() = \"Student Group\"]")).toHaveText("Student Group");
  await expect(page.getByRole('button', { name: "Current Students" })).toHaveText("Current Students");
  await expect(page.getByRole('heading', { name: "Mentees" })).toHaveText("Mentees");
  await expect(page.locator("//LABEL[@id='undefined-label'][normalize-space() = \"Student Group\"]")).toHaveText("Student Group");
  await expect(page.getByRole('button', { name: "Current Students" })).toHaveText("Current Students");
  await page.getByRole('link', { name: "Cancel" }).click();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByRole('button', { name: "Student Group (empty)" }).click();
  await page.locator("//LABEL[normalize-space() = \"Current Students\"]").click();
  await page.getByRole('link', { name: "Test Student #0001" }).click();
  await page.getByRole('link', { name: "Profile" }).click();
  await expect(page.locator("//dt[normalize-space()=\"Student Group\"]")).toHaveText("Student Group");
  await expect(page.locator("//SPAN[normalize-space() = \"Current Students\"]").nth(1)).toHaveText("Current Students");
  await expect(page.locator("//dt[normalize-space()=\"User Role\"]")).toHaveText("User Role");
  await expect(page.locator("//SPAN[normalize-space() = \"Full Access\"]")).toHaveText("Full Access");
  await expect(page.getByRole('heading', { name: "Mentorships" })).toHaveText("Mentorships");
  await expect(page.locator("//dt[normalize-space()=\"Allow users to request me as a mentor\"]")).toHaveText("Allow users to request me as a mentor");
  await expect(page.locator("//dt[normalize-space()=\"Allow users to request me as a mentor\"]/following::dd[normalize-space()=\"Yes\"]")).toHaveText("Yes");
  await expect(page.locator("//dt[normalize-space()=\"Mentorship Programs\"]")).toHaveText("Mentorship Programs");
  await expect(page.locator("//dt[normalize-space()=\"Mentorship Programs\"]/following::dd[normalize-space()=\"Admin-Assigned Matching Only\"]")).toHaveText("Admin-Assigned Matching Only");
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByRole('link', { name: "Test Student #0002" }).click();
  await page.getByRole('link', { name: "Profile" }).click();
  await expect(page.locator("//dt[normalize-space()=\"Student Group\"]")).toHaveText("Student Group");
  await expect(page.locator("//SPAN[normalize-space() = \"Full Access - Mentee\"]")).toHaveText("Full Access - Mentee");
  await expect(page.locator("//dt[normalize-space()=\"User Role\"]")).toHaveText("User Role");
  await expect(page.locator("//SPAN[normalize-space() = \"Current Students\"]").nth(1)).toHaveText("Current Students");
  await expect(page.getByRole('heading', { name: "Mentorships" })).toHaveText("Mentorships");
  await expect(page.locator("//dt[normalize-space()=\"Allow users to request me as a mentor\"]")).toHaveText("Allow users to request me as a mentor");
  await expect(page.locator("//dt[normalize-space()=\"Allow users to request me as a mentor\"]/following::dd[normalize-space()=\"Yes\"]")).toHaveText("Yes");
  await expect(page.locator("//dt[normalize-space()=\"Mentorship Programs\"]")).toHaveText("Mentorship Programs");
  await expect(page.locator("//dt[normalize-space()=\"Mentorship Programs\"]/following::dd[normalize-space()=\"Admin-Assigned Matching Only\"]")).toHaveText("Admin-Assigned Matching Only");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Login As" }).click();
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('e2e-tests-campuswide.qa-12twenty.com/on-login?returnUrl=%2Fdashboard');
  await page.getByRole('link', { name: "Mentorship" }).click();
  await page.getByRole('link', { name: "Mentorship" }).click();
  await expect(page.locator("//SPAN[normalize-space() = \"The ability to browse and request mentors has been disabled.\"]")).toHaveText("The ability to browse and request mentors has been disabled.");
  await page.getByRole('link', { name: "Browse" }).click();
  await expect(page.locator("//SPAN[normalize-space() = \"The ability to browse and request mentors has been disabled.\"]")).toHaveText("The ability to browse and request mentors has been disabled.");
  await page.getByRole('link', { name: "Manage" }).click();
  await expect(page.getByRole('heading', { name: "Manage Mentorship" })).toHaveText("Manage Mentorship");
  await page.locator("//*[normalize-space() = \"Site Management\"]//button[contains(@data-toggle,\"collapse\")]").click();
  await page.getByRole('link', { name: "Site Settings" }).click();
  await page.getByRole('link', { name: "Mentorships" }).click();
  await expect(page.getByRole('link', { name: "Admin-Assigned Matching Only" })).toHaveText("Admin-Assigned Matching Only");
  await page.locator("//a[normalize-space()=\"Admin-Assigned Matching Only\"]/following::tt-action-dropdown").click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.locator("//LABEL[@id='undefined-label'][normalize-space() = \"Admin-Assigned Matching Only\"]").hover();
  await page.locator("//label[normalize-space()=\"Admin-Assigned Matching Only\"]/following::toggle/div[@class=\"toggle btn btn-xs btn-success\"][@aria-checked=\"true\"]").click();
  await page.waitForLoadState('domcontentloaded');
  await page.getByRole('link', { name: "Save Changes" }).click();
  await expect(page.locator("//DIV[@role='alert'][normalize-space() = \"Mentorship Program saved successfully\"]")).toHaveText("Mentorship Program saved successfully");
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByRole('link', { name: "Test Student #0002" }).click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Login As" }).click();
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('e2e-tests-campuswide.qa-12twenty.com/on-login?returnUrl=%2Fdashboard');
  await page.locator("//*[normalize-space() = \"Mentorship\"]//button[contains(@data-toggle,\"collapse\")]").click();
  await page.getByRole('link', { name: "Mentorship" }).click();
  await expect(page.getByRole('heading', { name: "Mentorship" })).toHaveText("Mentorship");
  await expect(page.getByRole('heading', { name: "Recommended for you, based on your College." })).toHaveText("Recommended for you, based on your College.");
  await page.locator("//DIV[normalize-space() = \"Test Student #0001 Spring 2026\"]").nth(2).hover();
  await page.getByRole('link', { name: "Browse" }).click();
  await page.getByRole('link', { name: "Manage" }).click();
  await page.locator("//*[normalize-space() = \"Site Management\"]//button[contains(@data-toggle,\"collapse\")]").click();
  await page.getByRole('link', { name: "Site Settings" }).click();
  await page.getByRole('link', { name: "Mentorships" }).click();
  await expect(page.getByRole('link', { name: "Admin-Assigned Matching Only" })).toHaveText("Admin-Assigned Matching Only");
  await page.locator("//a[normalize-space()=\"Admin-Assigned Matching Only\"]/following::tt-action-dropdown").click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.locator("//LABEL[@id='undefined-label'][normalize-space() = \"Admin-Assigned Matching Only\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Off\"]").click();
  await page.getByRole('link', { name: "Save Changes" }).click();
  await expect(page.locator("//DIV[@role='alert'][normalize-space() = \"Mentorship Program saved successfully\"]")).toHaveText("Mentorship Program saved successfully");
});
