// TC: TC_A79991
// Students - Student Groups - Create and Merge Student Groups

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Students - Student Groups - Create and Merge Student Groups", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.locator("//a[normalize-space()=\"Site Management\"]/following-sibling::button").click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByRole('link', { name: "Groups" }).click();
  await page.getByRole('link', { name: "Add a new Group" }).click();
  await page.getByPlaceholder("Student Group Name").fill("Muuk Merge Group 1");
  await page.locator("//LABEL[normalize-space() = \"Enable display on site under student name\"]").click();
  await page.getByRole('button', { name: "Add" }).click();
  await page.locator("//SPAN[normalize-space() = \"The student group was created successfully\"]").hover();
  await page.getByRole('link', { name: "Add a new Group" }).click();
  await page.getByPlaceholder("Student Group Name").fill("Muuk Merge Group 2");
  await page.locator("//LABEL[normalize-space() = \"Enable display on site under student name\"]").click();
  await page.getByRole('button', { name: "Add" }).click();
  await page.locator("//SPAN[normalize-space() = \"The student group was created successfully\"]").hover();
  await page.locator("//TD[normalize-space()=\"Muuk Merge Group 2\"]").hover();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  selector = MK.onSetGV(`//BUTTON[@type=\'button\'][normalize-space() = "Reset Filters"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.getByRole('button', { name: "Reset Filters" }).click();
  }
  await page.getByRole('button', { name: "More Filters" }).click();
  await page.getByPlaceholder("Search filters").fill("12twenty ");
  await page.getByRole('button', { name: "12twenty ID" }).click();
  await page.getByPlaceholder("12twenty ID").fill("540016054866989");
  await page.getByRole('link', { name: "Cydney Moore" }).click();
  await page.waitForTimeout(2000);
  await page.getByRole('link', { name: "Profile" }).click();
  await page.getByRole('button', { name: "Edit" }).click();
  await page.locator("//LABEL[contains(normalize-space(),\"Student Group*\")]").hover();
  await page.getByRole('button', { name: "Bulk Update 1, Bulk Update 3" }).click();
  await page.locator("//LABEL[normalize-space() = \"Muuk Merge Group 1\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Student Group*\")]").click();
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("span.sub-header>span.ng-binding")).toContainText("Muuk Merge Group 1");
  await page.locator("//a[normalize-space()=\"Site Management\"]/following-sibling::button").click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByRole('link', { name: "Groups" }).click();
  await page.getByRole('heading', { name: "Students - Student Groups - Create and Merge Student Groups" }).click();
  await page.getByRole('link', { name: "Merge Group" }).click();
  await page.locator("//LABEL[normalize-space() = \"Merge Into*\"]").hover();
  await page.getByRole('heading', { name: "Merge Student Group" }).hover();
  await page.locator("SELECT[name='selectedStudentGroupId']").click();
  await page.keyboard.press("Home");
  await page.keyboard.press("ArrowDown");
  await page.keyboard.press("ArrowDown");
  await page.keyboard.press("ArrowDown");
  await page.keyboard.press("ArrowDown");
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Merge" }).click();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByRole('link', { name: "Cydney Moore" }).click();
  await page.waitForTimeout(3000);
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "View Audit Log" }).click();
  await page.locator("button.btn.btn-icon.ng-scope>i.far.fa-plus-square").click();
  await page.locator("//SPAN[normalize-space() = \"×\"]").click();
  await page.locator("div.side-nav-with-link-and-submenu-container>button.btn.btn-icon.sub-menu-icon").nth(7).click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByRole('link', { name: "Groups" }).click();
  await page.locator("//TD[normalize-space()=\"Muuk Merge Group 2\"]/ancestor::tr//button").click();
  await page.getByRole('link', { name: "Delete Group" }).click();
  await page.getByRole('heading', { name: "Delete Student Group" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this student group?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Delete Student Group" }).click();
  await page.getByRole('heading', { name: "Oops!" }).hover();
  await page.locator("//DIV[normalize-space() = \"This student group cannot be deleted because it is associated with 1 student(s). Please un-assign this student group from student accounts. To identify these students, add the \\'Student Group\\' filter on the Student Directory. You may also use the bulk update tool to move these students to a different student group.\"]").hover();
  await page.getByRole('link', { name: "OK" }).click();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByRole('link', { name: "Cydney Moore" }).click();
  await page.getByRole('link', { name: "Profile" }).click();
  await page.getByRole('button', { name: "Edit" }).click();
  await page.locator("//LABEL[contains(normalize-space(),\"Student Group*\")]").hover();
  await page.getByRole('button', { name: "Bulk Update 1, Bulk Update 3, Muuk Merge Group 2" }).click();
  await page.locator("//LABEL[normalize-space() = \"Muuk Merge Group 2\"]").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("span.sub-header>span.ng-binding")).toContainText("Muuk Merge Group 2");
  await page.locator("//a[normalize-space()=\"Site Management\"]/following-sibling::button").click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByRole('link', { name: "Groups" }).click();
  await page.locator("//TD[normalize-space()=\"Muuk Merge Group 2\"]").hover();
  await page.locator("//TD[normalize-space()=\"Muuk Merge Group 2\"]/ancestor::tr//button").click();
  await page.getByRole('link', { name: "Delete Group" }).click();
  await page.getByRole('heading', { name: "Delete Student Group" }).hover();
  await page.getByRole('button', { name: "Delete Student Group" }).click();
  await page.locator("//SPAN[normalize-space() = \"The student group was deleted successfully\"]").hover();
});
