// TC: TC_A81896
// PAUSED - LinkedIn - Import LinkedIn Profile on login and student profile

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("PAUSED - LinkedIn - Import LinkedIn Profile on login and student profile", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.locator("//a[normalize-space()=\"Site Management\"]//following-sibling::button").click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByRole('button', { name: "Add New Student" }).click();
  await page.getByRole('heading', { name: "Student Account Information" }).hover();
  await page.locator("//LABEL[normalize-space() = \"First (Preferred) Name\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Last Name*\"]").hover();
  await page.getByPlaceholder("First (Preferred) Name").fill("LinkedIn");
  await page.locator("//LABEL[normalize-space() = \"Email Address*\"]").hover();
  await page.getByPlaceholder("Last Name").fill("Test #1");
  await page.getByPlaceholder("Email Address").fill("test1@test.com");
  await page.locator("SELECT[name='RoleId']").selectOption("number:3");
  await page.locator("div.form-group.ng-scope.ng-dirty.ng-valid.ng-valid-required>label.control-label.ng-binding").nth(5).hover();
  await page.getByRole('heading', { name: "68 Steps" }).click();
  await page.locator("//LABEL[normalize-space() = \"Group 1\"]").click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.form-group.ng-scope.ng-dirty.ng-valid.ng-valid-required>label.control-label.ng-binding").nth(5).click();
  await page.locator("SELECT[name='ProgramId']").selectOption("number:1814999953610478");
  await page.locator("SELECT[name='College1Name']").selectOption("number:149999071101701");
  await page.locator("//LABEL[normalize-space() = \"Degree Level*\"]").hover();
  await page.locator("SELECT[name='DegreeLevelId']").selectOption("number:149999071102056");
  await page.locator("//LABEL[normalize-space() = \"Graduation Term*\"]").hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.getByPlaceholder("Search").fill("2028");
  await page.locator("//LABEL[normalize-space() = \"Summer 2028\"]").click();
  await page.locator("div.form-group.ng-pristine.ng-scope.ng-invalid.ng-invalid-required>label.control-label.ng-binding").click();
  await page.locator("SELECT[name='IsEnrolled']").selectOption("number:1");
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Save Changes" }).click();
  await page.locator("//SPAN[normalize-space() = \"Student saved successfully\"]").hover();
  await page.getByRole('button', { name: "Add New Student" }).click();
  await page.locator("//LABEL[normalize-space() = \"Last Name*\"]").hover();
  await page.getByPlaceholder("First (Preferred) Name").fill("LinkedIn");
  await page.locator("//LABEL[normalize-space() = \"Email Address*\"]").hover();
  await page.getByPlaceholder("Last Name").fill("Test #2");
  await page.locator("div.form-group.ng-pristine.ng-scope.ng-invalid.ng-invalid-required>label.control-label.ng-binding").hover();
  await page.locator("SELECT[name='IsEnrolled']").selectOption("number:1");
  await page.getByPlaceholder("Email Address").fill("test2@test.com");
  await page.locator("div.form-group.ng-pristine.ng-scope.ng-invalid.ng-invalid-required>label.control-label.ng-binding").hover();
  await page.locator("SELECT[name='RoleId']").selectOption("number:3");
  await page.locator("div.form-group.ng-scope.ng-dirty.ng-valid.ng-valid-required>label.control-label.ng-binding").nth(5).hover();
  await page.getByRole('heading', { name: "68 Steps" }).click();
  await page.locator("//LABEL[normalize-space() = \"Group 1\"]").click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.form-group.ng-scope.ng-dirty.ng-valid.ng-valid-required>label.control-label.ng-binding").nth(5).click();
  await page.locator("//LABEL[normalize-space() = \"Program*\"]").hover();
  await page.locator("SELECT[name='ProgramId']").selectOption("number:1814999953610478");
  await page.locator("//LABEL[normalize-space() = \"College/School*\"]").hover();
  await page.locator("SELECT[name='College1Name']").selectOption("number:149999071101701");
  await page.locator("//LABEL[normalize-space() = \"Degree Level*\"]").hover();
  await page.locator("SELECT[name='DegreeLevelId']").selectOption("number:149999071102056");
  await page.locator("//LABEL[normalize-space() = \"Graduation Term*\"]").hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.getByPlaceholder("Search").fill("2029");
  await page.locator("//LABEL[normalize-space() = \"Spring 2029\"]").click();
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Save Changes" }).click();
  await page.locator("//SPAN[normalize-space() = \"Student saved successfully\"]").hover();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("LinkedIn Test");
  await page.locator("BUTTON[aria-label=\"Search\"]").click();
  await page.getByRole('link', { name: "LinkedIn Test #1" }).hover();
  await page.getByRole('link', { name: "LinkedIn Test #2" }).hover();
  await page.locator("//A[normalize-space() = \"LinkedIn Test #1\"]/ancestor::tr//button").click();
  await page.getByRole('link', { name: "Login as user..." }).click();
  await page.getByRole('heading', { name: "Login as LinkedIn Test #1" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
});
