// TC: TC_A82640
// Outcomes - Settings - Admin can enable v2 and students can submit outcomes

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Outcomes - Settings - Admin can enable v2 and students can submit outcomes", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.locator("//*[normalize-space() = \"Site Management\"]//button[contains(@data-toggle,\"collapse\")]").click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("Outcome Muuk");
  await page.waitForLoadState('Enter');
  await page.waitForTimeout(1000);
  selector = MK.onSetGV(`//a[normalize-space()="Outcome Muuk"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.locator("//a[normalize-space()=\"Outcome Muuk\"]/ancestor::tr//button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Confirm Delete" }).hover();
  await page.locator("//LABEL[normalize-space() = \"I understand that deleting a student user will delete the user and all data associated with their account. This action can not be undone.\"]").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByRole('button', { name: "OK" }).click();
  }
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("Outcome Muuk");
  await page.locator("//SPAN[normalize-space() = \"Site Settings\"]").click();
  await page.getByRole('link', { name: "Outcome Survey" }).click();
  await page.waitForLoadState('load');
  selector = MK.onSetGV(`//SPAN[normalize-space() = "Spring 2025, Fall 2024, Summer 2024, Spring 2024, Fall 2023, Summer 2023"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.locator("//SPAN[normalize-space() = \"Spring 2025, Fall 2024, Summer 2024, Spring 2024, Fall 2023, Summer 2023\"]//ancestor::div[contains(@class,\"tt-card\")]//button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to delete this outcome survey setting?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  }
  selector = MK.onSetGV(`//SPAN[normalize-space() = "Summer 2023"]`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.locator("//SPAN[normalize-space() = \"Summer 2023\"]//ancestor::div[contains(@class,\"tt-card\")]//button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to delete this outcome survey setting?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  }
  await page.locator("//SPAN[normalize-space() = \"Site Settings\"]").click();
  await page.getByRole('link', { name: "Outcome Survey" }).click();
  await page.getByRole('link', { name: "General" }).click();
  await page.locator("//LABEL[normalize-space() = \"Off\"]").nth(1).click();
  await page.getByRole('button', { name: "Save Changes" }).click();
  await page.getByRole('button', { name: "New" }).click();
  await page.getByRole('heading', { name: "Create Setting" }).hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.getByPlaceholder("Search").fill("2025");
  await page.locator("//LABEL[normalize-space() = \"2025\"]").click();
  await page.getByPlaceholder("Search").fill("2024");
  await page.locator("//LABEL[normalize-space() = \"2024\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Graduation Terms\"]").click();
  textContent = MK.onSetGV(`Thanks for completing the survey!`, null);
  await page.getByRole('heading', { name: "Post Graduation" }).click();
  await page.locator("//div[normalize-space()=\"Post Graduation\"]//ancestor::section//LABEL[normalize-space() = \"Survey available to students/alumni\"]").hover();
  await page.getByRole('heading', { name: "20 Steps" }).click();
  await page.getByRole('heading', { name: "37 Steps" }).click();
  await page.locator("//div[normalize-space()=\"Post Graduation\"]//ancestor::section//LABEL[normalize-space() = \"Require Response\"]/following-sibling::div//div[contains(@class,\"off\")]").click();
  await page.locator("//div[normalize-space()=\"Post Graduation\"]//ancestor::section//LABEL[normalize-space() = \"Survey available to admins\"]").hover();
  await page.locator("//div[normalize-space()=\"Post Graduation\"]//ancestor::section//LABEL[normalize-space() = \"Survey available to admins\"]/following-sibling::div//div[contains(@class,\"off\")]").click();
  await page.locator("//div[normalize-space()=\"Post Graduation\"]//ancestor::section//LABEL[normalize-space() = \"Post Survey Notification\"]").hover();
  await page.locator("//div[normalize-space()=\"Post Graduation\"]//ancestor::section//div[@aria-labelledby=\"cke_postSubmissionConfirmationText_arialbl\"]").click();
  await page.getByRole('heading', { name: "Internship" }).click();
  await page.locator("//div[normalize-space()=\"Internship\"]//ancestor::section//LABEL[normalize-space() = \"Survey available to students/alumni\"]").hover();
  await page.locator("//div[normalize-space()=\"Internship\"]//ancestor::section//LABEL[normalize-space() = \"Survey available to students/alumni\"]/following-sibling::div//div[contains(@class,\"off\")]").click();
  await page.locator("//div[normalize-space()=\"Internship\"]//ancestor::section//LABEL[normalize-space() = \"Survey on Login\"]/following-sibling::div//div[contains(@class,\"off\")]").click();
  await page.getByRole('heading', { name: "Prerequisites" }).click();
  await page.locator("//div[normalize-space()=\"Internship\"]//ancestor::section//LABEL[normalize-space() = \"Survey available to admins\"]").hover();
  await page.getByRole('heading', { name: "Create a folder project." }).click();
  await page.locator("//div[normalize-space()=\"Internship\"]//ancestor::section//div[@aria-labelledby=\"cke_postSubmissionConfirmationText_arialbl\"]").click();
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("//dt[normalize-space()=\"Graduation Terms\"]/following-sibling::dd//span")).toHaveText("Spring 2025, Fall 2024, Summer 2024, Spring 2024, Fall 2023, Summer 2023");
  await page.getByRole('button', { name: "New" }).click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.getByPlaceholder("Search").fill("Summer 2023");
  await page.locator("//LABEL[normalize-space() = \"Summer 2023\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Graduation Terms\"]").click();
  textContent = MK.onSetGV(`Thanks for completing the survey! (Most Specific Winner!)`, null);
  await page.getByRole('heading', { name: "Post Graduation" }).click();
  await page.locator("//div[normalize-space()=\"Post Graduation\"]//ancestor::section//LABEL[normalize-space() = \"Survey available to students/alumni\"]").hover();
  await page.getByRole('heading', { name: "20 Steps" }).click();
  await page.getByRole('heading', { name: "37 Steps" }).click();
  await page.locator("//div[normalize-space()=\"Post Graduation\"]//ancestor::section//LABEL[normalize-space() = \"Require Response\"]/following-sibling::div//div[contains(@class,\"off\")]").click();
  await page.locator("//div[normalize-space()=\"Post Graduation\"]//ancestor::section//LABEL[normalize-space() = \"Survey available to admins\"]").hover();
  await page.locator("//div[normalize-space()=\"Post Graduation\"]//ancestor::section//LABEL[normalize-space() = \"Survey available to admins\"]/following-sibling::div//div[contains(@class,\"off\")]").click();
  await page.locator("//div[normalize-space()=\"Post Graduation\"]//ancestor::section//LABEL[normalize-space() = \"Post Survey Notification\"]").hover();
  await page.locator("//div[normalize-space()=\"Post Graduation\"]//ancestor::section//div[@aria-labelledby=\"cke_postSubmissionConfirmationText_arialbl\"]").click();
  await page.getByRole('heading', { name: "Internship" }).click();
  await page.locator("//div[normalize-space()=\"Internship\"]//ancestor::section//LABEL[normalize-space() = \"Survey available to students/alumni\"]").hover();
  await page.locator("//div[normalize-space()=\"Internship\"]//ancestor::section//LABEL[normalize-space() = \"Survey available to students/alumni\"]/following-sibling::div//div[contains(@class,\"off\")]").click();
  await page.locator("//div[normalize-space()=\"Internship\"]//ancestor::section//LABEL[normalize-space() = \"Survey on Login\"]/following-sibling::div//div[contains(@class,\"off\")]").click();
  await page.getByRole('heading', { name: "Prerequisites" }).click();
  await page.locator("//div[normalize-space()=\"Internship\"]//ancestor::section//LABEL[normalize-space() = \"Survey available to admins\"]").hover();
  await page.getByRole('heading', { name: "Create a folder project." }).click();
  await page.locator("//div[normalize-space()=\"Internship\"]//ancestor::section//div[@aria-labelledby=\"cke_postSubmissionConfirmationText_arialbl\"]").click();
  await page.getByRole('heading', { name: "Work Experience" }).click();
  await page.locator("//div[normalize-space()=\"Work Experience\"]//ancestor::section//LABEL[normalize-space() = \"Survey available to students/alumni\"]").hover();
  await page.getByRole('link', { name: "Integrating MuukTest with CircleCi - Guidelines" }).click();
  await page.getByRole('link', { name: "MuukTest + Playwright Tutorial" }).click();
  await page.getByRole('link', { name: "MuukTest Playwright Executor (CLI)" }).click();
  await page.locator("//div[normalize-space()=\"Work Experience\"]//ancestor::section//LABEL[normalize-space() = \"Survey available to admins\"]").hover();
  await page.getByRole('link', { name: "MuukTest Tutorial - CLI (Executor)" }).click();
  await page.locator("//div[normalize-space()=\"Work Experience\"]//ancestor::section//LABEL[normalize-space() = \"Post Survey Notification\"]").hover();
  await page.locator("//div[normalize-space()=\"Work Experience\"]//ancestor::section//div[@aria-labelledby=\"cke_postSubmissionConfirmationText_arialbl\"]").click();
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("(//H3[normalize-space() = \"Setting\"])[2]/following::dt[normalize-space()=\"Graduation Terms\"]//following-sibling::dd//span")).toHaveText("Summer 2023");
  await page.getByRole('link', { name: "Manage Users" }).click();
  studentFirstName = MK.onSetGV(`Outcome`, null);
  studentLastName = MK.onSetGV(`Muuk`, null);
  await page.getByRole('button', { name: "Add New Student" }).click();
  await page.getByPlaceholder("First (Preferred) Name").fill("` + studentFirstName + `");
  await page.getByPlaceholder("Last Name").fill("` + studentLastName + `");
  textContent = MK.onSetGV(` random text`, 5);
  await page.getByPlaceholder("Email Address").fill("studentmuuk+` + textContent + `@muukteam.testinator.com");
  await page.locator("//LABEL[normalize-space() = \"Program*\"]").click();
  await page.locator("SELECT[name='ProgramId']").selectOption("number:1814999953610478");
  await page.locator("//LABEL[normalize-space() = \"College/School*\"]").click();
  await page.locator("SELECT[name='College1Name']").selectOption("number:149999071101701");
  await page.locator("//LABEL[normalize-space() = \"Degree Level*\"]").click();
  await page.locator("SELECT[name='DegreeLevelId']").selectOption("number:149999071102056");
  await page.locator("//LABEL[normalize-space() = \"Major/Academic Program\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Graduation Term*\"]").click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.getByPlaceholder("Search").fill("Summer 2023");
  await page.locator("//LABEL[normalize-space() = \"Summer 2023\"]").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Student Id\")]").click();
  await page.getByPlaceholder("Student Id").fill("` + textContent + `");
  await page.locator("//LABEL[contains(normalize-space(),\"Active*\")]").click();
  await page.locator("SELECT[name='IsEnrolled']").selectOption("number:1");
  await page.locator("//LABEL[contains(normalize-space(),\"User Role*\")]").click();
  await page.locator("SELECT[name='RoleId']").selectOption("number:3");
  await page.locator("//LABEL[contains(normalize-space(),\"Student Group*\")]").click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.waitForLoadState('load');
  await page.locator("//SPAN[normalize-space() = \"Site Settings\"]").click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("Outcome Muuk");
  await page.getByRole('link', { name: "Home" }).click();
  await page.getByRole('heading', { name: "Professional Experience" }).click();
  await page.getByRole('heading', { name: "Work Experience" }).hover();
  await page.getByRole('link', { name: "Add Experience or Status" }).hover();
  await page.getByRole('link', { name: "Add Rumor" }).hover();
  await page.getByRole('heading', { name: "Post Graduation" }).hover();
  await page.getByRole('link', { name: "Add Experience or Status" }).hover();
  await page.getByRole('link', { name: "Add Rumor" }).hover();
  await page.getByRole('heading', { name: "Internship" }).hover();
  await page.getByRole('link', { name: "Add Experience or Status" }).hover();
  await page.getByRole('link', { name: "Add Rumor" }).hover();
  await page.getByRole('heading', { name: "Experiential Learning" }).hover();
  await page.getByRole('link', { name: "Add Experience or Status" }).hover();
  await page.locator("BUTTON[type='button']").nth(3).click();
  await page.getByRole('link', { name: "Login As" }).click();
  await page.waitForTimeout(3000);
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.getByRole('heading', { name: "Hi Outcome!" }).click();
  await page.locator("//P[normalize-space() = \"Work Experience\"]").hover();
  await page.locator("//P[normalize-space() = \"Please tell us about your experience\"]").hover();
  await page.getByRole('button', { name: "Working Full or Part-Time" }).hover();
  await page.getByRole('button', { name: "Contract/Consulting Work" }).hover();
  await page.getByRole('button', { name: "Self-Employed/Own Business" }).hover();
  await page.getByRole('button', { name: "Seeking Employment" }).hover();
  await page.getByRole('button', { name: "Retired" }).hover();
  await page.getByRole('button', { name: "Continuing My Education" }).hover();
  await page.getByRole('button', { name: "Voluntary Break from Employment" }).hover();
  await page.getByRole('button', { name: "Other Experience" }).hover();
  await page.getByRole('button', { name: "Continuing My Education" }).click();
  await page.locator("SELECT[id='Fields_ContinuingEducationDegreeLevelId'][name='Fields.ContinuingEducationDegreeLevelId']").click();
  await page.keyboard.press("Associates");
  await page.locator("INPUT[id='Fields_DegreeEarning'][name='Fields.DegreeEarning'][type='text']").fill("60000");
  await page.getByPlaceholder("University").fill("University of California--Davis");
  await page.keyboard.press("ArrowDown");
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(29).click();
  await page.locator("//LABEL[normalize-space() = \"Full-time\"]").click();
  await page.locator("//label[normalize-space() = \"Satisfaction\"]").hover();
  await page.locator("//label[contains(normalize-space(),\"Star Rating Attribute - Required\")]").hover();
  await page.locator("td.ant-table-cell.drag-visible.column-center.ant-table-cell-row-hover>div.ant-row.css-eqeg24").click();
  await page.locator("INPUT[type='button'][id='btnSubmit'][name='btnSubmit']").click();
  await page.getByRole('heading', { name: "Thank You!" }).hover();
  await page.locator("//P[contains(normalize-space(),\"Thanks for completing the survey!\")]").hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByRole('heading', { name: "Work Experience" }).click();
  await page.getByRole('link', { name: "Continuing My Education" }).hover();
  await page.locator("//DIV[contains(normalize-space(),\"University of California--Davis\")]").hover();
  await page.locator("//DIV[normalize-space() = \"Associates\"]").hover();
  await page.locator("//B[normalize-space() = \"log out\"]").click();
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('e2e-tests-campuswide.admin.qa-12twenty.com/');
  await page.locator("//*[normalize-space() = \"Site Management\"]//button[contains(@data-toggle,\"collapse\")]").click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.locator("//a[normalize-space()=\"Outcome Muuk\"]/ancestor::tr//button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Confirm Delete" }).hover();
  await page.locator("//LABEL[normalize-space() = \"I understand that deleting a student user will delete the user and all data associated with their account. This action can not be undone.\"]").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("Outcome Muuk");
  await page.locator("//SPAN[normalize-space() = \"Site Settings\"]").click();
  await page.getByRole('link', { name: "Outcome Survey" }).click();
  await page.locator("//SPAN[normalize-space() = \"Spring 2025, Fall 2024, Summer 2024, Spring 2024, Fall 2023, Summer 2023\"]//ancestor::div[contains(@class,\"tt-card\")]//button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to delete this outcome survey setting?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.locator("//SPAN[normalize-space() = \"Summer 2023\"]//ancestor::div[contains(@class,\"tt-card\")]//button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to delete this outcome survey setting?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
});
