// TC: TC62792
// 12TE - Post a Job - Employer

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("12TE - Post a Job - Employer", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto('https://employer.qa-12twenty.com/', { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Email Address").fill("e2e.employeruser.subscription.admin@walmart.com");
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.waitForTimeout(2000);
  await page.locator("button.btn.btn-school.submit-login-form>span").click();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").hover();
  await page.waitForLoadState('load');
  await page.waitForTimeout(2000);
  await page.getByRole('link', { name: "Jobs" }).click();
  await page.getByRole('link', { name: "Job Postings" }).hover();
  await page.getByRole('link', { name: "Analytics" }).hover();
  await page.getByRole('heading', { name: "Job Postings" }).hover();
  await page.getByRole('link', { name: "Post a Job" }).click();
  await page.locator("DIV[role='dialog']").hover();
  await page.getByRole('heading', { name: "Business" }).click();
  await page.locator("//P[normalize-space() = \"MBA, EMBA & PTMBA\"]").hover();
  await page.getByRole('heading', { name: "Please select one or more program types..." }).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Continue" }).click();
  await page.locator("//DIV[normalize-space() = \"1 School Selection\"]").hover();
  await page.locator("//DIV[normalize-space() = \"2 Job Details\"]").hover();
  await page.locator("//DIV[normalize-space() = \"3 Extras\"]").hover();
  await page.locator("//DIV[normalize-space() = \"4 Review & Submit\"]").hover();
  await page.locator("div.school-info>div.school-name.ng-binding").nth(22).click();
  await page.getByRole('heading', { name: "Selected Schools" }).hover();
  await page.locator("//DIV[normalize-space() = \"Items: 1\"]").hover();
  await page.locator("li.order-item.ng-scope>div.order-name.ng-binding").hover();
  await page.locator("ul>li.school-card.ng-scope").nth(41).click();
  await page.locator("li.order-item.ng-scope>div.order-name.ng-binding").nth(1).hover();
  await page.getByRole('heading', { name: "Selected Schools" }).hover();
  await page.locator("//DIV[normalize-space() = \"Items: 2\"]").hover();
  await page.waitForTimeout(2000);
  await page.locator("span>policy.ng-scope").click();
  await page.getByRole('button', { name: "Continue" }).click();
  await page.locator("//DIV[normalize-space() = \"2 Job Details\"]").hover();
  await page.getByPlaceholder("Job Title").fill("Business job posting");
  await page.locator("SELECT[name='CoreJobTypeId']").selectOption("number:1");
  await page.getByRole('button', { name: "-- Please Select Industries --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Functions *\"]").click();
  await page.getByRole('button', { name: "-- Please Select Functions --" }).click();
  await page.getByPlaceholder("Search").fill("informat");
  await page.locator("//LABEL[normalize-space() = \"Cybersecurity & Information Security\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Location Type *\"]").click();
  await page.locator("SELECT[name='LocationTypeId']").selectOption("number:3");
  await page.locator("//LABEL[normalize-space() = \"Candidate Population*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Students & Alumni\"]").click();
  await page.getByRole('button', { name: "-- Please Select a Work Authorization --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Description *\"]").click();
  await page.locator("SPAN[id='cke_1_top'][role='presentation']").click();
  await page.locator("div>label").nth(46).click();
  await page.getByPlaceholder("Url").fill("test@gmail.com");
  await page.getByPlaceholder("External ID").fill("12345");
  await page.waitForTimeout(1000);
  await page.locator("//LABEL[normalize-space() = \"I will wait until the end of the application period to review all of the applicants\"]").click();
  await page.locator('input[type="radio"]').click();
  await page.getByRole('link', { name: "Continue" }).click();
  await page.waitForTimeout(5000);
  await page.getByRole('link', { name: "Continue" }).click();
  await page.getByRole('button', { name: "Submit Free Order" }).click();
  await page.getByRole('heading', { name: "Thank You!" }).hover();
  await page.locator("div.ng-scope>div.sub-header").hover();
  await page.locator("//P[normalize-space() = \"This order has been moved to the Order History page. An email has also been sent to you confirming that your order has been paid.\"]").hover();
  await page.getByRole('heading', { name: "Order Details" }).hover();
  await page.getByRole('link', { name: "Jobs" }).click();
  await page.getByRole('link', { name: "Business job posting" }).click();
  await page.waitForTimeout(2000);
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('heading', { name: "Business job posting" }).hover();
  await page.locator("div.header-main>div.sub-header.primary-sub-header.ng-binding").hover();
  await page.locator("div.sub-header.badges>span.badge.application-open").hover();
  await page.locator("dl.dl-horizontal>dd.ng-binding").nth(1).hover();
  await page.locator("dl.dl-horizontal>dd.ng-binding.ng-scope").hover();
  await page.locator("div.rich-text-display.ng-binding>p").hover();
  await page.getByRole('link', { name: "Applicants (0)" }).click();
  await page.getByRole('link', { name: "Schools (2)" }).click();
  await page.locator("tr.ng-scope>td.school.ng-binding").hover();
  await page.locator("//SPAN[normalize-space(translate(., '\\u00A0', ' ')) = \"Delivered\"]").hover();
  await page.locator("tr.ng-scope>td.school.ng-binding").nth(1).hover();
  await page.locator("//SPAN[normalize-space(translate(., '\\u00A0', ' ')) = \"Delivered\"]").hover();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Edit" }).hover();
  await page.getByRole('link', { name: "Duplicate" }).hover();
  await page.getByRole('link', { name: "Deactivate" }).hover();
  await page.getByRole('link', { name: "Deactivate" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.locator("div.sub-header.badges>span.badge.inactive").hover();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.reload();
  await page.waitForLoadState('load');
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Job Title").fill("Business job posting");
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByRole('button', { name: "Get Results" }).click();
  await page.waitForLoadState('load');
  await page.locator("div.results-header-right>div.num-results.ng-binding.ng-scope").hover();
  await page.getByRole('link', { name: "Business job posting" }).hover();
  await page.locator("td>span.badge.inactive").hover();
});
