// TC: TC60125
// Outcomes - Add Report Status as Accepted Job - Student

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Outcomes - Add Report Status as Accepted Job - Student", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;
  const text = msg.text();
  const timestamp = new Date().toLocaleString();

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideStudentURL, { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.student.fullaccess@campuswide.com");
  await page.getByPlaceholder("Password").fill("BoH5dORH7xg%");
  await page.getByRole('button', { name: "Student/Alumni Log In" }).click();
  await page.waitForTimeout(1000);
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('heading', { name: "Post Graduation" }).hover();
  await page.locator("div.add-job-in-phase>span.add-job-in-phase-blurb").hover();
  await page.getByRole('button', { name: "Report Status" }).click();
  await page.getByRole('button', { name: "Accepted Job" }).click();
  await page.getByPlaceholder("Employer").fill("Amazon.com");
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: "Amazon.com" }).click();
  await page.getByPlaceholder("Job Title").fill("Manager");
  await page.locator("SELECT[id='Job.NumberOfEmployeesId'][name='Job.NumberOfEmployeesId']").selectOption("3");
  await page.locator("SELECT[name='Job.JobIndustryId']").selectOption("149999414151628");
  await page.locator("SELECT[name='Job.JobFunctionId']").selectOption("100001010430462");
  await page.getByPlaceholder("Country").fill("United States (USA)");
  await page.getByRole('link', { name: "United States (USA)" }).click();
  await page.getByPlaceholder("City").fill("New York - NY");
  await page.getByRole('link', { name: "New York - NY" }).click();
  await page.locator("INPUT[id='Job_Address1']").fill("123 Main Street");
  await page.locator("INPUT[id='Job_Address2']").fill("Suite 400");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Offer Received Date\"]").hover();
  await page.locator("INPUT[id='Job_PostalCode']").fill("10001");
  await page.getByPlaceholder("MM/DD/YYYY").fill("01/01/2024");
  await page.getByPlaceholder("MM/DD/YYYY").fill("01/15/2024");
  await page.getByPlaceholder("MM/DD/YYYY").fill("02/01/2024");
  await page.locator("//LABEL[normalize-space() = \"Compensation Currency Receiving\"]").click();
  await page.getByRole('heading', { name: "Primary Compensation" }).click();
  await page.locator("INPUT[type='text'][id='Job.Salary.BaseSalary'][name='Job.Salary.BaseSalary']").fill("80000");
  await page.locator("INPUT[type='text'][id='Job.Salary.ExpectedCommission'][name='Job.Salary.ExpectedCommission']").fill("5000");
  await page.locator("INPUT[type='text'][id='Job.Salary.ExpectedBonus'][name='Job.Salary.ExpectedBonus']").fill("10000");
  await page.locator("INPUT[type='text'][id='Job.Salary.GuaranteedBonus'][name='Job.Salary.GuaranteedBonus']").fill("8000");
  await page.locator("INPUT[type='text'][id='Job.Salary.OtherCompensation'][name='Job.Salary.OtherCompensation']").fill("10000");
  await page.locator("INPUT[type='text'][id='Job.Salary.CarriedInterestAmount'][name='Job.Salary.CarriedInterestAmount'][title='Interest Amount']").fill("5000");
  await page.locator("INPUT[type='text'][id='Job.Salary.SigningBonus'][name='Job.Salary.SigningBonus']").fill("2000");
  await page.locator("INPUT[type='text'][id='Job.Salary.RelocationBonus'][name='Job.Salary.RelocationBonus']").fill("1500");
  await page.locator("INPUT[type='text'][id='Job.Salary.TuitionReimbursementAmount'][name='Job.Salary.TuitionReimbursementAmount']").fill("1200");
  await page.locator("div>label.control-label.otherRadio").hover();
  await page.locator("INPUT[type='text'][id='Job.Salary.StockAmount'][name='Job.Salary.StockAmount']").fill("20000");
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").click();
  await page.locator("div>label.control-label.otherRadio").nth(1).hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(1).click();
  await page.locator("div>label.control-label.otherRadio").nth(2).hover();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(2).click();
  await page.locator("SELECT[name='Job.CustomJobSourceId'][id='Job.CustomJobSourceId']").selectOption("100011010338755");
  await page.locator("div.FullTimeJob.Internship.inputRow.clearfix>label.control-label.otherRadio").hover();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(3).click();
  await page.locator("div.FullTimeJob.inputRow.clearfix>label.control-label.otherRadio").nth(1).hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(4).click();
  await page.locator("div.FullTimeJob.inputRow.clearfix>label.control-label.otherRadio").nth(2).hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(5).click();
  await page.locator("div.FullTimeJob.inputRow.clearfix>label.control-label.otherRadio").nth(3).hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(6).click();
  await page.locator("div.FullTimeJob.inputRow.clearfix>label.control-label.otherRadio").nth(5).hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(8).click();
  await page.locator("div.FullTimeJob.inputRow.clearfix>label.control-label.otherRadio").nth(6).hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(9).click();
  await page.locator("div.FullTimeJob.inputRow.clearfix>label.control-label.otherRadio").nth(7).hover();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(10).click();
  await page.locator("div.inputRow>label.control-label").nth(33).hover();
  await page.locator("SELECT[id='Job_FundingRaisedId']").selectOption("2");
  await page.locator("//label[normalize-space() = \"Satisfaction\"]").hover();
  await page.locator("//label[contains(normalize-space(),\"Star Rating Attribute - Required\")]").hover();
  await page.locator("td.ant-table-cell.drag-visible.column-center.ant-table-cell-row-hover>div.ant-row.css-eqeg24").click();
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Submit" }).click();
  await page.getByRole('heading', { name: "Did you negotiate any elements of your compensation?" }).hover();
  await page.locator("LABEL[id='salaryRowLabel']").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(11).click();
  await page.locator("LABEL[id='expectedBonusRowLabel']").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(12).click();
  await page.locator("LABEL[id='negotiatedGuaranteedBonusRowLabel']").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(13).click();
  await page.locator("LABEL[id='otherGuaranteedCompensationRowLabel']").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(14).click();
  await page.locator("LABEL[id='carriedInterestRowLabel']").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(15).click();
  await page.locator("LABEL[id='signingBonusRowLabel']").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(16).click();
  await page.waitForTimeout(20000);
  await page.locator("LABEL[id='relocationBonusRowLabel']").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(17).click();
  await page.locator("LABEL[id='tuitionReimbursementAmountRowLabel']").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(18).click();
  await page.locator("LABEL[id='stockAmountRowLabel']").hover();
  await page.locator("//LABEL[@id='stockAmountRowLabel']//following::LABEL[normalize-space() = \"No\"]").click();
  await page.getByRole('link', { name: "Save" }).click();
  await page.getByRole('heading', { name: "Success" }).hover();
  await expect(page.locator("div.modal-content>div.modal-body").nth(2)).toContainText("You have successfully saved your job entry for \\'Manager\\' at \\'Amazon.com\\'");
  await page.getByRole('link', { name: "No thanks. That's all for now!" }).click();
  await page.getByRole('link', { name: "Manager" }).hover();
  await page.locator("//DIV[normalize-space() = \"Amazon.com\"]").hover();
  await page.locator("div.sub-info.ng-scope>span.ng-binding").hover();
  await page.locator("div.badges>span.badge.ng-binding.ng-scope").hover();
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('e2e-tests-campuswide.admin.qa-12twenty.com/');
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("e2e Test Student");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "e2e Test Student" }).click();
  await page.getByRole('heading', { name: "e2e Test Student" }).hover();
  await page.getByRole('heading', { name: "Post Graduation" }).hover();
  await page.locator("//A[contains(text(),\"Manager\")]/following::DIV[normalize-space() = \"Amazon.com\"]").hover();
  await page.locator("div.badges>span.badge.ng-binding.ng-scope.offer-accepted").hover();
  await page.locator("div.badges>span.badge.ng-binding.ng-scope.alert").hover();
  await page.getByRole('link', { name: "Manager" }).click();
  await page.locator("dd.ng-scope>span.ng-binding.ng-scope").nth(6).hover();
  await page.locator("BUTTON[type='button']").nth(5).click();
  await page.getByRole('link', { name: "Edit" }).hover();
  await page.getByRole('link', { name: "Delete" }).hover();
  await page.getByRole('link', { name: "Approve" }).hover();
  await page.getByRole('link', { name: "Move Outcome" }).hover();
  await page.getByRole('link', { name: "Unaccept" }).hover();
  await page.getByRole('link', { name: "Add Outcome Note" }).hover();
  await page.getByRole('link', { name: "Exclude from Reporting" }).hover();
  await page.getByRole('link', { name: "View Outcome Audit Log" }).hover();
  await expect(page.locator("//dt[normalize-space()=\"Is Approved\"]//following-sibling::dd[contains(@class,\"ng-scope\")]")).toHaveText("No");
  await page.getByRole('link', { name: "Approve" }).click();
  await page.getByRole('heading', { name: "Approve Job" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Approve" }).click();
  await page.reload();
  await page.getByRole('link', { name: "Manager" }).click();
  await page.locator("BUTTON[type='button']").nth(5).click();
  await page.getByRole('link', { name: "Unapprove" }).hover();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete Entry" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Entry" }).click();
  await page.waitForTimeout(3000);
  await page.waitForLoadState('load');
  await page.reload();
  await page.reload();
  selector = MK.onSetGV(`//A[@role="button"][contains(text(),"Manager")]`, null);
  var isElementPresent = await page.locator(selector).count() > 0;
  if (!isElementPresent) {
  snippetLog('Element is not present.');
  } else {
  throw new Error('Element is present');
  }
  selector = MK.onSetGV(` //DIV[normalize-space() = "Amazon.com"]`, null);
  var isElementPresent = await page.locator(selector).count() > 0;
  if (!isElementPresent) {
  snippetLog('Element is not present.');
  } else {
  throw new Error('Element is present');
  }
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.reload();
  await page.waitForLoadState('load');
});
