// TC: TC62800
// Events - Employers can Search for upcoming and past events by name

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Events - Employers can Search for upcoming and past events by name", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto('https://employer.qa-12twenty.com/', { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Email Address").fill("e2e.employeruser.subscription.admin@walmart.com");
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.waitForTimeout(2000);
  await page.locator("button.btn.btn-school.submit-login-form>span").click();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").hover();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: "Events" }).click();
  await page.getByRole('link', { name: "Events" }).hover();
  await page.getByRole('link', { name: "Analytics" }).hover();
  await page.getByRole('heading', { name: "Events" }).hover();
  await page.reload();
  await page.locator("//SPAN[normalize-space() = \"Event Name\"]").click();
  await page.getByPlaceholder("Event Name").fill("Christmas Eve");
  await page.getByRole('heading', { name: "Events" }).click();
  await page.getByRole('link', { name: "Past" }).click();
  await page.locator("//SPAN[normalize-space() = \"Event Name\"]").click();
  await page.getByPlaceholder("Event Name").fill("Christmas Eve");
  await page.getByRole('heading', { name: "Events" }).click();
  selector = MK.onSetGV(`//SPAN[contains(text(),"Christmas Eve Event")]`, null);
  source = await page.locator(selector);
  if (await source.count() == 0){
  snippetLog("Performing steps. . .");
  await page.getByRole('link', { name: "Host an Event" }).click();
  await page.getByRole('heading', { name: "Please select one or more program types..." }).hover();
  await page.getByRole('button', { name: "Continue" }).click();
  await page.locator("//DIV[normalize-space() = \"Students & Alumni from non-12twenty schools\"]").click();
  await page.getByRole('link', { name: "Continue" }).click();
  await page.getByRole('heading', { name: "General" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Event Name*\"]").hover();
  await page.getByPlaceholder("Event Name").fill("Christmas Eve Event");
  await page.locator("//LABEL[normalize-space() = \"Event Type*\"]").hover();
  await page.locator("SELECT[id='CoreEventTypeId'][name='CoreEventTypeId']").selectOption("number:1");
  await page.locator("//LABEL[normalize-space() = \"Event Format*\"]").hover();
  await page.locator("SELECT[id='FormatId'][name='FormatId']").selectOption("number:1");
  await page.locator("//DIV[normalize-space() = \"You will be able to add a virtual meeting URL once the event is submitted\"]").hover();
  await page.getByRole('heading', { name: "Event Dates" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Time Zone*\"]").hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Eastern Time (US & Canada) (UTC-05:00)\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Event Date and Time*\"]").hover();
  await page.getByPlaceholder("MM/DD/YYYY").fill("12/24/2024");
  await page.waitForTimeout(1000);
  await page.getByPlaceholder("H:MMpm").fill("2:15pm");
  await page.getByPlaceholder("H:MMpm").fill("2:45pm");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Registration Dates*\"]").hover();
  await page.getByPlaceholder("MM/DD/YYYY").fill("11/24/2024");
  await page.getByRole('heading', { name: "98 Steps" }).fill("12:00pm");
  await page.getByPlaceholder("H:MMpm").fill("4:00pm");
  await page.locator("//LABEL[normalize-space() = \"Work Authorization *\"]").click();
  await page.getByRole('button', { name: "-- Please Select a Work Authorization --" }).click();
  await page.locator("//LABEL[normalize-space() = \"All Work Authorizations Accepted\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Work Authorization *\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Description*\"]").click();
  await page.locator("//DIV[@id='cke_Description'][@role='application'][normalize-space(translate(., '\\u00A0', ' ')) = \"Rich Text Editor, DescriptionEditor toolbars Undo Keyboard shortcut Ctrl+Z Redo Keyboard shortcut Ctrl+Y Bold Keyboard shortcut Ctrl+B Underline Keyboard shortcut Ctrl+U Italic Keyboard shortcut Ctrl+I Strikethrough Remove Format Insert/Remove Numbered List Insert/Remove Bulleted List Decrease Indent Increase Indent Link Keyboard shortcut Ctrl+K Unlink Insert Horizontal Line MaximizePress ALT 0 for help◢\"]").click();
  await page.getByRole('heading', { name: "Additional Candidate Requirements" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Additional Candidate Requirements*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Name*\"]").hover();
  await page.getByPlaceholder("Additional Candidate Requirements").fill("Stem Students");
  await page.getByPlaceholder("Name").fill("John");
  await page.locator("//LABEL[normalize-space() = \"Phone*\"]").hover();
  await page.getByPlaceholder("Phone").fill("8456321478");
  await page.locator("//LABEL[normalize-space() = \"Email*\"]").hover();
  await page.getByPlaceholder("Email").fill("john@yopmail.com");
  await page.getByPlaceholder("MM/DD/YYYY").fill("12/24/2024");
  await page.getByRole('link', { name: "Continue" }).click();
  await page.getByRole('heading', { name: "Event Details" }).hover();
  await page.getByRole('link', { name: "Submit" }).click();
  await page.getByRole('heading', { name: "Success!" }).hover();
  await page.locator("//DIV[normalize-space() = \"Your event has been submitted to your selected schools for approval.\"]").nth(1).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByRole('heading', { name: "Christmas Eve Event" }).click();
  await page.getByRole('button', { name: "Action" }).click();
  await page.getByRole('link', { name: "Cancel Event" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you would like to cancel this event? This action cannot be undone.\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByRole('link', { name: "Events" }).click();
  await page.getByRole('link', { name: "Past" }).click();
  }
  await expect(page.locator("a.primary-item.primary-item-with-icons>span.primary-item-text.ng-binding")).toHaveText("Christmas Eve Event");
  await page.locator("div.results-header-right>div.num-results.ng-binding").hover();
  await page.locator("td.center>span.badge.ng-binding").hover();
  await page.getByRole('button', { name: "Event Name Christmas Eve (empty)" }).click();
  await page.getByPlaceholder("Event Name").fill("Mexico");
  await page.getByRole('heading', { name: "Events" }).click();
  await page.locator("div.search-results>div.no-results").hover();
  await page.locator("div.results-header-right>div.num-results.ng-binding").hover();
  await page.reload();
  await page.waitForTimeout(2000);
});
