// TC: TC83327
// Events – Waitlisted Student Auto-Promotion on Cancellation

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Events – Waitlisted Student Auto-Promotion on Cancellation", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Events" }).click();
  await expect(page.getByRole('heading', { name: "Events" })).toHaveText("Events");
  await page.getByRole('link', { name: "Host an Event" }).click();
  await expect(page.getByRole('heading', { name: "Host an Event" })).toHaveText("Host an Event");
  await expect(page.getByRole('heading', { name: "General Info" })).toHaveText("General Info");
  await expect(page.locator("//LABEL[normalize-space() = \"Event Name*\"]")).toHaveText("Event Name*");
  await page.getByPlaceholder("Event Name").fill("Waitlist Event Test");
  await expect(page.locator("//LABEL[normalize-space() = \"Event Type*\"]")).toHaveText("Event Type*");
  await page.locator("SELECT[id='EventTypeId'][name='EventTypeId']").selectOption("number:1499993124744");
  await expect(page.locator("//LABEL[normalize-space() = \"Event Format\"]")).toHaveText("Event Format");
  await page.locator("SELECT[id='EventFormatId'][name='EventFormatId']").selectOption("number:3");
  await expect(page.locator("//LABEL[normalize-space() = \"# of Attendees Permitted*\"]")).toHaveText("# of Attendees Permitted*");
  await page.getByPlaceholder("# of Attendees Permitted").fill("1");
  await page.locator("//LABEL[contains(normalize-space(),\"Enable Waitlist\")]").hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Enable Waitlist\")]//following::LABEL[normalize-space() = \"Yes\"]").click();
  await expect(page.locator("//LABEL[normalize-space() = \"Dress Attire*\"]")).toHaveText("Dress Attire*");
  await page.locator("SELECT[id='DressAttireId'][name='DressAttireId']").selectOption("number:1");
  await expect(page.locator("//LABEL[normalize-space() = \"Work Authorization Requirement*\"]")).toHaveText("Work Authorization Requirement*");
  await page.getByRole('button', { name: "-- Work Authorization Requirement --" }).click();
  await page.keyboard.press("Tab");
  await page.keyboard.press("Enter");
  await expect(page.getByRole('heading', { name: "Event Dates" })).toHaveText("60000");
  await expect(page.locator("//LABEL[normalize-space() = \"Event Date and Time*\"]")).toHaveText("Event Date and Time*");
  await page.getByPlaceholder("MM/DD/YYYY").fill("04/14/2027");
  await page.getByPlaceholder("H:MMpm").fill("60000");
  await page.getByPlaceholder("H:MMpm").fill("60000");
  await expect(page.locator("//LABEL[normalize-space() = \"Student Registration*\"]")).toHaveText("60000");
  await page.getByPlaceholder("MM/DD/YYYY").fill("03/30/2026");
  await page.getByPlaceholder("H:MMpm").fill("60000");
  await page.getByPlaceholder("MM/DD/YYYY").fill("60000");
  await page.getByPlaceholder("H:MMpm").fill("60000");
  await expect(page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Student Publish Date *\"]")).toHaveText("60000");
  await page.getByPlaceholder("MM/DD/YYYY").fill("03/30/2026");
  await page.getByPlaceholder("H:MMpm").fill("60000");
  await expect(page.getByRole('heading', { name: "Event Description" })).toHaveText("60000");
  await page.locator("//BUTTON[@type='button'][@title='None selected'][normalize-space() = \"-- Select a Value --\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Select all\"]").nth(1).click();
  await expect(page.getByRole('heading', { name: "Primary Event Contact" })).toHaveText("60000");
  await page.getByRole('button', { name: "Use My Information" }).click();
  await expect(page.locator("//LABEL[normalize-space() = \"Contact Phone\"]")).toHaveText("Contact Phone");
  await page.getByPlaceholder("Contact Phone").fill("2222222222");
  await page.getByRole('button', { name: "Save" }).click();
  await expect(page.locator("//SPAN[normalize-space() = \"This event has been approved. Any edits will take effect immediately.\"]")).toContainText("This event has been approved. Any edits will take effect immediately.");
  await page.locator("BUTTON[type='button']").nth(3).click();
  await page.getByRole('link', { name: "12twenty" }).click();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByRole('link', { name: "Test Student #0001" }).click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Login As" }).click();
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('e2e-tests-campuswide.qa-12twenty.com/on-login?returnUrl=%2Fdashboard');
  await page.getByRole('link', { name: "Events" }).click();
  await expect(page.getByRole('heading', { name: "Events" })).toHaveText("Events");
  await page.getByPlaceholder("Employer, Event Name, or Keyword").fill("Waitlist Event Test");
  await expect(page.locator("//SPAN[normalize-space() = \"Registration Open\"]").nth(1)).toHaveText("60000");
  await expect(page.locator("//SPAN[normalize-space() = \"Not Registered\"]").nth(2)).toHaveText("Not Registered");
  await page.locator("//SPAN[normalize-space() = \"Waitlist Event Test\"]").nth(3).click();
  await page.getByRole('button', { name: "Register Now" }).click();
  indexPages = MK.onSetGV(`2`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator("//DIV[normalize-space() = \"Are you sure you want to register for this event?\"]")).toHaveText("Are you sure you want to register for this event?");
  await page.getByRole('link', { name: "Register" }).click();
  await expect(page.getByRole('heading', { name: "Registration Complete" })).toHaveText("Registration Complete");
  await page.getByRole('link', { name: "Go Back to Event Page" }).click();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForTimeout(2000);
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByRole('link', { name: "Test Student #0002" }).click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Login As" }).click();
  await page.waitForTimeout(2000);
  await page.getByRole('link', { name: "Events" }).click();
  await expect(page.getByRole('heading', { name: "Events" })).toHaveText("Events");
  await page.getByPlaceholder("Employer, Event Name, or Keyword").fill("Waitlist Event Test");
  await expect(page.locator("//SPAN[normalize-space() = \"Registration Open\"]").nth(1)).toHaveText("60000");
  await expect(page.locator("//SPAN[normalize-space() = \"Not Registered\"]").nth(2)).toHaveText("Not Registered");
  await page.locator("//SPAN[normalize-space() = \"Waitlist Event Test\"]").nth(3).click();
  await page.getByRole('button', { name: "Register for Waitlist" }).click();
  indexPages = MK.onSetGV(`2`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await expect(page.locator("//DIV[normalize-space() = \"Are you sure you want to register for the waitlist?\"]")).toHaveText("Are you sure you want to register for the waitlist?");
  await page.getByRole('link', { name: "Register" }).click();
  await expect(page.getByRole('heading', { name: "Registration Complete - Waitlist" })).toHaveText("Registration Complete - Waitlist");
  await page.getByRole('link', { name: "Go Back to Event Page" }).click();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('link', { name: "Events" }).click();
  await page.waitForLoadState('load');
  await expect(page.getByRole('heading', { name: "Events" })).toHaveText("Events");
  await page.getByPlaceholder("Employer, Event Name, or Keyword").fill("Waitlist Event Test");
  await page.locator("//SPAN[normalize-space() = \"Waitlist Event Test\"]").nth(3).click();
  await page.getByRole('link', { name: "Registered Students (1)" }).click();
  await expect(page.getByRole('heading', { name: "Registered Students" })).toHaveText("Registered Students");
  await expect(page.getByRole('heading', { name: "Waitlist Auto Promote Enabled Auto Promote Disabled" })).toHaveText("Waitlist Auto Promote Enabled Auto Promote Disabled");
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByRole('link', { name: "Test Student #0001" }).click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Login As" }).click();
  await page.waitForTimeout(2000);
  await page.waitForTimeout(2000);
  await page.getByRole('link', { name: "Events" }).click();
  await expect(page.getByRole('heading', { name: "Events" })).toHaveText("Events");
  await page.getByRole('link', { name: "Advanced Search" }).click();
  await page.getByPlaceholder("Employer, Event Name, or Keyword").fill("Waitlist Event Test");
  await expect(page.locator("//SPAN[normalize-space() = \"Registered\"]").nth(2)).toHaveText("60000");
  await page.locator("//SPAN[normalize-space() = \"Waitlist Event Test\"]").nth(3).click();
  await page.getByRole('button', { name: "Cancel Registration" }).click();
  await expect(page.locator("//DIV[normalize-space() = \"Are you sure you want to cancel your registration for this event?\"]").nth(1)).toHaveText("Are you sure you want to cancel your registration for this event?");
  await page.getByRole('button', { name: "OK" }).click();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('link', { name: "Events" }).click();
  await page.getByPlaceholder("Employer, Event Name, or Keyword").fill("Waitlist Event Test");
  await page.locator("//SPAN[normalize-space() = \"Waitlist Event Test\"]").nth(3).click();
  await page.getByRole('link', { name: "Registered Students (1)" }).click();
  await expect(page.getByRole('heading', { name: "Registered Students" })).toHaveText("Registered Students");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Cancel Registration" }).click();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByRole('link', { name: "Best rated" }).click();
  await page.getByRole('link', { name: "Delete" }).click();
  await expect(page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this event?\"]").nth(1)).toHaveText("Are you sure you want to permanently delete this event?");
  await page.getByRole('button', { name: "Delete Event" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Home" }).click();
  await page.getByRole('link', { name: "Events" }).click();
});
