// TC: TC64779
// OCI - Register for Interview and Job and apply as Student - Admin

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("OCI - Register for Interview and Job and apply as Student - Admin", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;
  const text = msg.text();
  const timestamp = new Date().toLocaleString();

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Job Listings & Interviews" }).click();
  await page.getByRole('heading', { name: "Job Listings & Interviews" }).hover();
  await page.getByRole('link', { name: "Register for Interviews" }).click();
  await page.getByRole('heading', { name: "Register For Interviews" }).hover();
  await page.getByRole('heading', { name: "Interview Details" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Employer*\"]").hover();
  await page.getByPlaceholder("Employer").fill("Walmart");
  await page.locator("div.tt-suggestion.tt-selectable>strong.tt-highlight").click();
  await page.locator("//LABEL[normalize-space() = \"OCI Round* :\"]").hover();
  await page.locator("SELECT[name='OciRoundId']").click();
  await page.keyboard.press("ArrowDown");
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.active.day").click();
  var today = new Date();
  today.setDate(today.getDate() + 1);
  var formattedDate = ("0" + (today.getMonth() + 1)).slice(-2) + '/' +
  ("0" + today.getDate()).slice(-2) + '/' +
  today.getFullYear();
  date = formattedDate;
  await page.getByPlaceholder("MM/DD/YYYY").fill("` + date + `");
  await page.getByRole('heading', { name: "Interview Periods Please Note: Once period dates for individual OCI registrations have been customized, periods can no longer be added or removed from the round. OCI periods can be added or removed from a round, even if there are active OCI registrations, unless period dates have been customized for individual OCI registrations" }).hover();
  await page.locator("tr>th").hover();
  await page.locator("tr>th").nth(1).hover();
  await page.getByRole('heading', { name: "Interview Date Preferences Preferred Interview Dates cannot be the same." }).hover();
  await page.locator("div.form-group.ng-scope>label.control-label").nth(2).click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Second Choice\"]").click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(30).click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Third Choice\"]").click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(31).click();
  await page.locator("label.control-label>span.ng-binding").click();
  await page.locator("SELECT[id='custom_attribute_800'][name='custom_attribute_800']").click();
  await page.locator("SELECT[id='custom_attribute_800'][name='custom_attribute_800']").selectOption("1180051101059");
  await page.getByRole('heading', { name: "Interview Preferences" }).hover();
  await page.locator("//LABEL[normalize-space() = \"# of Total Interview Slots*\"]").click();
  await page.getByPlaceholder("# of Total Interview Slots").fill("20");
  await page.locator("//LABEL[normalize-space() = \"# of Interview Rooms Requested*\"]").click();
  await page.getByPlaceholder("# of Interview Rooms Requested").fill("4");
  await page.locator("//LABEL[normalize-space() = \"Length of Interview*\"]").click();
  await page.getByPlaceholder("Length of Interview").fill("15");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Rotating Schedule\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[normalize-space() = \"Are you hiring for multiple positions?\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(1).click();
  await page.locator("//LABEL[normalize-space() = \"Please set the number of applications allowed per student across all positions\"]").click();
  await page.getByRole('heading', { name: "Additional Information" }).hover();
  await page.locator("div.form-group>label.control-label").nth(12).hover();
  await page.getByPlaceholder("Please set the number of applications allowed per student across all positions").fill("7");
  await page.locator("div.form-group>label.control-label").nth(13).hover();
  await page.getByPlaceholder("Visitation Description").fill("Testing visitation description, muuktest automated test case");
  await page.getByPlaceholder("Special Request").click();
  await page.locator("//LABEL[contains(normalize-space(),\"Employer Presentation?\")]").hover();
  await page.getByPlaceholder("Special Request").fill("Testing special request, muuktest automated test case");
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(2).click();
  await page.locator('input[type="radio"]').check();
  await page.locator("div.form-group>label.control-label").nth(15).hover();
  await page.locator("//LABEL[contains(normalize-space(),\"Office Hours?\")]").hover();
  await page.getByPlaceholder("Employer Presentation Details").fill("Testing employer presentation details, muuktest automated test case");
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(3).click();
  await page.locator('input[type="radio"]').check();
  await page.locator("div.form-group>label.control-label").nth(17).hover();
  await page.getByRole('heading', { name: "Interview Contact" }).hover();
  await page.getByPlaceholder("Office Hour Details").fill("Testing office hours details, muuktest automated test case");
  await page.getByRole('button', { name: "Use My Information" }).click();
  await page.getByPlaceholder("OCI Contact Title").fill("Accountant");
  await page.locator("//LABEL[normalize-space() = \"OCI Contact Address*\"]").hover();
  await page.getByPlaceholder("OCI Contact Phone").fill("7897897890");
  await page.getByPlaceholder("OCI Contact Address").fill("Hyderabad");
  await page.getByRole('button', { name: "Next" }).click();
  await page.getByRole('heading', { name: "On-Campus Interviews" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Ok" }).click();
  await page.getByRole('link', { name: "Post a Job" }).click();
  await page.getByRole('heading', { name: "Create Job Posting" }).hover();
  await page.getByPlaceholder("Job Title").fill("Manager");
  await page.getByRole('button', { name: "-- Type of Job --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Salary Range\"]").click();
  await page.getByPlaceholder("Min").fill("50000");
  await page.getByPlaceholder("Max").fill("70000");
  await page.locator("SELECT[name='CurrencyId']").selectOption("number:14");
  await page.locator("SELECT[name='PayFormatId']").selectOption("number:3");
  await page.locator("SELECT[id='LocationTypeId'][name='LocationTypeId']").selectOption("number:2");
  await page.getByRole('button', { name: "-- Industry --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Job Function*\"]").click();
  await page.getByRole('button', { name: "-- Job Function --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Preferred Years of Experience\"]").click();
  await page.getByPlaceholder("Preferred Years of Experience").fill("2");
  await page.locator("SELECT[id='InterviewFormatId'][name='InterviewFormatId']").selectOption("number:6");
  await page.getByRole('button', { name: "-- Work Authorization Requirement --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('heading', { name: "Application Method(s)*" }).click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Apply via This Site*\"]").click();
  await page.locator("div.form-group>label.control-label").nth(12).click();
  await page.locator("//LABEL[contains(text(),\"Apply via External Link\")]//following::label[normalize-space()=\"No\"]").click();
  await page.locator('input[type="radio"]').check();
  await page.locator("div.form-group>label.control-label").nth(13).click();
  await page.locator("//LABEL[contains(text(),\"Apply via Email\")]//following::LABEL[normalize-space() = \"Yes\"]").click();
  await page.getByPlaceholder("e.g. sample@domain.com").fill("john123@12twenty.com");
  await page.getByRole('heading', { name: "Job Description" }).click();
  await page.locator("label.control-label>span").nth(15).click();
  textContent = MK.onSetGV(`Managing a portfolio of clients, developing strong relationships, and ensuring the successful delivery of our products and services.`, null);
  page.keyboard.type(textContent);
  await page.getByRole('heading', { name: "Attachments" }).click();
  fileName = MK.onSetGV(`Test_Resume_01.pdf`, null);
  var fileInput = await page.$("INPUT[type='file']");
  var filePath ="./test/"+fileName;
  if(fileInput){
  await fileInput.setInputFiles(filePath);
  }
  else{
  throw new Error('Element to upload file is not present.');
  }
  await page.locator("//LABEL[normalize-space() = \"Interviewer*\"]").click();
  await page.keyboard.press("ArrowDown");
  await page.getByRole('button', { name: "Use My Information" }).click();
  await page.getByPlaceholder("Title").fill("Project Manager");
  await page.getByPlaceholder("Job Posting Contact Phone").fill("9766336543");
  await page.getByPlaceholder("Job Posting Contact Address").fill("Hyderabad 123");
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(4).click();
  await page.locator("SELECT[id='ContactAlumniGraduationYear'][name='ContactAlumniGraduationYear']").selectOption("number:2021");
  await page.locator("SELECT[id='ContactAlumniGraduationProgramId'][name='ContactAlumniGraduationProgramId']").selectOption("number:14999901011484");
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.ng-scope>label.control-label.ng-binding").nth(3).click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.ng-scope>label.control-label.ng-binding").nth(4).click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.ng-scope>label.control-label.ng-binding").nth(5).click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.ng-scope>label.control-label.ng-binding").nth(5).click();
  await page.locator("SELECT[id='JobPostingSourceId'][name='JobPostingSourceId']").selectOption("number:100063031018421");
  await page.locator("SELECT[id='custom_attribute_3'][name='custom_attribute_3']").click();
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Enter');
  await page.locator("//LABEL[normalize-space() = \"# of Total Interview Slots*\"]").click();
  await page.getByPlaceholder("# of Total Interview Slots").fill("3");
  await page.getByRole('button', { name: "Next" }).click();
  await page.getByRole('heading', { name: "Job Posting" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Ok" }).click();
  await expect(page.getByRole('heading', { name: "Manager" })).toHaveText("                Manager                                                                                                                            ");
  await expect(page.getByRole('link', { name: "Walmart" })).toHaveText("Walmart");
  await page.locator("div.sub-header.ng-scope>text.ng-binding").hover();
  await expect(page.locator("//SPAN[normalize-space() = \"Full-Time Job\"]")).toHaveText(" Full-Time Job");
  await expect(page.locator("//SPAN[normalize-space() = \"Schedule Not Released\"]")).toHaveText("                        Schedule Not Released                    ");
  await expect(page.locator("div.sub-header.badges>span.badge.badge-false.ng-scope")).toHaveText("                        Rotating Schedules Requested                    ");
  await expect(page.locator("div.sub-header.badges>span.badge.pending-approval.ng-binding.ng-scope")).toHaveText("Date Needed");
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('e2e-tests-campuswide.qa-12twenty.com/');
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.student.fullaccess@campuswide.com");
  await page.getByPlaceholder("Password").fill("BoH5dORH7xg%");
  await page.getByRole('button', { name: "Student/Alumni Log In" }).click();
  await page.waitForTimeout(1000);
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Job Listings & Interviews" }).click();
  await page.getByRole('link', { name: "Advanced Search" }).click();
  await page.waitForTimeout(3000);
  await page.locator("tt-display-selected-filter-default.ng-isolate-scope>span.has-filter-value.ng-binding.not-excluded").click();
  await page.locator("//LABEL[normalize-space() = \"Approved\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Application Open\"]").click();
  await page.getByRole('heading', { name: "Job Listings & Interviews" }).click();
  await page.getByPlaceholder("Employer, Job Title, or Keyword").fill("Manager");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Manager" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Apply Now" }).click();
  await page.waitForTimeout(3000);
  indexPages = MK.onSetGV(`2`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.locator("em>span").hover();
  fileName = MK.onSetGV(`Test_Resume_01.pdf`, null);
  var fileInput = await page.$("INPUT[type='file']");
  var filePath ="./test/"+fileName;
  if(fileInput){
  await fileInput.setInputFiles(filePath);
  }
  else{
  throw new Error('Element to upload file is not present.');
  }
  await page.getByRole('link', { name: "Continue" }).click();
  await page.locator("//LABEL[normalize-space() = \"I have completed the above application requirements\"]").click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.getByRole('button', { name: "Yes" }).click();
  await page.getByRole('link', { name: "Submit Application" }).click();
  await page.getByRole('heading', { name: "Thank you for letting us know you applied!" }).hover();
  await page.getByRole('link', { name: "Back to Job Details" }).click();
  await expect(page.locator("//DIV[contains(normalize-space(), \"Application: You applied for this job posting on\")]").nth(1)).toContainText("                                Application: You applied for this job posting on                                                                                                                                                                                                ");
  await page.getByRole('button', { name: "Withdraw from Application" }).hover();
  await page.getByRole('button', { name: "Edit Application" }).hover();
  await page.waitForTimeout(2000);
  await page.waitForTimeout(5000);
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.reload();
  await page.getByRole('link', { name: "Applicants (1)" }).click();
  await page.getByRole('link', { name: "e2e Test Student" }).hover();
  await page.locator("//A[normalize-space() = \"e2e Test Student\"]/ancestor::tr//button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Delete Application" }).click();
  await page.getByRole('heading', { name: "Remove Applicant" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Delete" }).click();
  await page.waitForTimeout(5000);
  await page.reload();
  await page.reload();
  selector = MK.onSetGV(`//A[contains(text(),"e2e Test Student")]`, null);
  var isElementPresent = await page.locator(selector).count() > 0;
  if (!isElementPresent) {
  snippetLog('Element is not present.');
  } else {
  throw new Error('Element is present');
  }
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete Job Posting" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Job Posting" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Job Listings & Interviews" }).hover();
  await page.reload();
  await page.waitForTimeout(2000);
  selector = MK.onSetGV(`//SPAN[contains(text(),"Manager")]//ancestor::td//span[normalize-space()="Walmart"]`, null);
  var isElementPresent = await page.locator(selector).count() > 0;
  if (!isElementPresent) {
  snippetLog('Element is not present.');
  } else {
  throw new Error('Element is present');
  }
});
