// TC: TC59304
// Command Center - Interview session Student and Employer - Admin

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Command Center - Interview session Student and Employer - Admin", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;
  const text = msg.text();
  const timestamp = new Date().toLocaleString();

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Job Listings & Interviews" }).hover();
  await page.locator("//A[normalize-space() = \"Job Listings & Interviews\"]//following::BUTTON").click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Command Center" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Interview Command Center" }).hover();
  await page.locator("//SPAN[normalize-space() = \"Interview Date\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Relative Range\"]").click();
  await page.locator("SELECT[name='date_']").click();
  await page.keyboard.press("today");
  await page.locator("//SPAN[normalize-space() = \"Interview Date\"]").click();
  await page.getByRole('heading', { name: "Interview Command Center" }).click();
  await page.getByRole('link', { name: "Waiting (4)" }).click();
  await page.waitForTimeout(5000);
  jobPostingName = await page.locator('(//span[contains(@class,"primary-item-text ng-binding ng-scope")])[last()]//following::span[@class="primary-item-text ng-binding"]').innerText();
  snippetLog('JOB POSTING NAME:' + jobPostingName);
  await page.waitForTimeout(2000);
  urlpage1 = page.url();
  const studentNum = await page.locator('(//span[contains(@class,"primary-item-text ng-binding ng-scope")])[last()]').innerText();
  snippetLog("studentNum: "+ studentNum);
  // Get the time of the current interview
  var locator = page
  .locator('(//span[contains(@class,"primary-item-text ng-binding ng-scope")])[last()]/ancestor::tr//tt-date-time-display')
  .first();
  var fullText = (await locator.innerText()).trim();
  snippetLog(`Full text: ${fullText}`);
  var timeOnly = fullText.split(',')[1]?.trim();
  interviewTime = timeOnly; // assign it to global variable
  snippetLog(`Time extracted: ${interviewTime}`);
  await page.locator("(//span[contains(@class,\"primary-item-text ng-binding ng-scope\")])[last()]").click();
  urlpage2 = page.url();
  await page.getByRole('heading', { name: "Test Student #0092" }).hover();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Login As" }).click();
  await page.waitForTimeout(3000);
  await page.waitForLoadState('load');
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForTimeout(2000);
  selector = MK.onSetGV(`//A[@role=\'button\'][normalize-space() = \'Bypass "On Next Login" (Admin Only)\']`, null);
  source = await page.locator(selector);
  if (await source.count() > 0){
  snippetLog("Performing steps. . .");
  await page.locator("//A[@role='button'][normalize-space() = 'Bypass \"On Next Login\" (Admin Only)']").click();
  }
  await page.getByRole('link', { name: "Job Listings & Interviews" }).click();
  await page.getByPlaceholder("Employer, Job Title, or Keyword").fill("` + jobPostingName + `");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.locator(`//*[normalize-space()="${jobPostingName}"]`).nth(0).click();
  snippetLog(`Clicked on the span with text: ${jobPostingName}`);
  urlpage3 = page.url();
  await page.waitForTimeout(2000);
  await page.locator("a.meeting-join-link.ng-scope>span.meeting-join-link-text.ng-binding").click();
  await page.waitForTimeout(2000);
  await page.waitForLoadState('load');
  await page.waitForTimeout(2000);
  await page.reload();
  await page.getByRole('heading', { name: "206 Steps" }).click();
  await page.waitForTimeout(1000);
  await page.waitForTimeout(3000);
  await page.locator("a>span.mw-ui-button.mw-ui-quiet").nth(4).click();
  await page.waitForTimeout(1000);
  await page.reload();
  await page.getByRole('heading', { name: "206 Steps" }).click();
  await page.waitForTimeout(1000);
  await page.waitForTimeout(1000);
  await page.locator("a>span.mw-ui-button.mw-ui-quiet").nth(4).click();
  await page.waitForTimeout(1000);
  await page.waitForTimeout(1000);
  urlpage4 = page.url();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForLoadState('load');
  await page.waitForTimeout(2000);
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Job Listings & Interviews" }).click();
  await page.getByRole('link', { name: "Command Center" }).click();
  await page.getByRole('link', { name: "Waiting (4)" }).click();
  await page.waitForTimeout(2000);
  await page.locator("(//span[contains(@class,\"primary-item-text ng-binding ng-scope\")])[last()]/following::span[contains(text(),\"Job Posting\")]").click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Schedule" }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: "Schedule Actions" }).click();
  await page.getByRole('link', { name: "Send Interviewer Links" }).click();
  await page.locator("//A[@id=\"navbar-settings-btn\"][normalize-space() = \"Site Management\"]/following::button[contains(@class,\"sub-menu-icon\")]").click();
  await page.getByRole('link', { name: "Email Activity" }).click();
  await page.getByRole('link', { name: "Interview Link" }).click();
  await page.getByRole('link', { name: "this link" }).click();
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForTimeout(2000);
  await page.waitForLoadState('load');
  interviewerurl = page.url();
  snippetLog('interviewerurl: ' + interviewerurl);
  await page.waitForTimeout(2000);
  urlpage1 = page.url();
  await page.waitForTimeout(2000);
  const contextCarmen = await page.context().browser().newContext();
  const pageCarmen = await contextCarmen.newPage();
  pageCarmen.goto(interviewerurl);
  await page.waitForTimeout(5000);
  await page.waitForLoadState('load');
  indexPages = MK.onSetGV(`0`, null);
  indexWindow = MK.onSetGV(`0`, null);
  newPages = contextCarmen.pages();
  pagesAfterPopUp = newPages[parseInt(indexPages)];
  snippetLog('Redeclared window');
  snippetLog(await page.url());
  await page.waitForLoadState('load');
  await page.waitForTimeout(5000);
  await page.getByRole('heading', { name: "205 Steps" }).click();
  await page.waitForTimeout(1000);
  await page.waitForTimeout(1000);
  await page.locator("a>span.mw-ui-button.mw-ui-quiet").nth(4).click();
  await page.waitForTimeout(2000);
  indexWindow = MK.onSetGV(`1`, null);
  newPages = contextCarmen.pages();
  pagesAfterPopUp = newPages[parseInt(indexPages)];
  snippetLog('Redeclared window');
  snippetLog(await page.url());
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForTimeout(1000);
  await page.locator("//A[normalize-space() = \"Job Listings & Interviews\"]//following::BUTTON").click();
  await page.getByRole('link', { name: "Command Center" }).click();
  await page.getByRole('link', { name: "Waiting (4)" }).click();
  await page.getByRole('link', { name: "In Progress (1)" }).click();
  indexWindow = MK.onSetGV(`0`, null);
  indexPages = MK.onSetGV(`0`, null);
  newPages = contextCarmen.pages();
  pagesAfterPopUp = newPages[parseInt(indexPages)];
  snippetLog('Redeclared window');
  snippetLog(await page.url());
});
