// TC: TC62910
// Job Postings - Post a Student Employment Job

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Job Postings - Post a Student Employment Job", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;
  const text = msg.text();
  const timestamp = new Date().toLocaleString();

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.waitForTimeout(1000);
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Job Listings & Interviews" }).click();
  await page.getByRole('heading', { name: "Job Listings & Interviews" }).hover();
  await page.getByRole('link', { name: "Student Employment" }).click();
  await page.getByRole('link', { name: "Post a Student Employment Job" }).click();
  await page.getByRole('heading', { name: "Create Student Employment Job" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Employer*\"]").hover();
  await page.getByPlaceholder("Employer").fill("State Farm Insurance");
  await page.locator("div.tt-suggestion.tt-selectable>strong.tt-highlight").click();
  await page.locator("//LABEL[normalize-space() = \"Job Title*\"]").click();
  await page.getByPlaceholder("Job Title").fill("Manager");
  await page.locator("div.form-group>label.control-label").nth(2).click();
  await page.getByRole('button', { name: "-- Type of Job --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Salary Range\"]").click();
  await page.getByPlaceholder("Min").fill("50");
  await page.getByPlaceholder("Max").fill("70");
  await page.locator("SELECT[name='CurrencyId']").selectOption("number:14");
  await page.locator("SELECT[name='PayFormatId']").selectOption("number:3");
  await page.locator("//LABEL[normalize-space() = \"Location Type*\"]").click();
  await page.locator("SELECT[id='LocationTypeId'][name='LocationTypeId']").selectOption("number:2");
  await page.locator("//LABEL[normalize-space() = \"Industry*\"]").click();
  await page.getByRole('button', { name: "-- Industry --" }).click();
  await page.getByPlaceholder("Search").fill("Accounting ");
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Job Function*\"]").click();
  await page.getByRole('button', { name: "-- Job Function --" }).click();
  await page.getByPlaceholder("Search").fill("Audit");
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Preferred Years of Experience\"]").click();
  await page.getByPlaceholder("Preferred Years of Experience").fill("2");
  await page.locator("//LABEL[normalize-space() = \"Interview Format\"]").click();
  await page.locator("SELECT[id='InterviewFormatId'][name='InterviewFormatId']").selectOption("number:6");
  await page.getByRole('button', { name: "-- Work Authorization Requirement --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Work-Study Required?\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Apply via This Site*\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(1).click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Apply via External Link\"]").click();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(2).click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Apply via Email\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(3).click();
  await page.getByPlaceholder("e.g. sample@domain.com").fill("state123@gmail.com");
  await page.getByRole('heading', { name: "Job Description" }).click();
  await page.locator("div.form-group>label.control-label").nth(15).click();
  await page.getByRole('heading', { name: "Attachments" }).click();
  fileName = MK.onSetGV(`Test_Resume_01.pdf`, null);
  var fileInput = await page.$("INPUT[type='file']");
  var filePath ="./test/"+fileName;
  if(fileInput){
  await fileInput.setInputFiles(filePath);
  }
  else{
  throw new Error('Element to upload file is not present.');
  }
  await page.locator("a.file-name>span.temp-file.ng-binding").hover();
  await page.getByRole('heading', { name: "Application Document Requirements" }).click();
  await page.locator("div.form-section-header>span.form-section-header-help-text").click();
  await page.getByRole('heading', { name: "Job Dates" }).click();
  await page.locator("//LABEL[normalize-space() = \"Time Zone*\"]").click();
  await page.getByRole('button', { name: "Guadalajara, Mexico City, Monterrey (UTC-06:00)" }).click();
  await page.getByPlaceholder("Search").fill("Chennai");
  await page.locator("//LABEL[normalize-space() = \"Chennai, Kolkata, Mumbai, New Delhi (UTC+05:30)\"]").click();
  await page.locator('input[type="radio"]').check();
  await page.locator("div.form-group.ng-scope>label.control-label").nth(2).click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(10).click();
  await page.locator("div.form-group.ng-scope>label.control-label").nth(3).click();
  await page.locator("//LABEL[normalize-space() = \"How do you plan on reviewing your applicants?\"]").click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[normalize-space() = \"I will review applicants as they come in, and may close the job posting early\"]").click();
  await page.locator("div.form-group>label.control-label").nth(20).click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>th.next").click();
  await page.locator("tr>td.day").nth(6).click();
  await page.getByRole('heading', { name: "Interview Detail" }).click();
  await page.locator("div.form-section-header>span.form-section-header-help-text").nth(1).click();
  await page.locator("//LABEL[normalize-space() = \"Interviewer\"]").click();
  await page.getByRole('heading', { name: "Primary Job Contact" }).click();
  await page.getByRole('button', { name: "Use My Information" }).click();
  await page.getByPlaceholder("Title").fill("test");
  await page.getByPlaceholder("Job Posting Contact Phone").fill("9153455681");
  await page.getByPlaceholder("Job Posting Contact Address").fill("Hyderabad");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Is Alumnus\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(4).click();
  await page.locator("div.form-group>label.control-label").nth(31).click();
  await page.locator("SELECT[id='ContactAlumniGraduationYear'][name='ContactAlumniGraduationYear']").selectOption("number:2021");
  await page.locator("div.form-group>label.control-label").nth(32).click();
  await page.locator("SELECT[id='ContactAlumniGraduationProgramId'][name='ContactAlumniGraduationProgramId']").selectOption("number:14999901011484");
  await page.getByRole('heading', { name: "Eligibility" }).click();
  await page.locator("div.form-section-header>div.form-section-header-help-text.ng-binding").click();
  await page.locator("//LABEL[normalize-space() = \"Student Group*\"]").click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.ng-scope>label.control-label.ng-binding").nth(4).click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.ng-scope>label.control-label.ng-binding").nth(5).click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.ng-scope>label.control-label.ng-binding").nth(6).click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('heading', { name: "Career Center Administrator" }).click();
  await page.locator("div.form-section-header>span.form-section-header-help-text").nth(2).click();
  await page.locator("//LABEL[normalize-space() = \"Source of Job Posting\"]").click();
  await page.locator("SELECT[id='JobPostingSourceId'][name='JobPostingSourceId']").selectOption("number:100063031018421");
  await page.locator("label.control-label>span.ng-binding").click();
  await page.locator("SELECT[id='custom_attribute_3'][name='custom_attribute_3']").click();
  await page.getByRole('heading', { name: "Job Posting Owner" }).click();
  await page.locator("div.form-section-header>span.form-section-header-help-text").nth(3).click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.locator("button.btn.btn-school.ng-scope>span.ng-scope").nth(1).hover();
  await page.getByRole('button', { name: "Save Draft" }).hover();
  await page.getByRole('button', { name: "Next" }).click();
  await page.getByRole('heading', { name: "Job Posting" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Ok" }).click();
  await page.getByRole('heading', { name: "Manager" }).hover();
  await page.getByRole('link', { name: "State Farm Insurance" }).hover();
  await page.locator("div.sub-header.ng-scope>text.ng-binding").hover();
  await page.locator("//SPAN[normalize-space() = \"Full-Time Job\"]").hover();
  await page.locator("div.sub-header.badges>span.badge").hover();
  await page.locator("//SPAN[normalize-space() = \"Job Posting Status: Application Open. Any edits will take effect immediately.\"]").hover();
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('e2e-tests-campuswide.qa-12twenty.com/');
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.student.fullaccess@campuswide.com");
  await page.getByPlaceholder("Password").fill("BoH5dORH7xg%");
  await page.getByRole('button', { name: "Student/Alumni Log In" }).click();
  await page.waitForTimeout(1000);
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Job Listings & Interviews" }).click();
  await page.getByRole('heading', { name: "Job Listings & Interviews" }).hover();
  await page.getByRole('link', { name: "Advanced Search" }).click();
  await page.getByPlaceholder("Employer, Job Title, or Keyword").fill("Manager");
  await page.locator("BUTTON[aria-label=\"Search\"]").click();
  await page.locator("//SPAN[normalize-space() = \"Manager\"]").click();
  await page.getByRole('link', { name: "Job Details" }).hover();
  await page.getByRole('heading', { name: "Manager" }).hover();
  await page.getByRole('link', { name: "State Farm Insurance" }).hover();
  await page.getByRole('link', { name: "Apply Now" }).click();
  indexPages = MK.onSetGV(`2`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('heading', { name: "Manager" }).hover();
  await page.getByRole('link', { name: "State Farm Insurance" }).hover();
  fileName = MK.onSetGV(`Test_Resume_01.pdf`, null);
  var fileInput = await page.$("INPUT[type='file']");
  var filePath ="./test/"+fileName;
  if(fileInput){
  await fileInput.setInputFiles(filePath);
  }
  else{
  throw new Error('Element to upload file is not present.');
  }
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Continue" }).click();
  await page.getByRole('heading', { name: "Application Instructions" }).hover();
  await page.locator("//SPAN[normalize-space() = \"Apply Externally\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Documents to Include\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"I have completed the above application requirements\"]").click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you have completed the application instructions on this page? This employer is requiring you to: Apply via email: state123@gmail.com\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Yes" }).click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Mark as Applied" }).click();
  await page.getByRole('heading', { name: "Thank you for letting us know you applied!" }).hover();
  await page.locator("//SPAN[normalize-space() = \"Manager\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"State Farm Insurance\"]").hover();
  await page.getByRole('link', { name: "Back to Job Details" }).click();
  await page.getByRole('button', { name: "Withdraw from Application" }).hover();
  await page.getByRole('button', { name: "Edit Application" }).hover();
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.reload();
  await page.getByRole('link', { name: "Applicants (1)" }).click();
  await page.getByRole('link', { name: "e2e Test Student" }).hover();
  await page.locator("//A[normalize-space() = \"e2e Test Student\"]/ancestor::tr//button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Delete Application" }).click();
  await page.getByRole('heading', { name: "Remove Applicant" }).hover();
  await page.locator("//DIV[normalize-space() = \"This will delete the application of the student(s) and remove them from the process.\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete" }).click();
  await page.waitForTimeout(5000);
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete Job Posting" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
});
