// TC: TC63795
// 12TE - Events - Create, searching and cancel - Employer

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("12TE - Events - Create, searching and cancel - Employer", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(employerQA, { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Email Address").fill("e2e.employeruser.subscription.admin@walmart.com");
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.waitForTimeout(2000);
  await page.locator("button.btn.btn-school.submit-login-form>span").click();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").hover();
  await page.getByRole('link', { name: "Events" }).click();
  await page.getByRole('heading', { name: "Events" }).hover();
  await page.getByRole('link', { name: "Upcoming" }).hover();
  await page.getByRole('link', { name: "Past" }).hover();
  await page.getByRole('link', { name: "Host an Event" }).click();
  await page.getByRole('heading', { name: "Please select one or more program types..." }).hover();
  await page.getByRole('heading', { name: "Business" }).hover();
  await page.locator("//P[normalize-space() = \"MBA, EMBA & PTMBA\"]").hover();
  await page.getByRole('heading', { name: "Business" }).click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Continue" }).click();
  await page.locator("div.logo-container>img.school-logo.ng-scope").nth(6).hover();
  await page.locator("div.school-info>div.school-name.ng-binding").nth(50).click();
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Back" }).hover();
  await page.getByRole('link', { name: "Continue" }).click();
  await page.getByRole('heading', { name: "Event Dates" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Time Zone*\"]").hover();
  await page.getByPlaceholder("Event Name").fill("Event Muuktest-12Twenty");
  await page.locator("//LABEL[normalize-space() = \"Event Type*\"]").click();
  await page.locator("SELECT[id='CoreEventTypeId'][name='CoreEventTypeId']").click();
  await page.keyboard.press("ArrowDown");
  await page.locator("//LABEL[normalize-space() = \"Event Format*\"]").click();
  await page.locator("SELECT[name='FormatId']").click();
  await page.keyboard.press("ArrowDown");
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.getByPlaceholder("Search").fill("Pacific Time");
  await page.locator("//LABEL[normalize-space() = \"Pacific Time (US & Canada) (UTC-08:00)\"]").click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Event Date and Time*\"]").hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").fill("12:00pm");
  await page.getByPlaceholder("H:MMpm").fill("1:15pm");
  await page.locator("div.form-group>label.control-label.ng-binding.ng-scope").nth(1).hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").fill("12:00am");
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.getByPlaceholder("H:MMpm").fill("11:00am");
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.locator("div.form-group>label.control-label").nth(6).click();
  await page.getByRole('button', { name: "-- Please Select a Work Authorization --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Select all\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Permanent US Work Authorization Required\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"STEM eligible degree\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"All Work Authorizations Accepted\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Other Work Authorization Required\"]").hover();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Description*\"]").click();
  await page.locator("body.cke_editable.cke_editable_themed.cke_contents_ltr.cke_show_borders>p").click();
  await page.getByPlaceholder("Additional Candidate Requirements").fill("60000");
  await page.getByRole('heading', { name: "Primary Event Contact" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Name*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Phone*\"]").hover();
  await page.getByPlaceholder("Name").fill("John");
  await page.locator("//LABEL[normalize-space() = \"Email*\"]").hover();
  await page.getByPlaceholder("Phone").fill("8456321478");
  await page.getByPlaceholder("Email").fill("john@yopmail.com");
  await page.getByRole('link', { name: "Continue" }).click();
  await page.getByRole('heading', { name: "Event Details" }).hover();
  await page.getByRole('button', { name: "Submit" }).click();
  await page.getByRole('heading', { name: "Success!" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByRole('heading', { name: "Event Muuktest-12Twenty" }).hover();
  await page.locator("div.header-main>div.sub-header.ng-binding").hover();
  await page.locator("div.sub-header>em").hover();
  await page.locator("span>span.ng-binding.ng-scope").hover();
  await page.locator("div.sub-header>span.badge.missing-information.ng-scope").hover();
  await page.getByRole('button', { name: "Action" }).click();
  await page.getByRole('link', { name: "Edit Event" }).hover();
  await page.getByRole('link', { name: "Duplicate Event" }).hover();
  await page.getByRole('link', { name: "Cancel Event" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByRole('link', { name: "Events" }).click();
  await page.getByRole('heading', { name: "Events" }).hover();
  await page.getByRole('link', { name: "Upcoming" }).click();
  await page.waitForTimeout(3000);
  selector = MK.onSetGV(`//SPAN[contains(text(),"Active")]//ancestor::tr//SPAN[contains(text(),"Event Muuktest-12Twenty")]`, null);
  var isElementPresent = await page.locator(selector).count() > 0;
  if (!isElementPresent) {
  snippetLog('Element is not present.');
  } else {
  throw new Error('Element is present');
  }
});
