// TC: TC63105
// Admin - Bulk Update Students

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Admin - Bulk Update Students", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto('https://e2e-tests-campuswide.admin.qa-12twenty.com/dashboard', { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.waitForTimeout(2000);
  await page.reload();
  await page.getByRole('button', { name: "Add Filter" }).click();
  await page.getByPlaceholder("Search filters").fill("Student Group");
  await page.locator("li.ng-scope>span.filter-group.ng-binding").hover();
  await page.getByRole('button', { name: "Student Group" }).click();
  await page.waitForTimeout(2000);
  await page.locator("//LABEL[normalize-space() = \"Bulk Update 1\"]").click();
  await page.getByRole('heading', { name: "Students & Alumni" }).click();
  await page.locator("BUTTON[type='button']").nth(16).click();
  await page.getByRole('link', { name: "Bulk Update All" }).click();
  await page.locator("div.form-group>label.control-label").hover();
  await page.locator("SELECT[id='SelectAttribute'][name='SelectAttribute']").selectOption("number:1000100");
  await page.locator("div.form-group>label.control-label").nth(2).hover();
  await page.locator("//LABEL[normalize-space() = \"Append\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Replace all values\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Replace\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Append\"]").click();
  await page.locator('input[type="radio"]').check();
  await page.locator("label.control-label.ng-binding>span.ng-scope").nth(1).hover();
  await page.locator("//LABEL[normalize-space() = \"New value*\"]").hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"New value*\"]").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.locator("BUTTON[type='button']").nth(16).click();
  await page.locator("BUTTON[type='button']").nth(16).click();
  await page.reload();
  await page.locator("//span[normalize-space()=\"Student Group\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Bulk Update 2\"]").click();
  await page.getByRole('heading', { name: "Students & Alumni" }).click();
  await page.locator("div.results-view-options>button.btn.selected").click();
  await page.locator("BUTTON[type='button']").nth(16).click();
  await page.getByRole('link', { name: "Bulk Update All" }).click();
  await page.getByRole('heading', { name: "Bulk Update 215 Students" }).hover();
  await page.locator("div.form-group>label.control-label").hover();
  await page.locator("SELECT[id='SelectAttribute'][name='SelectAttribute']").selectOption("number:1000100");
  await page.locator("//LABEL[normalize-space() = \"Append\"]").click();
  await page.locator('input[type="radio"]').check();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Replace\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Replace*\"]//following-sibling::div").click();
  await page.waitForTimeout(2000);
  await page.keyboard.press("ArrowDown");
  await page.locator("//LABEL[normalize-space() = \"Replace*\"]").click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"New value*\"]").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.reload();
  await page.getByRole('button', { name: "Reset" }).click();
  await page.getByRole('button', { name: "Add Filter" }).click();
  await page.getByPlaceholder("Search filters").fill("Student Group");
  await page.getByRole('button', { name: "Student Group" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('heading', { name: "Students & Alumni" }).click();
  await page.reload();
  await page.getByRole('button', { name: "Add Filter" }).click();
  await page.getByPlaceholder("Search filters").fill("Student Group");
  await page.getByRole('button', { name: "Student Group" }).click();
  await page.locator("//LABEL[normalize-space() = \"Bulk Update 2\"]").click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('heading', { name: "Students & Alumni" }).click();
  await page.locator("BUTTON[type='button']").nth(16).click();
  await page.getByRole('link', { name: "Bulk Update All" }).click();
  await page.getByRole('heading', { name: "Bulk Update 215 Students" }).hover();
  await page.locator("div.form-group>label.control-label").hover();
  await page.locator("SELECT[id='SelectAttribute'][name='SelectAttribute']").selectOption("number:1000100");
  await page.locator("div.form-group>label.control-label").nth(2).hover();
  await page.locator("//LABEL[normalize-space() = \"Replace all values\"]").click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"New value*\"]").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.reload();
  await page.getByRole('button', { name: "Reset" }).click();
  await page.getByRole('button', { name: "Add Filter" }).click();
  await page.locator("li.ng-scope>span.filter-group.ng-binding").hover();
  await page.getByPlaceholder("Search filters").fill("Student Group");
  await page.getByRole('button', { name: "Student Group" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('heading', { name: "Students & Alumni" }).click();
});
