// TC: TC67639
// Custom Report - Create a custom outcome report with filters and columns and delete it

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Custom Report - Create a custom outcome report with filters and columns and delete it", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;
  const text = msg.text();
  const timestamp = new Date().toLocaleString();

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Reports" }).click();
  await page.getByRole('link', { name: "Custom Reports" }).click();
  await page.getByRole('heading', { name: "Custom Reports" }).hover();
  await page.locator("div.folder-nav.pull-left>tt-folder-structure.ng-binding").hover();
  await page.locator("div.ng-scope>div.no-results").hover();
  await page.getByRole('button', { name: "Create New Report" }).click();
  await page.locator("//li[normalize-space()=\"Employer & Contact Reports\"]").hover();
  await page.locator("//li[normalize-space()=\"Student Reports\"]").hover();
  await page.locator("//li[normalize-space()=\"Experiential Learning Reports\"]").hover();
  await page.locator("//li[normalize-space()=\"Outcome Reports\"]").hover();
  await page.locator("//li[normalize-space()=\"Job Posting Reports\"]").hover();
  await page.locator("//li[normalize-space()=\"Event Reports\"]").hover();
  await page.locator("//li[normalize-space()=\"Appointment Reports\"]").hover();
  await page.getByRole('link', { name: "Outcomes" }).click();
  await page.locator("//SPAN[normalize-space() = \"Offer Status\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Accepted\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Received\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Rejected\"]").hover();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//SPAN[normalize-space() = \"Offer Status\"]").click();
  await page.locator("//SPAN[normalize-space() = \"Outcome Type\"]").click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//SPAN[normalize-space() = \"Outcome Type\"]").click();
  await page.locator("//SPAN[normalize-space() = \"Job Phase\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Work Experience\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Post Graduation\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Internship\"]").hover();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//SPAN[normalize-space() = \"Job Phase\"]").click();
  await page.getByRole('button', { name: "Add Filter" }).click();
  await page.locator("li.ng-scope>span.filter-group.ng-binding").hover();
  await page.getByPlaceholder("Search filters").fill("Graduation term");
  await page.getByRole('button', { name: "Graduation Term" }).click();
  await page.getByPlaceholder("Search Graduation Term filter options").fill("Spring 2030");
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//SPAN[contains(normalize-space(),\"Graduation Term\")]").click();
  await page.locator("//div[normalize-space()=\"Employer\"]").dblclick();
  await page.locator("//div[normalize-space()=\"Job Title\"]").dblclick();
  await page.locator("//div[normalize-space()=\"Offer Accepted Date\"]").dblclick();
  await page.locator("//div[normalize-space()=\"Detailed Function\"]").dblclick();
  await page.locator("//div[normalize-space()=\"Detailed Industry\"]").dblclick();
  await page.locator("//div[normalize-space()=\"Base Salary\"]").dblclick();
  await page.locator("//div[contains(normalize-space(),\"Base Salary\")]//div[@class=\"view-option\"]").click();
  await page.getByRole('heading', { name: "Column Settings" }).hover();
  await page.getByRole('heading', { name: "Base Salary" }).hover();
  await page.getByRole('heading', { name: "Column Settings" }).click();
  await page.keyboard.press("Tab");
  await page.keyboard.press("Tab");
  await page.keyboard.press("Enter");
  await page.keyboard.press("ArrowDown");
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: "Ok" }).click();
  await expect(page.locator("//DIV[normalize-space() = \"Base Salary (per year)\"]")).toHaveText("Base Salary (per year) ");
  await page.locator("//div[normalize-space()=\"Job Source\"]").dblclick();
  await page.getByRole('button', { name: "Generate Report" }).click();
  await page.waitForTimeout(10000);
  await page.getByRole('link', { name: "Save Report" }).click();
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Name of Report").fill("Muuk Report");
  await page.getByPlaceholder("Add description here.").fill("Automated test case");
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: "Save Report" }).click();
  await page.getByRole('link', { name: "Custom Reports" }).click();
  await page.reload();
  await page.getByRole('link', { name: "Muuk Report" }).hover();
  await page.locator("td>span.ng-binding.ng-scope").hover();
  await page.getByRole('link', { name: "Muuk Report" }).click();
  await page.getByRole('heading', { name: "Custom Report: Muuk Report" }).hover();
  await page.getByRole('link', { name: "Back to List" }).click();
  await page.locator("BUTTON[type='button']").nth(4).click();
  await page.getByRole('link', { name: "Edit" }).hover();
  await page.getByRole('link', { name: "Move" }).hover();
  await page.getByRole('link', { name: "Duplicate" }).hover();
  await page.getByRole('link', { name: "Export" }).hover();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to delete report Muuk Report?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.locator("div.ng-scope>div.no-results").hover();
});
