// TC: TC_A77681
// Schedules - Templates - Add, edit, delete a schedule template

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Schedules - Templates - Add, edit, delete a schedule template", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Site Management" }).hover();
  await page.locator("div.side-nav-with-link-and-submenu-container>button.btn.btn-icon.sub-menu-icon").nth(7).click();
  await page.getByRole('link', { name: "Site Settings" }).click();
  await page.getByRole('link', { name: "Schedule Templates" }).click();
  await page.getByRole('heading', { name: "Schedules" }).hover();
  await page.locator("tr>th").hover();
  await page.locator("tr>th").nth(1).hover();
  await page.getByRole('button', { name: "Add Schedule Template" }).click();
  await page.getByRole('heading', { name: "Add Schedule Template" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Description\"]").hover();
  await page.getByPlaceholder("Schedule Template Name").fill("Muuk e2e Test Template");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Time*\"]").hover();
  await page.getByPlaceholder("Description").fill("Test");
  await page.getByPlaceholder("H:MMpm").fill("2:00pm");
  await page.getByPlaceholder("H:MMpm").fill("60000");
  await page.locator("//LABEL[normalize-space() = \"Add break (optional)\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Add break (optional)\"]/following-sibling::div//button").click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Break 1*\"]").hover();
  await page.locator("BUTTON[type='button']").nth(2).hover();
  await page.locator("BUTTON[type='button']").nth(3).hover();
  await page.getByPlaceholder("Schedules - Templates - Add, edit, delete a schedule template ").fill("2:15pm");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Break 1*\"]").click();
  await page.getByPlaceholder("Search").fill("2:30pm");
  await page.waitForTimeout(1000);
  await page.locator("//LABEL[normalize-space() = \"Duration of Slots (min)*\"]").click();
  await page.locator("INPUT[type='number']").fill("30");
  await page.locator("//LABEL[normalize-space() = \"Students Per Slot*\"]").hover();
  await page.locator("//label[normalize-space()=\"Students Per Slot*\"]/following::input").fill("2");
  await page.locator("//LABEL[normalize-space() = \"Students Per Slot*\"]").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: "Save" }).click();
  await page.locator("BUTTON[type='button']").nth(3).click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.getByRole('heading', { name: "Edit Schedule Template" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Schedule Template Name*\"]").hover();
  await page.getByPlaceholder("Schedule Template Name").fill("Muuk e2e Test Template - Renamed");
  await page.getByPlaceholder("Description").fill("Test - Edit");
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.locator("//td[normalize-space()=\"Muuk e2e Test Template - Renamed\"]").hover();
  await page.locator("//td[normalize-space()=\"Test - Edit\"]").hover();
  await page.getByRole('link', { name: "Events" }).click();
  await page.getByRole('link', { name: "Host a Job Fair" }).click();
  await page.getByRole('heading', { name: "Scheduling" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Enable Schedules\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Enable Schedules\"]//following::LABEL[normalize-space() = \"Yes\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Select the schedule templates available to employers*\"]").hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Muuk e2e Test Template - Renamed\"]").click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Select the schedule templates available to employers*\"]").click();
  await page.getByRole('button', { name: "Cancel" }).click();
  await page.locator("div.side-nav-with-link-and-submenu-container>button.btn.btn-icon.sub-menu-icon").nth(7).click();
  await page.getByRole('link', { name: "Site Settings" }).click();
  await page.getByRole('link', { name: "Schedule Templates" }).click();
  await page.locator("//td[normalize-space()=\"Muuk e2e Test Template - Renamed\"]").hover();
  await page.locator("BUTTON[type='button']").nth(3).click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete Schedule Template" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to permanently delete this schedule template?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Schedule Template" }).click();
  await page.waitForTimeout(2000);
  await page.getByRole('link', { name: "Events" }).click();
  await page.getByRole('link', { name: "Host a Job Fair" }).click();
  await page.getByRole('heading', { name: "Scheduling" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Enable Schedules\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Enable Schedules\"]//following::LABEL[normalize-space() = \"Yes\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Select the schedule templates available to employers*\"]").hover();
  await page.locator("button.multiselect.dropdown-toggle.btn.btn-small>b.caret").nth(2).click();
});
