// TC: TC_A77432
// Communities - Admin can create, update community, student can view and comment

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Communities - Admin can create, update community, student can view and comment", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Communities" }).click();
  await page.getByPlaceholder("Search by Name").hover();
  await page.getByRole('button', { name: "Add New Community" }).hover();
  await page.getByPlaceholder("Search by Name").fill("Muuktest Community");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('button', { name: "Reset Filters" }).hover();
  await page.locator("//SPAN[normalize-space() = \"Type - Public\"]").hover();
  await page.locator("//i[@class=\"fa fa-users\"]//following::SPAN[normalize-space() = \"2\"]").hover();
  await page.getByRole('link', { name: "Muuktest Community - Edit name" }).click();
  await page.getByRole('link', { name: "Home" }).click();
  await page.getByRole('link', { name: "Members (2)" }).click();
  await page.getByRole('heading', { name: "Members (2)" }).hover();
  await page.getByRole('link', { name: "Home" }).click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.waitForTimeout(2000);
  await page.locator("div.entity-detail-header-cmp.with-hero-image.default-hero-image>div.header").click();
  await page.getByRole('heading', { name: "Muuktest Community - Edit name" }).hover();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.keyboard.press("Backspace");
  await page.keyboard.press("Backspace");
  await page.keyboard.press("Backspace");
  await page.keyboard.press("Backspace");
  await page.keyboard.press("Backspace");
  await page.keyboard.press("Backspace");
  await page.keyboard.press("Backspace");
  await page.keyboard.press("Backspace");
  await page.keyboard.press("Backspace");
  await page.keyboard.press("Backspace");
  await page.locator("div.entity-detail-header-cmp.with-hero-image.default-hero-image>div.header").click();
  await page.getByRole('heading', { name: "Description" }).hover();
  await page.locator("//div[normalize-space() = \"This is a test for e2e Tests\"]").hover();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: "Edit" }).click();
  await page.getByRole('heading', { name: "Edit Community Description" }).hover();
  await page.locator("div.modal-body>div.form-group").click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: "Save" }).click();
  await page.locator("//P[normalize-space() = \"This is a test for e2e Tests - Edit\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Description updated successfully!\"]").hover();
  await page.getByRole('button', { name: "Edit" }).click();
  await page.getByRole('heading', { name: "Edit Community Description" }).hover();
  await page.locator("div.modal-body>div.form-group").click();
  await page.waitForTimeout(1000);
  await page.keyboard.press("Backspace");
  await page.keyboard.press("Backspace");
  await page.keyboard.press("Backspace");
  await page.keyboard.press("Backspace");
  await page.keyboard.press("Backspace");
  await page.keyboard.press("Backspace");
  await page.getByRole('link', { name: "Save" }).click();
  await page.locator("//SPAN[normalize-space() = \"Description updated successfully!\"]").hover();
  await page.locator("//div[normalize-space() = \"This is a test for e2e Tests\"]").hover();
  await page.getByRole('button', { name: "Edit" }).click();
  await page.getByRole('link', { name: "Add Leader(s)" }).click();
  await page.getByPlaceholder("Student").click();
  await page.getByPlaceholder("Student").click();
  await page.waitForTimeout(1000);
  await page.keyboard.press("ArrowDown");
  await page.getByRole('link', { name: "Add Leader(s)" }).click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.waitForLoadState('load');
  await page.locator("//SPAN[normalize-space() = \"Alexa Kane\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Community leaders updated.\"]").hover();
  await page.getByRole('button', { name: "Edit" }).click();
  await page.locator("a.ng-scope>i.glyphicon.glyphicon-remove").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.locator("//SPAN[normalize-space() = \"Community leaders updated.\"]").hover();
  await page.reload();
  await page.getByRole('link', { name: "Members (3)" }).click();
  await page.locator("//SPAN[normalize-space() = \"Alexa Kane\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Alexa Kane\"]/following::button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Send Email" }).hover();
  await page.getByRole('link', { name: "Remove Member" }).click();
  await page.locator("//SPAN[normalize-space() = \"Member removed successfully.\"]").hover();
  await page.locator("div.uploaded-image-cmp>img.uploaded-image.ng-scope.ng-isolate-scope").hover();
  await page.locator("//SPAN[normalize-space() = \"Change Image\"]").click();
  await page.getByRole('heading', { name: "Select an Image" }).hover();
  await page.getByRole('heading', { name: "Drag an image here" }).hover();
  await page.locator("//SPAN[normalize-space() = \"Image Requirements\"]").hover();
  fileName = MK.onSetGV(`logomuuk.jpg`, null);
  var fileInput = await page.$("INPUT[type='file']");
  var filePath ="./test/"+fileName;
  if(fileInput){
  await fileInput.setInputFiles(filePath);
  }
  else{
  throw new Error('Element to upload file is not present.');
  }
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "OK" }).click();
  await page.locator("div.uploaded-image-cmp>img.uploaded-image.ng-scope.ng-isolate-scope").hover();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Enable new post notifications" }).click();
  await page.locator("//SPAN[normalize-space() = \"Notification option updated.\"]").hover();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Disable new post notifications" }).click();
  await page.locator("//SPAN[normalize-space() = \"Notification option updated.\"]").hover();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Enable notifications for discussions I join" }).click();
  await page.locator("//SPAN[normalize-space() = \"Notification option updated.\"]").hover();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Disable notifications for discussions I join" }).click();
  await page.locator("//SPAN[normalize-space() = \"Notification option updated.\"]").hover();
  await page.getByRole('link', { name: "Home" }).click();
  await page.getByRole('button', { name: "Hi e2e! What’s on your mind?" }).click();
  await page.locator("SPAN[id='cke_1_top'][role='presentation']").click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: "Post" }).click();
  await page.locator("//SPAN[normalize-space() = \"Like\"]").click();
  await page.reload();
  await page.locator("//SPAN[normalize-space() = \"1\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Unlike\"]").hover();
  await page.locator("//DIV[normalize-space() = \"0 comments\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Comment\"]").click();
  await page.locator("//span[normalize-space()=\"Discussion Feed\"]//ancestor::div[@class=\"modal-content\"]//div[contains(@id,\"new-comment-content\")]").click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: "Comment" }).click();
  await page.locator("//SPAN[normalize-space() = \"×\"]").nth(1).click();
  await page.getByRole('link', { name: "Members (2)" }).click();
  await page.locator("//TBODY//SPAN[normalize-space() = \"Alexis Kramer\"]").click();
  await page.getByRole('link', { name: "Home" }).click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Login As" }).click();
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('e2e-tests-campuswide.qa-12twenty.com/on-login?returnUrl=%2Fdashboard');
  await page.getByRole('link', { name: "Communities" }).click();
  await page.getByRole('link', { name: "Muuktest Community - Edit name" }).click();
  await page.getByRole('link', { name: "Home" }).click();
  await page.locator("//SPAN[normalize-space() = \"2\"]").nth(1).hover();
  await page.locator("//SPAN[normalize-space() = \"Type: Public\"]").nth(1).hover();
  await page.locator("//SPAN[normalize-space() = \"JOINED\"]").nth(1).hover();
  await page.locator("//SPAN[normalize-space() = \"Like\"]").click();
  await page.locator("//SPAN[normalize-space() = \"Unlike\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"2\"]").nth(2).hover();
  await page.locator("//SPAN[normalize-space() = \"Comment\"]").click();
  await page.locator("//span[normalize-space()=\"Discussion Feed\"]//ancestor::div[@class=\"modal-content\"]//div[contains(@id,\"new-comment-content\")]").click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: "Comment" }).click();
  await page.locator("//SPAN[normalize-space() = \"Comment saved successfully\"]").hover();
  await page.locator("//DIV[normalize-space() = \"Test comment\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Like\"]").click();
  await page.locator("//SPAN[normalize-space() = \"×\"]").nth(1).click();
  await page.reload();
  await page.locator("//DIV[normalize-space() = \"2 comments\"]").click();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForTimeout(2000);
  await page.reload();
  await page.getByRole('link', { name: "Communities" }).click();
  await page.getByRole('link', { name: "Muuktest Community - Edit name" }).click();
  await page.getByRole('link', { name: "Home" }).click();
  await page.locator("div.community-activity.ng-scope>div.tt-card").hover();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Edit" }).hover();
  await page.locator("//SPAN[normalize-space() = \"Turn off notifications for this post\"]").hover();
  await page.getByRole('link', { name: "Delete" }).click();
});
