// TC: TC63509
// Contacts - Activity Stream - Add&#x2F;Delete Note&#x2F;Meeting

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Contacts - Activity Stream - Add&#x2F;Delete Note&#x2F;Meeting", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Contacts" }).click();
  await page.getByPlaceholder("Contact Name or Email Address").fill("Test Contact 01-001");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.locator("ng-transclude>span.primary-item-text.ng-binding.ng-scope").click();
  await page.getByRole('heading', { name: "Test Contact 1-1" }).hover();
  await page.getByRole('link', { name: "Profile" }).hover();
  await page.getByRole('link', { name: "Activities" }).hover();
  await page.getByRole('link', { name: "Notes" }).hover();
  await page.getByRole('link', { name: "Emails" }).hover();
  await page.getByRole('link', { name: "Events" }).hover();
  await page.getByRole('link', { name: "OCI and Job Listings" }).hover();
  await page.getByRole('link', { name: "Experiences" }).hover();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").click();
  await page.getByRole('link', { name: "Account Settings" }).hover();
  await page.getByRole('link', { name: "Log Out" }).hover();
  await page.getByRole('link', { name: "Log Out" }).click();
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('e2e-tests-campuswide.qa-12twenty.com/');
  await page.waitForLoadState('load');
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.student.fullaccess@campuswide.com");
  await page.getByPlaceholder("Password").fill("BoH5dORH7xg%");
  await page.getByRole('button', { name: "Student/Alumni Log In" }).click();
  await page.waitForTimeout(1000);
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Contacts" }).click();
  await page.getByPlaceholder("Contact Name or Email Address").fill("Test Contact 01-001");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.locator("ng-transclude>span.primary-item-text.ng-binding.ng-scope").click();
  await page.getByRole('heading', { name: "Test Contact 1-1" }).hover();
  await page.locator("//SPAN[@title='When auto-sync is enabled, employer user account updates will automatically carry over to this contact profile.'][normalize-space() = \"AutoSync Enabled\"]").hover();
  await page.locator('input[type="checkbox"]').hover();
  await page.getByRole('link', { name: "Activities" }).click();
  await page.waitForLoadState('load');
  var activity = await page.locator('//SPAN[contains(text(),"Student/Contact Meeting")]');
  if (await activity.count() > 0){
  snippetLog("Deleting activity. . .");
  await page.getByRole('link', { name: "javascript:void(0)" }).click();
  await page.getByRole('heading', { name: "Delete Activity" }).hover();
  await page.locator("div.modal-content>div.modal-body").nth(2).hover();
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Confirm" }).click();
  await page.getByRole('heading', { name: "Success" }).hover();
  await page.locator("div.modal-content>div.modal-body").nth(1).hover();
  await page.getByRole('link', { name: "OK" }).click();
  }
  await page.waitForTimeout(2000);
  await page.getByRole('link', { name: "Profile" }).click();
  await page.getByRole('link', { name: "Activities" }).click();
  await page.waitForLoadState('load');
  var note = await page.locator('//P[normalize-space() = "Add quick, detailed notes to organize your thoughts, document ideas, or provide context for tasks, events, and projects efficiently."]');
  if (await note.count() > 0){
  snippetLog("Deleting note. . .");
  await page.getByRole('link', { name: "javascript:void(0)" }).click();
  await page.getByRole('heading', { name: "Delete Note" }).hover();
  await page.locator("div.modal-content>div.modal-body").nth(2).hover();
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Confirm" }).click();
  await page.waitForTimeout(5000);
  await page.getByRole('heading', { name: "Success" }).hover();
  await page.locator("//DIV[normalize-space() = \"You have successfully deleted the note.\"]").hover();
  await page.getByRole('link', { name: "OK" }).click();
  }
  await page.getByRole('link', { name: "Profile" }).click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Add Note" }).click();
  await page.getByRole('heading', { name: "Add Note" }).hover();
  await page.locator("//DIV[normalize-space() = \"Contact: Test Contact 01-001\"]").hover();
  await page.locator("div.form-group>label.control-label").hover();
  await page.waitForTimeout(1000);
  await page.locator("html").click();
  textContent = MK.onSetGV(`Add quick, detailed notes to organize your thoughts, document ideas, or provide context for tasks, events, and projects efficiently.`, null);
  await page.waitForTimeout(1000);
  page.keyboard.type(textContent);
  await page.locator("html").hover();
  await page.locator("SELECT[id='UTypeId'][name='TypeId']").selectOption("number:3809");
  await page.locator("//LABEL[normalize-space() = \"Note Date * *Required. *Date must be in the past. *Invalid. Please enter a date between 1900 and 2078.\"]").hover();
  await page.locator("div.form-group>label.control-label").nth(3).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Add" }).click();
  await page.getByRole('link', { name: "Notes" }).click();
  await page.waitForTimeout(2000);
  await page.waitForTimeout(2000);
  await page.reload();
  await page.waitForTimeout(2000);
  await page.locator("//P[normalize-space() = \"Add quick, detailed notes to organize your thoughts, document ideas, or provide context for tasks, events, and projects efficiently.\"]").hover();
  await page.locator("tr.ng-scope>td.ng-binding.ng-scope").hover();
  await page.locator("tr.ng-scope>td.ng-binding.ng-scope").nth(1).hover();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Add Note" }).hover();
  await page.getByRole('link', { name: "New Task" }).hover();
  await page.getByRole('link', { name: "New Meeting" }).hover();
  await page.getByRole('link', { name: "New Meeting" }).click();
  await page.getByRole('heading', { name: "Add Meeting" }).hover();
  await page.getByPlaceholder("Add title here").fill("Student/Contact Meeting");
  await page.locator("div.form-group>label.control-label").nth(1).click();
  await page.locator("div.form-group>label.control-label").nth(2).click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.locator("div.form-group>label.control-label").nth(3).click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.locator("div.form-group>label.control-label").nth(4).click();
  await page.getByPlaceholder("Add description here").hover();
  await page.getByPlaceholder("Add description here").fill("Meeting to consult data");
  await page.locator("div.form-group>label.control-label").nth(5).click();
  await page.getByPlaceholder("Add comments here").fill("Testing creation of meeting");
  await page.locator("div.form-group>label").nth(6).click();
  await page.getByPlaceholder("Search Contacts").hover();
  await page.locator("div.attrVals>label").hover();
  await page.locator("div.attrVals>label").nth(1).hover();
  await page.locator("div.attrVals>label").nth(2).hover();
  await page.locator("div.attrVals>label").nth(3).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.getByRole('link', { name: "Activities" }).click();
  await page.locator("span>span.title.ng-binding.ng-scope").hover();
  await page.locator("div.ng-scope>span.text-area-display.ng-binding").hover();
  await page.locator("div.creatorName>span.ng-binding").nth(1).hover();
  await page.locator("//DIV[normalize-space() = \"Contact: Test Contact 01-001\"]").nth(1).hover();
  await page.waitForTimeout(10000);
  await page.getByRole('link', { name: "Activities" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "javascript:void(0)" }).click();
  await page.getByRole('heading', { name: "Delete Activity" }).hover();
  await page.locator("div.modal-content>div.modal-body").nth(2).hover();
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Confirm" }).click();
  await page.getByRole('heading', { name: "Success" }).hover();
  await page.locator("div.modal-content>div.modal-body").nth(1).hover();
  await page.getByRole('link', { name: "OK" }).click();
  await page.waitForTimeout(2000);
  await page.getByRole('link', { name: "Profile" }).click();
  await page.waitForTimeout(4000);
  selector = MK.onSetGV(`//SPAN[contains(text(),"Student/Contact Meeting")]`, null);
  var isElementPresent = await page.locator(selector).count() > 0;
  if (!isElementPresent) {
  snippetLog('Element is not present.');
  } else {
  throw new Error('Element is present');
  }
  await page.getByRole('link', { name: "Activities" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "javascript:void(0)" }).click();
  await page.getByRole('heading', { name: "Delete Note" }).hover();
  await page.locator("div.modal-content>div.modal-body").nth(2).hover();
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Confirm" }).click();
  await page.waitForTimeout(5000);
  await page.getByRole('heading', { name: "Success" }).hover();
  await page.locator("//DIV[normalize-space() = \"You have successfully deleted the note.\"]").hover();
  await page.getByRole('link', { name: "OK" }).click();
  await page.waitForTimeout(5000);
  await page.waitForLoadState('load');
  await page.reload();
  await page.waitForTimeout(5000);
  selector = MK.onSetGV(`//P[normalize-space() = "Add quick, detailed notes to organize your thoughts, document ideas, or provide context for tasks, events, and projects efficiently."]`, null);
  var isElementPresent = await page.locator(selector).count() > 0;
  if (!isElementPresent) {
  snippetLog('Element is not present.');
  } else {
  throw new Error('Element is present');
  }
  await page.locator('input[type="checkbox"]').click();
  await page.locator('input[type="checkbox"]').hover();
  await page.reload();
  await page.locator("div.activity-stream.clearfix>div.gray-text.no-items.ng-scope").hover();
});
