// TC: TC66112
// 12TE Events - Employer user adds a multi-school event to multiple schools

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("12TE Events - Employer user adds a multi-school event to multiple schools", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;
  const text = msg.text();
  const timestamp = new Date().toLocaleString();

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(employerQA, { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Email Address").fill("e2e.employeruser.subscription.admin@walmart.com");
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.waitForTimeout(2000);
  await page.locator("button.btn.btn-school.submit-login-form>span").click();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").hover();
  await page.getByRole('link', { name: "Events" }).click();
  await page.getByRole('heading', { name: "Events" }).hover();
  await page.getByRole('link', { name: "Host an Event" }).click();
  await page.getByRole('heading', { name: "Business" }).hover();
  await page.getByRole('heading', { name: "Business" }).click();
  await page.getByRole('heading', { name: "Law" }).click();
  await page.getByRole('heading', { name: "Specialized Business Masters" }).click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Continue" }).click();
  await page.locator("//DIV[normalize-space() = \"Students & Alumni from non-12twenty schools\"]").click();
  await page.locator("div.school-info>div.school-name.ng-binding").nth(3).click();
  await page.locator("div.school-info>div.school-name.ng-binding").nth(7).click();
  await page.locator("div.school-info>div.school-name.ng-binding").nth(11).click();
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Back" }).hover();
  await page.getByRole('link', { name: "Continue" }).click();
  await page.getByRole('heading', { name: "General" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Event Name*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Event Type*\"]").click();
  await page.locator("SELECT[id='CoreEventTypeId'][name='CoreEventTypeId']").click();
  await page.keyboard.press("ArrowDown");
  await page.locator("div.form-group>label.control-label").nth(1).hover();
  await page.locator("SELECT[name='FormatId']").click();
  await page.keyboard.press("ArrowDown");
  await page.locator("div.form-group>label.control-label").nth(2).hover();
  await page.getByRole('heading', { name: "Event Dates" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Time Zone*\"]").hover();
  await page.getByPlaceholder("Event Name").fill("Muuk Event Multiple Schools");
  await page.locator("//LABEL[normalize-space() = \"Event Format*\"]").hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.getByPlaceholder("Search").fill("Chennai");
  await page.locator("//LABEL[normalize-space() = \"Chennai, Kolkata, Mumbai, New Delhi (UTC+05:30)\"]").click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Event Date and Time*\"]").hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("div.xGj8Mb>div.wDYxhc").nth(5).click();
  await page.getByPlaceholder("H:MMpm").fill("12:00pm");
  await page.getByPlaceholder("H:MMpm").fill("11:30pm");
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").fill("12:00am");
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.getByPlaceholder("H:MMpm").fill("11:00am");
  await page.locator("div.form-group>label.control-label").nth(6).click();
  await page.getByRole('button', { name: "-- Please Select a Work Authorization --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Description*\"]").click();
  await page.locator("html").click();
  await page.getByPlaceholder("Additional Candidate Requirements").fill("60000");
  await page.getByRole('heading', { name: "Primary Event Contact" }).click();
  await page.locator("//LABEL[normalize-space() = \"Name*\"]").click();
  await page.getByPlaceholder("Name").fill("John");
  await page.locator("//LABEL[normalize-space() = \"Phone*\"]").click();
  await page.getByPlaceholder("Phone").fill("8456321478");
  await page.locator("//LABEL[normalize-space() = \"Email*\"]").click();
  await page.getByPlaceholder("Email").click();
  await page.getByPlaceholder("Email").fill("john@yopmail.com");
  await page.getByRole('heading', { name: "Registration Document(s)" }).hover();
  await page.locator("tr>th").hover();
  await page.locator("tr>th").nth(1).hover();
  await page.locator("tr>th").nth(2).hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("div.xGj8Mb>div.wDYxhc").nth(5).click();
  await page.getByRole('link', { name: "Continue" }).click();
  await page.getByRole('heading', { name: "Event Details" }).hover();
  await page.locator("dl.dl-horizontal>dd.ng-binding").hover();
  await page.locator("dl.dl-horizontal>dd").nth(1).hover();
  await page.getByRole('button', { name: "Submit" }).click();
  await page.getByRole('heading', { name: "Success!" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByRole('heading', { name: "Muuk Event Multiple Schools" }).hover();
  await page.locator("div.sub-header>span.badge.missing-information.ng-scope").hover();
  await page.locator("div.school-info>div.school-name.ng-binding").hover();
  await page.locator("div.school-info>div.school-name.ng-binding").nth(1).hover();
  await page.locator("div.school-info>div.school-name.ng-binding").nth(2).hover();
  await page.locator("//DIV[normalize-space() = \"Students & Alumni from non-12twenty schools\"]").hover();
  await page.getByRole('link', { name: "Events" }).click();
  await page.locator("a.primary-item.primary-item-with-icons>span.primary-item-text.ng-binding").nth(1).hover();
  await expect(page.locator("td.center>span.badge.ng-binding").nth(1)).toHaveText("Active");
  await page.locator("a.primary-item.primary-item-with-icons>span.primary-item-text.ng-binding").nth(1).click();
  await page.waitForLoadState('load');
  await page.getByRole('button', { name: "Action" }).click();
  await page.getByRole('link', { name: "Edit Event" }).hover();
  await page.getByRole('link', { name: "Duplicate Event" }).hover();
  await page.getByRole('link', { name: "Cancel Event" }).hover();
  await page.getByRole('link', { name: "Cancel Event" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByRole('link', { name: "Events" }).click();
  await page.locator("a.primary-item.primary-item-with-icons>span.primary-item-text.ng-binding").nth(6).hover();
  await expect(page.locator("td.center>span.badge.ng-binding").nth(1)).toHaveText("Canceled");
  await page.getByRole('link', { name: "Events" }).click();
  await page.getByRole('link', { name: "Upcoming" }).click();
  selector = MK.onSetGV(`//SPAN[contains(text(),"Muuk Event Multiple Schools")]//ancestor::tr//td//span[contains(text(),"Active")]`, null);
  var isElementPresent = await page.locator(selector).count() > 0;
  if (!isElementPresent) {
  snippetLog('Element is not present.');
  } else {
  throw new Error('Element is present');
  }
});
