// TC: TC61991
// IN PROGRESS--Events - Host a Job Fair, Approving Employer Registration, and Processing Payment - Admin

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("IN PROGRESS--Events - Host a Job Fair, Approving Employer Registration, and Processing Payment - Admin", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;
  const text = msg.text();
  const timestamp = new Date().toLocaleString();

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto('https://e2e-tests-campuswide.admin.qa-12twenty.com/dashboard', { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: "Events" }).click();
  await page.getByRole('heading', { name: "Events" }).hover();
  await page.getByRole('link', { name: "Host a Job Fair" }).click();
  await page.getByRole('heading', { name: "Host a Job Fair" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Enable Schedules\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").click();
  await page.locator("//H2[normalize-space()=\"Additional Registration Method\"]//following::LABEL[normalize-space() = \"Yes\"]").click();
  await page.locator("//SPAN[normalize-space() = \"To create/manage your schedule templates, please visit the templates management page.\"]").click();
  await page.getByRole('link', { name: "templates management page" }).click();
  await page.waitForTimeout(2000);
  urlpage1 = page.url();
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForTimeout(2000);
  await page.waitForLoadState('load');
  await page.getByRole('button', { name: "Add Schedule Template" }).click();
  await page.getByRole('heading', { name: "Add Schedule Template" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Schedule Template Name*\"]").click();
  await page.getByPlaceholder("Schedule Template Name").fill("template01");
  await page.getByPlaceholder("Description").fill("Testing templates");
  await page.getByPlaceholder("H:MMpm").fill("12:00am");
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Enter');
  await page.getByPlaceholder("H:MMpm").fill("5:15pm");
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Enter');
  await page.locator("div.form-group.ng-scope>label.control-label").nth(2).click();
  await page.locator("div.form-group.ng-scope>label.control-label.ng-binding").nth(2).click();
  await page.locator("INPUT[type='number']").fill("3");
  await page.locator("div.form-group.ng-scope>label.control-label").nth(4).click();
  await page.locator("div.form-group.ng-scope>label.control-label.ng-binding").nth(3).click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: "Save" }).click();
  await page.locator("tr.ng-scope>td.ng-binding").nth(2).hover();
  await page.locator("tr.ng-scope>td.ng-binding").nth(3).hover();
  await page.waitForTimeout(2000);
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForTimeout(2000);
  await page.getByRole('heading', { name: "Host a Job Fair" }).click();
  await page.waitForLoadState('load');
  await page.reload();
  await page.waitForTimeout(2000);
  await page.locator("//LABEL[normalize-space() = \"Enable Schedules\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").click();
  await page.getByPlaceholder("Event Name").fill("Test Job Fair");
  await page.locator("//LABEL[normalize-space() = \"Event Type*\"]").click();
  await page.locator("SELECT[id='EventTypeId'][name='EventTypeId']").selectOption("number:1499993124749");
  await page.locator("//LABEL[normalize-space() = \"Event Format\"]").click();
  await page.locator("SELECT[id='EventFormatId'][name='EventFormatId']").selectOption("number:1");
  await page.locator("//LABEL[normalize-space() = \"Location*\"]").click();
  await page.getByPlaceholder("Event Location").fill("Hyderabad");
  await page.getByPlaceholder("Briefly describe who this event is meant for").fill("Target Audience");
  await page.locator("SELECT[name='DressAttireId']").selectOption("number:4");
  await page.locator("//LABEL[normalize-space() = \"Work Authorization Requirement*\"]").click();
  await page.getByRole('button', { name: "-- Work Authorization Requirement --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('heading', { name: "Event Dates" }).click();
  await page.locator("div.form-group.ng-isolate-scope>label.control-label").click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").fill("12:00am");
  await page.getByPlaceholder("H:MMpm").fill("11:00pm");
  await page.locator("div.form-group>label.control-label").nth(12).click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.active.day").click();
  await page.getByPlaceholder("H:MMpm").fill("12:00am");
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.active.day").click();
  await page.getByPlaceholder("H:MMpm").fill("10:00pm");
  await page.locator("div.form-group>label.control-label").nth(13).click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.active.day").click();
  await page.getByPlaceholder("H:MMpm").fill("12:00am");
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.active.day").click();
  await page.getByPlaceholder("H:MMpm").fill("10:00pm");
  await page.locator("//LABEL[normalize-space() = \"Student Publish Date *\"]").click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").fill("12:00am");
  await page.getByRole('heading', { name: "Scheduling" }).click();
  await page.locator("//LABEL[normalize-space() = \"Select the schedule templates available to employers*\"]/following::button").click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('heading', { name: "Additional Registration Method" }).click();
  await page.getByRole('heading', { name: "Event Description" }).click();
  await page.locator("div.form-group>label.control-label").nth(19).click();
  await page.getByPlaceholder("Other Information").fill("Other information testing");
  await page.getByRole('heading', { name: "Attachments" }).click();
  fileName = MK.onSetGV(`Test_Resume_01.pdf`, null);
  var fileInput = await page.$("INPUT[type='file']");
  var filePath ="./test/"+fileName;
  if(fileInput){
  await fileInput.setInputFiles(filePath);
  }
  else{
  throw new Error('Element to upload file is not present.');
  }
  await page.getByRole('heading', { name: "Registration Document(s)" }).click();
  await page.getByRole('link', { name: "Add Document Type" }).click();
  await page.locator("SELECT[name='CoreApplicationDocumentTypeId']").selectOption("number:1");
  await page.getByRole('heading', { name: "Eligibility" }).click();
  await page.locator("//LABEL[normalize-space() = \"Student Group*\"]").click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.ng-scope>label.control-label.ng-binding").nth(4).click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.ng-scope>label.control-label.ng-binding").nth(5).click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.ng-scope>label.control-label.ng-binding").nth(6).click();
  await page.getByRole('heading', { name: "Primary Event Contact" }).click();
  await page.locator("//LABEL[normalize-space() = \"Contact Name\"]").click();
  await page.getByPlaceholder("Contact Name").fill("e2e Test Admin");
  await page.locator("//LABEL[normalize-space() = \"Contact Email\"]").click();
  await page.getByPlaceholder("Contact Email").fill("e2etestadmin@test.com");
  await page.locator("//LABEL[normalize-space() = \"Contact Phone\"]").click();
  await page.getByPlaceholder("Contact Phone").fill("7660072137");
  await page.getByRole('heading', { name: "Payment Method" }).hover();
  await page.locator("//SPAN[normalize-space() = \"Please select a payment method for employer registrations. To update or add a new payment method, navigate to the Payments site setting page.\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Payment Method*\"]").click();
  await page.locator("SELECT[id='input-58pe6-select'][name='']").selectOption("number:145");
  await page.locator("//SPAN[normalize-space() = \"Default Payment Method\"]").hover();
  await page.getByRole('heading', { name: "Admin" }).click();
  await page.locator("//LABEL[normalize-space() = \"Event Source\"]").click();
  await page.locator("SELECT[id='SourceId'][name='SourceId']").selectOption("number:1030070311959");
  await page.locator("//LABEL[normalize-space() = \"Employer Registrants Visibility\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Allow employers to view student registrants\"]").click();
  await page.locator("label.control-label>span.ng-binding").click();
  await page.locator("div.form-group.ng-isolate-scope>label.control-label").click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.getByPlaceholder("H:MMpm").fill("12:00am");
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: "Save" }).click();
  await page.waitForTimeout(2000);
  await page.getByRole('heading', { name: "Muuktest Job Fair" }).hover();
});
