// TC: TC67031
// Events - Job Fairs - Admin create and edit job fair, launch kiosk and checks student in, deletes event

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Events - Job Fairs - Admin create and edit job fair, launch kiosk and checks student in, deletes event", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;
  const text = msg.text();
  const timestamp = new Date().toLocaleString();

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Events" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Events" }).hover();
  await page.getByRole('link', { name: "Host a Job Fair" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Host a Job Fair" }).hover();
  await page.getByRole('heading', { name: "General Info" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Event Name*\"]").click();
  await page.getByPlaceholder("Event Name").fill("E2E Test Job Fair");
  await page.locator("//LABEL[normalize-space() = \"Event Type*\"]").click();
  await page.locator("SELECT[id='EventTypeId'][name='EventTypeId']").selectOption("number:1499993124749");
  await page.locator("//LABEL[normalize-space() = \"Event Format\"]").click();
  await page.locator("SELECT[name='EventFormatId']").selectOption("number:3");
  await page.locator("//DIV[normalize-space() = \"You will be able to add a virtual meeting URL on the following page\"]").nth(2).hover();
  await page.locator("//LABEL[normalize-space() = \"Location*\"]").click();
  await page.getByPlaceholder("Location").click();
  await page.locator("//LABEL[normalize-space() = \"Target Audience\"]").click();
  await page.getByPlaceholder("Briefly describe who this event is meant for").fill("Casual");
  await page.locator("//LABEL[normalize-space() = \"Dress Attire*\"]").click();
  await page.locator("SELECT[name='DressAttireId']").selectOption("number:3");
  await page.locator("form.tt-form.form-horizontal>section").click();
  await page.getByPlaceholder("Briefly describe who this event is meant for").fill("Target Audience");
  await page.locator("//LABEL[normalize-space() = \"Work Authorization Requirement*\"]").click();
  await page.getByRole('button', { name: "-- Work Authorization Requirement --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('heading', { name: "Event Dates" }).click();
  await page.locator("//LABEL[normalize-space() = \"Time Zone*\"]").click();
  await page.getByRole('button', { name: "Guadalajara, Mexico City, Monterrey (UTC-06:00)" }).click();
  await page.locator("div.form-group.ng-isolate-scope>label.control-label").click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td").nth(4).click();
  await page.getByPlaceholder("H:MMpm").fill("2:05pm");
  await page.waitForTimeout(1000);
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td").nth(78).click();
  await page.waitForTimeout(1000);
  await page.getByPlaceholder("H:MMpm").fill("3:45pm");
  var today = new Date();
  var formattedDate = ("0" + (today.getMonth() + 1)).slice(-2) + '/' +
  ("0" + today.getDate()).slice(-2) + '/' +
  today.getFullYear();
  date = formattedDate;
  await page.locator("div.form-group>label.control-label").nth(9).click();
  await page.getByPlaceholder("MM/DD/YYYY").fill("` + date + `");
  await page.getByPlaceholder("H:MMpm").fill("12:05am");
  await page.getByPlaceholder("MM/DD/YYYY").fill("` + date + `");
  await page.locator("INPUT[id='searchInput'][name='search'][type='search']").fill("11:55pm");
  await page.getByPlaceholder("MM/DD/YYYY").fill("` + date + `");
  await page.locator("INPUT[type='search'][title='Search Wikipedia'][name='search'][id='ooui-php-1'][role='combobox']").fill("12:05am");
  await page.getByPlaceholder("BUSCAR").fill("` + date + `");
  await page.getByPlaceholder("Busca licenciatura, maestría, doctorado, curso, etc").fill("11:55pm");
  await page.locator("INPUT[type='TEXT'][name='login']").fill("` + date + `");
  await page.locator("INPUT[type='text'][name='txt_Key_Captcha'][id='txt_Key_Captcha']").fill("12:05am");
  await page.getByRole('heading', { name: "Scheduling" }).click();
  await page.locator("//LABEL[normalize-space() = \"No\"]").click();
  await page.getByRole('heading', { name: "Additional Registration Method" }).click();
  await page.locator("div.form-section-header>span.form-section-header-help-text").hover();
  await page.locator("div.form-group>label.control-label").nth(16).hover();
  await page.locator("//LABEL[contains(text(),\"Register via Ot\")]//following::LABEL[normalize-space() = \"Yes\"]").click();
  await page.getByPlaceholder("Additional Registration Instructions").fill("Additional Registration Instructions");
  await page.getByRole('heading', { name: "Event Description" }).click();
  await page.locator("body.cke_editable.cke_editable_themed.cke_contents_ltr.cke_show_borders>p").click();
  await page.getByPlaceholder("Other Information").fill("60000");
  await page.getByRole('heading', { name: "Attachments" }).click();
  await page.getByRole('heading', { name: "Registration Document(s)" }).hover();
  await page.getByRole('heading', { name: "Eligibility" }).hover();
  await page.locator("div.form-section-header>div.form-section-header-help-text").hover();
  await page.locator("//LABEL[normalize-space() = \"Student Group*\"]").click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.ng-scope>label.control-label.ng-binding").nth(2).click();
  await page.getByRole('heading', { name: "Payment Method" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Payment Method*\"]").click();
  await page.locator("//h2[normalize-space()=\"Payment Method\"]/following::select").click();
  await page.keyboard.press("ArrowDown");
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "E2E Test Job Fair" }).hover();
  await page.locator("//DIV[normalize-space() = \"Job Fair\"]").hover();
  await page.locator("div.sub-header>em.ng-binding").hover();
  await page.locator("span>em").hover();
  await page.locator("//DIV[normalize-space() = \"Virtual\"]").hover();
  await page.getByRole('link', { name: "Events" }).click();
  await page.waitForLoadState('load');
  await page.locator("a.event-name.primary-item.primary-item-with-icons>span.primary-item-text.ng-binding").hover();
  await page.locator("td.table-non-primary-col.center>span.badge.event-status").hover();
  await page.locator("td.table-non-primary-col>span.badge").nth(1).hover();
  await page.locator("tr.event.ng-scope>td.select-checkbox").click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.locator("a.event-name.primary-item.primary-item-with-icons>span.primary-item-text.ng-binding").click();
  await page.waitForLoadState('load');
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Edit Event" }).hover();
  await page.getByRole('link', { name: "Cancel Event" }).hover();
  await page.getByRole('link', { name: "Delete" }).hover();
  await page.getByRole('link', { name: "Duplicate" }).hover();
  await page.getByRole('link', { name: "Print Name Tags" }).hover();
  await page.getByRole('link', { name: "Generate QR Code" }).hover();
  await page.getByRole('link', { name: "Launch Check-In Kiosk" }).hover();
  await page.getByRole('link', { name: "Copy Student URL" }).hover();
  await page.getByRole('link', { name: "Copy Employer URL" }).hover();
  await page.getByRole('link', { name: "View Audit Log" }).hover();
  await page.getByRole('link', { name: "Edit Event" }).click();
  await page.waitForLoadState('load');
  await page.locator("//LABEL[normalize-space() = \"Event Name*\"]").click();
  await page.getByPlaceholder("Event Name").fill("Test 67 To Test 197");
  await page.locator("SELECT[name='EventTypeId']").click();
  await page.locator("//LABEL[normalize-space() = \"Dress Attire*\"]").click();
  await page.locator("SELECT[name='DressAttireId']").selectOption("number:1");
  await page.locator("//LABEL[normalize-space() = \"Student Group*\"]").click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.getByRole('button', { name: "Current Students" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('heading', { name: "Eligibility" }).click();
  await page.getByRole('button', { name: "Save" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Test 67 To Test 197" }).hover();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Launch Check-In Kiosk" }).click();
  await page.getByRole('heading', { name: "Please Select a Check-In Type" }).hover();
  await page.locator("label.radio-inline>b").hover();
  await page.locator("label.radio-inline>b").nth(1).hover();
  await page.locator("label.radio-inline>b").nth(2).hover();
  await page.locator("label.radio-inline>b").click();
  await page.locator("//LABEL[normalize-space() = \"Open check-in: Allow all users to check-in regardless of eligibility or registration status.\"]").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Ok" }).click();
  await page.getByRole('heading', { name: "Test 67 To Test 197" }).hover();
  await page.locator("div>p.ng-scope").hover();
  await page.getByPlaceholder("Email or Student ID").fill("e2e.student.fullaccess@campuswide.com");
  await page.getByRole('button', { name: "Check-in" }).click();
  await page.getByRole('heading', { name: "Success!" }).hover();
  await page.locator("//DIV[normalize-space() = \"Test 67 To Test 197 Please swipe your student ID to check in, or enter your details below Check-in\"]").nth(7).hover();
  await page.getByRole('heading', { name: "Test 67 To Test 197" }).hover();
  await page.locator("div>p.ng-scope").hover();
  await page.goto('https://e2e-tests-campuswide.admin.qa-12twenty.com/', { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Events" }).click();
  await page.locator("a.event-name.primary-item.primary-item-with-icons>span.primary-item-text.ng-binding").hover();
  await page.locator("a.event-name.primary-item.primary-item-with-icons>span.primary-item-text.ng-binding").click();
  await page.getByRole('link', { name: "Registered Students (1)" }).click();
  await page.getByRole('link', { name: "e2e Test Student" }).hover();
  await page.locator("tr>th.sortable.center").hover();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Cancel Event" }).hover();
  await page.getByRole('link', { name: "Cancel Event" }).click();
  await page.getByRole('heading', { name: "Cancel Event" }).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByRole('heading', { name: "Success!" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByRole('link', { name: "Event Details" }).click();
  await page.locator("div.actionable-alert-message>span.ng-scope").hover();
  await page.locator("button.btn.dropdown-toggle.ng-binding>span.glyphicon.glyphicon-option-vertical.ng-scope").click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete Event" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Event" }).click();
  await page.getByRole('heading', { name: "Oops!" }).hover();
  await page.locator("div.modal-content>div.modal-body").nth(4).hover();
  await page.getByRole('link', { name: "OK" }).click();
  await page.getByRole('link', { name: "Registered Students (1)" }).click();
  await page.getByRole('link', { name: "e2e Test Student" }).hover();
  await page.locator("BUTTON[type='button']").nth(9).click();
  await page.getByRole('link', { name: "Cancel Registration" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete Event" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Event" }).click();
  await page.getByRole('link', { name: "Events" }).click();
  await page.waitForLoadState('load');
  await page.reload();
  await page.reload();
  selector = MK.onSetGV(`//SPAN[contains(text(),"Muuktest Event")]`, null);
  var isElementPresent = await page.locator(selector).count() > 0;
  if (!isElementPresent) {
  snippetLog('Element is not present.');
  } else {
  throw new Error('Element is present');
  }
});
