// TC: TC67722
// 12TE Interviews - Employer user adds a multi-school interview to multiple schools

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("12TE Interviews - Employer user adds a multi-school interview to multiple schools", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;
  const text = msg.text();
  const timestamp = new Date().toLocaleString();

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(employerQA, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Email Address").fill("e2e.employeruser.subscription.admin@walmart.com");
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.waitForTimeout(2000);
  await page.locator("button.btn.btn-school.submit-login-form>span").click();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").hover();
  await page.getByRole('link', { name: "Interviews" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Interviews" }).hover();
  await page.getByRole('link', { name: "Analytics" }).hover();
  await page.getByRole('link', { name: "Interviews" }).click();
  await page.getByRole('heading', { name: "Interviews" }).hover();
  await page.getByRole('link', { name: "Interview Schedule" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "General" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Interview Name*\"]").hover();
  await page.getByPlaceholder("Interview Name").fill("Muuktest Interview Test");
  await page.getByRole('heading', { name: "Interview Details" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Interview Format*\"]").hover();
  await page.getByRole('heading', { name: "Interview Dates" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Interview Date Selection*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Employer Selected\"]").click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[normalize-space() = \"Interview Plan*\"]").click();
  await page.locator("SELECT[name='CoreInterviewPlanTemplateId']").selectOption("number:31");
  await page.getByRole('button', { name: "Next" }).click();
  await page.getByRole('heading', { name: "Muuktest Interview Test" }).hover();
  await page.locator("div.header-main>div.sub-header.ng-binding").hover();
  await page.getByRole('link', { name: "Job Postings (0)" }).hover();
  await page.locator("span.actionable-alert-message>span.ng-scope").hover();
  await page.getByRole('link', { name: "New Job" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Please select one or more program types..." }).hover();
  await page.getByRole('button', { name: "Continue" }).click();
  await page.locator("//SPAN[normalize-space() = \"School\"]").click();
  await page.getByPlaceholder("School").fill("e2e");
  await page.locator("//SPAN[normalize-space() = \"School\"]").click();
  await page.locator("div.school-info>div.school-name.ng-binding").nth(2).click();
  await page.locator("div.school-info>div.school-name.ng-binding").nth(3).click();
  await page.getByRole('heading', { name: "Selected Schools" }).hover();
  await page.locator("//DIV[normalize-space() = \"Items: 2\"]").hover();
  await page.locator("li.order-item.ng-scope>div.order-name.ng-binding").hover();
  await page.locator("li.order-item.ng-scope>div.order-name.ng-binding").nth(1).hover();
  await page.getByRole('button', { name: "Continue" }).click();
  await page.waitForLoadState('load');
  await page.locator("//LABEL[normalize-space() = \"Job Title *\"]").hover();
  await page.getByRole('heading', { name: "Details" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Employment Types *\"]").hover();
  await page.getByPlaceholder("Job Title").fill("e2e Job Posting");
  await page.getByRole('button', { name: "-- Please Select Employment Types --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Type of Job *\"]").click();
  await page.locator("SELECT[name='CoreJobTypeId']").selectOption("number:1");
  await page.locator("//LABEL[normalize-space() = \"Practice Areas *\"]").click();
  await page.getByRole('button', { name: "-- Please Select Practice Areas --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Industries *\"]").click();
  await page.getByRole('button', { name: "-- Please Select Industries --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Functions *\"]").click();
  await page.getByRole('button', { name: "-- Please Select Functions --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Location Type *\"]").click();
  await page.locator("SELECT[name='LocationTypeId']").selectOption("number:3");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Salary Range\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Description *\"]").click();
  await page.locator("html").click();
  await page.locator("div.form-group>label.control-label").nth(9).click();
  await page.getByRole('heading', { name: "Job Dates" }).hover();
  await page.locator("//LABEL[normalize-space() = \"How do you plan on reviewing your applicants?*\"]").hover();
  await page.getByPlaceholder("Url").fill("https://www.linkedin.com");
  await page.locator("//LABEL[normalize-space() = \"I will review applicants as they come in, and may close the job posting early\"]").click();
  await page.getByRole('heading', { name: "Target Candidate Profile" }).click();
  await page.locator("//LABEL[normalize-space() = \"Candidate Population*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Students & Alumni\"]").click();
  await page.getByRole('link', { name: "Back" }).hover();
  await page.getByPlaceholder("Additional Candidate Requirements").fill("Current");
  await page.getByRole('link', { name: "Continue" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Continue" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Order Details" }).hover();
  await page.getByRole('button', { name: "Submit Free Order" }).click();
  await page.getByRole('button', { name: "Action" }).click();
  await page.getByRole('link', { name: "Edit Interview" }).hover();
  await page.getByRole('link', { name: "Cancel Interview" }).hover();
  await page.getByRole('link', { name: "Cancel Interview" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Interviews" }).click();
  selector = MK.onSetGV(`//A[contains(text(),"Muuktest Interview Test")]//ancestor::tr//SPAN[contains(text(),"Schedule Needed")]`, null);
  var isElementPresent = await page.locator(selector).count() > 0;
  if (!isElementPresent) {
  snippetLog('Element is not present.');
  } else {
  throw new Error('Element is present');
  }
});
