// TC: TC60749
// Student Employment - Post a Student Employment Job - Admin

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Student Employment - Post a Student Employment Job - Admin", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: "Student Employment" }).click();
  await page.getByRole('heading', { name: "Job Listings & Interviews" }).hover();
  await page.getByRole('link', { name: "Post a Student Employment Job" }).click();
  await page.getByRole('heading', { name: "Create Student Employment Job" }).hover();
  await page.getByPlaceholder("Employer").fill("Alphabet");
  await page.locator("div.tt-suggestion.tt-selectable>strong.tt-highlight").click();
  await page.getByPlaceholder("Job Title").fill("Software Engineer");
  await page.getByRole('button', { name: "-- Type of Job --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Salary Range\"]").click();
  await page.getByRole('button', { name: "Full-Time Job" }).click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Salary Range\"]").click();
  await page.getByPlaceholder("Min").fill("60000");
  await page.getByPlaceholder("Max").fill("90000");
  await page.locator("SELECT[name='CurrencyId']").selectOption("number:1");
  await page.locator("SELECT[id='LocationTypeId'][name='LocationTypeId']").click();
  await page.locator("div.multiline-lookup.ng-scope>select.multiline-input.form-control.ng-pristine.ng-untouched").selectOption("number:1");
  await page.getByPlaceholder("City").fill("New York - NY");
  await page.locator("//DIV[normalize-space() = \"New York - NY\"]").click();
  await page.getByRole('button', { name: "-- Industry --" }).click();
  await page.getByPlaceholder("Search").fill("Technology/Engineering/Science");
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Job Function*\"]").click();
  await page.getByRole('button', { name: "-- Job Function --" }).click();
  await page.getByPlaceholder("Search").fill("Information Technology");
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Preferred Years of Experience\"]").click();
  await page.getByPlaceholder("Preferred Years of Experience").fill("5");
  await page.locator("SELECT[id='InterviewFormatId'][name='InterviewFormatId']").selectOption("number:6");
  await page.getByRole('button', { name: "-- Work Authorization Requirement --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Work-Study Required?\"]").click();
  await page.locator("//LABEL[normalize-space() = \"No\"]").click();
  await page.getByRole('heading', { name: "Application Method(s)*" }).click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Apply via This Site*\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(1).click();
  await page.locator("body.cke_editable.cke_editable_themed.cke_contents_ltr.cke_show_borders>p").click();
  await page.waitForTimeout(1000);
  page.keyboard.type('Testing');
  await page.getByRole('heading', { name: "Attachments" }).click();
  await page.getByRole('link', { name: "browse" }).click();
  fileName = MK.onSetGV(`Test_Resume_01.pdf`, null);
  var fileInput = await page.$("INPUT[type='file']");
  var filePath ="./test/"+fileName;
  if(fileInput){
  await fileInput.setInputFiles(filePath);
  }
  else{
  throw new Error('Element to upload file is not present.');
  }
  await page.waitForTimeout(1000);
  await page.getByPlaceholder("MM/DD/YYYY").fill("10/16/2024");
  await page.locator("div.form-group.ng-scope>label.control-label").nth(3).click();
  await page.getByPlaceholder("MM/DD/YYYY").fill("12/31/2028");
  await page.locator("//LABEL[normalize-space() = \"How do you plan on reviewing your applicants?\"]").click();
  await page.locator("//LABEL[normalize-space() = \"I will review applicants as they come in, and may close the job posting early\"]").click();
  await page.locator("div.form-group>label.control-label").nth(20).click();
  await page.getByPlaceholder("MM/DD/YYYY").fill("12/01/2024");
  await page.getByRole('heading', { name: "Interview Detail" }).click();
  await page.locator("//LABEL[normalize-space() = 'Interviewer']/following::SELECT").click();
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Enter');
  await page.getByRole('button', { name: "Use My Information" }).click();
  await page.getByPlaceholder("Title").fill("Software Engineer");
  await page.getByPlaceholder("Job Posting Contact Phone").fill("+1-123-456-7890");
  await page.getByPlaceholder("Job Posting Contact Address").fill("1234 Technology Drive New York, NY 10001 USA");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Is Alumnus\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(4).click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[normalize-space() = \"Student Group*\"]").click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('heading', { name: "Career Center Administrator" }).click();
  await page.locator("//LABEL[normalize-space() = \"Source of Job Posting\"]").click();
  await page.locator("SELECT[id='JobPostingSourceId'][name='JobPostingSourceId']").selectOption("number:100063031018426");
  await page.locator("label.control-label>span.ng-binding").click();
  await page.locator("SELECT[id='custom_attribute_3'][name='custom_attribute_3']").click();
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Enter');
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save Draft" }).hover();
  await page.waitForTimeout(3000);
  await page.getByRole('button', { name: "Next" }).click();
  await page.getByRole('heading', { name: "Job Posting" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Ok" }).click();
  await page.getByRole('heading', { name: "Software Engineer" }).hover();
  await page.getByRole('link', { name: "Alphabet" }).hover();
  await page.locator("div.sub-header.ng-scope>text.ng-binding").hover();
  await page.locator("//SPAN[normalize-space() = \"Full-Time Job\"]").hover();
  await page.locator("div.sub-header.badges>span.badge.application-open").hover();
  await page.locator("//SPAN[normalize-space() = \"\\$60,000.00 - \\$90,000.00 USD per year\"]").hover();
  await page.locator("dl.dl-horizontal>dd.ng-binding").nth(1).hover();
  await page.locator("dl.dl-horizontal>dd.ng-binding").nth(2).hover();
  await page.locator("span>span.ng-binding.ng-scope").nth(1).hover();
  await page.locator("span>span.ng-binding.ng-scope").nth(2).hover();
  await page.locator("span>span.ng-binding.ng-scope").nth(3).hover();
  await page.locator("ng-transclude>span.primary-item-text.ng-binding.ng-scope").hover();
  await page.locator("div.entity-short-summary-primary>span.sub-info.ng-binding").hover();
  await page.locator("div.entity-short-summary-primary>span.sub-info.ng-binding.ng-scope").hover();
  await page.locator("span>span.ng-binding.ng-scope").nth(4).hover();
  await page.locator("//DIV[normalize-space() = \"Resume (Required)\"]").hover();
  await page.locator("dd>div.ng-binding").nth(2).hover();
  await page.locator("dd>div.ng-binding").nth(3).hover();
  await page.locator("dd>div.address.ng-binding").hover();
  await page.getByRole('link', { name: "Student Employment" }).click();
  await page.getByRole('link', { name: "All" }).click();
  await page.locator("//SPAN[normalize-space() = \"Job Status\"]").click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('heading', { name: "Job Listings & Interviews" }).click();
  await page.getByPlaceholder("Employer, Job Title, or Keyword").fill("Software Engineer");
  await page.waitForTimeout(1000);
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.locator("a.primary-item.primary-item-with-icons.job-title>span.primary-item-text.ng-binding").nth(3).hover();
  await page.locator("div.entity-short-summary-primary>span.sub-info.ng-binding.ng-scope").nth(3).hover();
  await page.locator("//SPAN[normalize-space() = \"New York - NY\"]").hover();
  await page.getByRole('link', { name: "0 applicants" }).hover();
  await page.locator("a.primary-item.primary-item-with-icons.job-title>span.primary-item-text.ng-binding").nth(3).click();
  await page.waitForTimeout(10000);
  await page.waitForLoadState('load');
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.locator("ul.dropdown-menu.dropdown-menu-right>li.dropdown-header.ng-scope").hover();
  await page.getByRole('link', { name: "Delete" }).hover();
  await page.getByRole('link', { name: "Duplicate" }).hover();
  await page.getByRole('link', { name: "Deactivate" }).hover();
  await page.locator("ul.dropdown-menu.dropdown-menu-right>li.dropdown-header.ng-scope").nth(1).hover();
  await page.getByRole('link', { name: "Copy Student URL" }).hover();
  await page.getByRole('link', { name: "Copy Employer URL" }).hover();
  await page.getByRole('link', { name: "View Audit Log" }).hover();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete Job Posting" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Job Posting" }).click();
  await page.getByRole('heading', { name: "Job Listings & Interviews" }).hover();
  await page.reload();
  await page.getByRole('button', { name: "Reset" }).click();
  await page.waitForTimeout(1000);
  selector = MK.onSetGV(` //SPAN[contains(text(),"Software Engineer")]`, null);
  var isElementPresent = await page.locator(selector).count() > 0;
  if (!isElementPresent) {
  snippetLog('Element is not present.');
  } else {
  throw new Error('Element is present');
  }
});
