// TC: TC61996
// Experiential Learning - Add a new experience - Student

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Experiential Learning - Add a new experience - Student", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;
  const text = msg.text();
  const timestamp = new Date().toLocaleString();

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideStudentURL, { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.student.fullaccess@campuswide.com");
  await page.getByPlaceholder("Password").fill("BoH5dORH7xg%");
  await page.getByRole('button', { name: "Student/Alumni Log In" }).click();
  await page.waitForTimeout(1000);
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Home" }).hover();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Experiential Learning" }).click();
  await page.getByRole('heading', { name: "Experiential Learning" }).hover();
  await page.getByRole('link', { name: "New Experience" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Create New Experience" }).hover();
  await page.getByRole('heading', { name: "Basics" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Employer*\"]").click();
  await page.getByPlaceholder("Specify employer name").fill("Albertsons");
  await page.locator("div.tt-suggestion.tt-selectable>strong.tt-highlight").click();
  await page.locator("//LABEL[normalize-space() = \"Experiential Learning Type*\"]").click();
  await page.locator("SELECT[name='TypeId']").selectOption("number:1001430512364");
  await page.getByRole('heading', { name: "Supervisor" }).click();
  await page.locator("//LABEL[normalize-space() = \"Contact*\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Contact*\"]/following-sibling::div//select").selectOption("number:220048011149329");
  await page.locator("ng-transclude>span.primary-item-text.ng-binding.ng-scope").hover();
  await page.locator("div.entity-short-summary-primary>span.sub-info.ng-binding").hover();
  await page.locator("div.entity-short-summary-primary>span.sub-info.ng-binding.ng-scope").hover();
  await page.locator("//LABEL[normalize-space() = \"Employer Supervisor Phone*\"]").click();
  await page.getByPlaceholder("Employer Supervisor Phone").fill("7546822186");
  await page.locator("//LABEL[normalize-space() = \"Contact\"]").nth(2).click();
  await page.getByPlaceholder("Select a contact").fill("Brad Andrews");
  await page.locator("div.tt-suggestion.tt-selectable>strong.tt-highlight").nth(1).click();
  await page.locator("ng-transclude>span.primary-item-text.ng-binding.ng-scope").nth(1).hover();
  await page.locator("div.entity-short-summary-primary>span.sub-info.ng-binding").nth(2).hover();
  await page.locator("div.entity-short-summary-primary>span.sub-info.ng-binding.ng-scope").nth(1).hover();
  await page.locator("//LABEL[normalize-space() = \"Faculty Supervisor First Name\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Faculty Supervisor Last Name\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Faculty Supervisor Email\"]").hover();
  await page.getByRole('heading', { name: "When" }).click();
  await page.getByPlaceholder("MM/DD/YYYY").fill("12/01/2022");
  await page.getByPlaceholder("MM/DD/YYYY").fill("12/01/2023");
  await page.locator("//LABEL[normalize-space() = \"Academic Term*\"]").click();
  await page.locator("SELECT[name='AcademicTermId']").selectOption("number:190017010143208");
  await page.locator("SELECT[name='AcademicTermId']").click();
  await page.locator("SELECT[name='SchoolYearId']").selectOption("number:19");
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Albertsons" }).hover();
  await page.locator("//DIV[normalize-space() = \"Fall 2022\"]").hover();
  await page.locator("div.sub-header.badges>span.badge").hover();
  await page.getByRole('button', { name: "Submit" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.waitForLoadState('load');
  await page.locator("div.sub-header.badges>span.badge.pending-initial-approval").hover();
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('e2e-tests-campuswide.admin.qa-12twenty.com/');
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("e2e Test Student");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "e2e Test Student" }).click();
  await page.getByRole('heading', { name: "e2e Test Student" }).hover();
  await page.locator("ng-transclude>span.ng-binding.ng-scope").click();
  await page.waitForLoadState('load');
  await page.waitForTimeout(2000);
  await page.locator("//SPAN[normalize-space() = \"Pending Initial Approval\"]").hover();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Approve" }).click();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.locator("div.sub-header.badges>span.badge.in-progress").hover();
  await page.getByRole('button', { name: "Submit" }).click();
  await page.getByRole('button', { name: "OK" }).click();
  await page.locator("//SPAN[normalize-space() = \"Pending Final Approval\"]").hover();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForTimeout(2000);
  await page.reload();
  await page.reload();
  urlpage1 = page.url();
  indexPages = MK.onSetGV(`2`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForLoadState('load');
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Approve" }).click();
  await page.getByRole('button', { name: "OK" }).click();
  await page.locator("div.sub-header.badges>span.badge.complete").hover();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(1000);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  var targetPage = context.pages().find(page => page.url() === urlpage1);
  if (targetPage) {
  await targetPage.bringToFront();
  } else {
  throw new Error(`A page with the next url was not found: ${urlpage1}`);
  }
  await page.waitForTimeout(1000);
  await page.reload();
  await page.getByRole('link', { name: "Back to List" }).click();
  await page.getByRole('link', { name: "Albertsons" }).hover();
  await page.getByRole('link', { name: "Albertsons" }).click();
  await page.getByRole('link', { name: "Documents and Forms" }).click();
  await page.getByRole('link', { name: "Details" }).click();
  await page.waitForTimeout(1000);
  indexPages = MK.onSetGV(`2`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete Experience" }).hover();
  await page.getByRole('button', { name: "Delete Experience" }).click();
});
