// TC: TC75214
// Outcomes - Student creates Post Graduation Own Venture

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Outcomes - Student creates Post Graduation Own Venture", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideStudentURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.student.fullaccess@campuswide.com");
  await page.getByPlaceholder("Password").fill("BoH5dORH7xg%");
  await page.getByRole('button', { name: "Student/Alumni Log In" }).click();
  await page.waitForTimeout(1000);
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Profile" }).click();
  await page.getByRole('link', { name: "Home" }).click();
  await page.getByRole('link', { name: "Add Experience or Status" }).click();
  await page.getByRole('button', { name: "Post Graduation" }).click();
  await page.getByRole('heading', { name: "Report Status" }).hover();
  await page.locator("div.add-job-options-title>p.phase-name.ng-binding").hover();
  await page.locator("div.add-job-options-title>p.prompt.ng-binding").hover();
  await page.getByRole('button', { name: "Own Venture" }).click();
  await page.locator("//LABEL[contains(normalize-space(),\"Employer\")]").hover();
  await page.getByPlaceholder("Employer").fill("TBD");
  await page.locator("//LABEL[contains(normalize-space(),\"Detailed Industry\")]").click();
  await page.locator("SELECT[name='Job.JobIndustryId'][id='Job.JobIndustryId']").selectOption("149999414151537");
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[contains(normalize-space(),\"Job Title\")]").hover();
  await page.getByPlaceholder("Job Title").fill("Owner Muuk");
  await page.locator("SELECT[id='Job_OwnVentureTypeId'][name='Job.OwnVentureTypeId']").selectOption("2");
  await page.locator("//LABEL[contains(normalize-space(),\"Location Type\")]").hover();
  await page.locator("SELECT[name='Job.LocationTypeId'][id='Job.LocationTypeId']").selectOption("2");
  await page.locator('input[type="checkbox"]').click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("INPUT[type='text'][id='Job.Salary.TotalCompensation'][name='Job.Salary.TotalCompensation']").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a freelance position?\")]").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(1).click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a faculty position?\")]").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(2).click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(4).click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a post-graduation internship?\")]").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(5).click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(6).click();
  await page.locator('input[type="radio"]').check();
  await page.locator("SELECT[id='Job_FundingRaisedId'][name='Job.FundingRaisedId']").selectOption("1");
  await page.locator("div.inputRow>label.control-label").nth(19).hover();
  await page.locator("SELECT[id='Job_OwnVentureNumberOfEmployeesId'][name='Job.OwnVentureNumberOfEmployeesId']").selectOption("1");
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.locator("TEXTAREA[id='Job_OptionalPertinentInformation'][name='Job.OptionalPertinentInformation']").fill("Starting online company to sell clothes.");
  await page.locator("//label[normalize-space() = \"Satisfaction\"]").hover();
  await page.locator("//label[contains(normalize-space(),\"Star Rating Attribute - Required\")]").hover();
  await page.locator("td.ant-table-cell.drag-visible.column-center.ant-table-cell-row-hover>div.ant-row.css-eqeg24").click();
  await page.getByRole('button', { name: "Submit" }).click();
  await page.getByRole('link', { name: "OK" }).click();
  await page.getByRole('link', { name: "Home" }).click();
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('e2e-tests-campuswide.admin.qa-12twenty.com/');
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Students & Alumni" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("e2e");
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "e2e Test Student" }).click();
  await page.getByRole('link', { name: "Owner Muuk" }).hover();
  await page.locator("//A[@role=\"button\"][normalize-space() = \"Owner Muuk\"]/ancestor::div[@class=\"ng-scope\"][1]//button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Approve" }).click();
  await page.getByRole('heading', { name: "Approve Job" }).hover();
  await page.locator("//DIV[normalize-space() = \"Are you sure you want to approve this job?\"]").nth(1).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Approve" }).click();
  await page.waitForLoadState('load');
  await page.reload();
  await page.locator("//A[@role=\"button\"][normalize-space() = \"Owner Muuk\"]/ancestor::div[@class=\"ng-scope\"][1]//SPAN[normalize-space() = \"Approved\"]").hover();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('link', { name: "Owner Muuk" }).click();
  await page.getByRole('link', { name: "Own Venture" }).hover();
  await page.locator("div.badges>span.badge.ng-binding.ng-scope").nth(1).hover();
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.getByRole('button', { name: "Cancel" }).click();
  await page.locator("//A[contains(text(),\"Owner Muuk\")]//following::A[@title=\"Edit Job\"][normalize-space() = \"Edit\"]").hover();
  await page.locator("//A[contains(text(),\"Owner Muuk\")]//following::A[@role='button'][@title='Delete Job'][normalize-space() = \"Delete\"]").hover();
  await page.getByRole('button', { name: "Edit" }).hover();
  await page.locator("//A[contains(text(),\"Owner Muuk\")]//following::A[@role='button'][@title='Delete Job'][normalize-space() = \"Delete\"]").click();
  await page.getByRole('heading', { name: "Delete Entry" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Entry" }).click();
  await page.waitForTimeout(5000);
});
