// TC: TC64300
// 12TE Interviews - Schedule an interview for a job and then cancel it - Employer

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("12TE Interviews - Schedule an interview for a job and then cancel it - Employer", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(employerQA, { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Email Address").fill("e2e.employeruser.subscription.admin@walmart.com");
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.waitForTimeout(2000);
  await page.locator("button.btn.btn-school.submit-login-form>span").click();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").hover();
  await page.getByRole('link', { name: "Interviews" }).click();
  await page.getByRole('link', { name: "Interviews" }).hover();
  await page.getByRole('link', { name: "Analytics" }).hover();
  await page.getByRole('heading', { name: "Interviews" }).hover();
  await page.getByRole('link', { name: "Interview Schedule" }).click();
  await page.getByRole('heading', { name: "General" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Interview Name*\"]").hover();
  await page.getByPlaceholder("Interview Name").fill("Test");
  await page.getByRole('heading', { name: "Interview Details" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Interview Format*\"]").hover();
  await page.locator("//DIV[normalize-space() = \"You will be able to add a virtual meeting URL when creating schedules\"]").hover();
  await page.getByRole('heading', { name: "Interview Dates" }).click();
  await page.locator("div.form-section-inputs>div.alert.alert-info").hover();
  await page.locator("//LABEL[normalize-space() = \"Interview Date Selection*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Employer Selected\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"School Selected\"]").hover();
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.getByRole('button', { name: "Next" }).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('heading', { name: "Interview Dates" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Interview Date Selection*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Employer Selected\"]").hover();
  await page.locator('input[type="radio"]').check();
  await page.getByRole('button', { name: "Next" }).click();
  await page.locator("span.actionable-alert-message>span.ng-scope").hover();
  await page.getByRole('link', { name: "Job Posting" }).click();
  await page.getByRole('heading', { name: "Please select one or more program types..." }).hover();
  await page.getByRole('heading', { name: "Business" }).click();
  await page.getByRole('button', { name: "Continue" }).click();
  await page.locator("//DIV[normalize-space() = \"1 School Selection\"]").hover();
  await page.locator("//DIV[normalize-space() = \"2 Job Details\"]").hover();
  await page.locator("//DIV[normalize-space() = \"3 Extras\"]").hover();
  await page.locator("//DIV[normalize-space() = \"4 Review & Submit\"]").hover();
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Select All Results" }).hover();
  await page.locator("//DIV[normalize-space() = \"School (empty)\"]").nth(1).hover();
  await page.locator("//DIV[normalize-space() = \"Program Type Business (empty)\"]").nth(1).hover();
  await page.locator("//DIV[normalize-space() = \"Metro Region (empty)\"]").nth(1).hover();
  await page.locator("//DIV[normalize-space() = \"State (empty)\"]").nth(1).hover();
  await page.locator("//DIV[normalize-space() = \"North America Region (empty)\"]").nth(1).hover();
  await page.locator("//DIV[normalize-space() = \"Reset\"]").hover();
  await page.getByRole('heading', { name: "Selected Schools" }).hover();
  await page.locator("div.count>label").hover();
  await page.locator("li.order-item.ng-scope>div.order-name.ng-binding").hover();
  await page.locator("li.order-item.ng-scope>div.order-name.ng-binding").nth(1).hover();
  await page.locator("span>policy.ng-scope").click();
  await page.getByRole('button', { name: "Continue" }).click();
  await page.locator("//DIV[normalize-space() = \"2 Job Details\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Job Title *\"]").hover();
  await page.getByPlaceholder("Job Title").fill("Business job posting");
  await page.getByRole('heading', { name: "Details" }).click();
  await page.locator("//LABEL[normalize-space() = \"Type of Job *\"]").hover();
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Enter');
  await page.locator("//LABEL[normalize-space() = \"Industries *\"]").hover();
  await page.getByRole('button', { name: "-- Please Select Industries --" }).click();
  await page.getByPlaceholder("Search").fill("tech");
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Functions *\"]").hover();
  await page.getByPlaceholder("Search").fill("inform");
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Description *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Location Type *\"]").click();
  await page.locator("SELECT[name='LocationTypeId']").selectOption("number:3");
  await page.getByRole('heading', { name: "Additional Application Method(s)" }).click();
  await page.locator("div.form-group>label.control-label").nth(8).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Email Address * Use a comma to separate email addresses\"]").click();
  await page.getByPlaceholder("Email Address").fill("test@gmail.com");
  await page.getByRole('heading', { name: "Job Dates" }).click();
  await page.locator('input[type="radio"]').check();
  await page.getByRole('heading', { name: "Target Candidate Profile" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Target Cohort*\"]").hover();
  await page.getByPlaceholder("Target Cohort").fill("1st year  MBA");
  await page.getByRole('button', { name: "-- Please Select a Work Authorization --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('link', { name: "Continue" }).click();
});
