// TC: TC69203
// Mentorships - Set mentor, browse mentors, request mentor, complete tasks

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Mentorships - Set mentor, browse mentors, request mentor, complete tasks", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;
  const text = msg.text();
  const timestamp = new Date().toLocaleString();

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.locator("//a[normalize-space()=\"Site Management\"]/following-sibling::button").click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByRole('heading', { name: "Manage Students & Alumni" }).hover();
  await page.getByRole('button', { name: "Add New Student" }).click();
  await page.getByRole('heading', { name: "Student Account Information" }).hover();
  textContent = MK.onSetGV(` random number`, 5);
  await page.getByPlaceholder("First (Preferred) Name").fill("Muuktest");
  await page.getByPlaceholder("Last Name").fill("Mentor ` + textContent + `");
  await page.locator("div.form-group.ng-pristine.ng-scope.ng-invalid.ng-invalid-required>label.control-label.ng-binding").hover();
  await page.getByPlaceholder("Email Address").fill("muuktestmentor` + textContent + `@test.com");
  await page.locator("SELECT[name='IsEnrolled']").selectOption("number:1");
  await page.locator("div.form-group.ng-pristine.ng-scope.ng-invalid.ng-invalid-required>label.control-label.ng-binding").hover();
  await page.locator("SELECT[name='RoleId']").selectOption("number:149999900505");
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Bulk Update 1\"]").click();
  await page.locator("div.form-group.ng-scope.ng-dirty.ng-valid.ng-valid-required>label.control-label.ng-binding").nth(5).click();
  await page.locator("SELECT[name='ProgramId']").selectOption("number:1814999953610478");
  await page.locator("//LABEL[normalize-space() = \"College/School*\"]").hover();
  await page.locator("SELECT[name='College1Name']").selectOption("number:149999071101701");
  await page.locator("//LABEL[normalize-space() = \"Degree Level*\"]").hover();
  await page.locator("SELECT[name='DegreeLevelId']").selectOption("number:149999071102056");
  await page.locator("SELECT[name='Major1Name']").selectOption("number:360038051146044");
  await page.getByRole('heading', { name: "130 Steps" }).click();
  await page.locator("//LABEL[normalize-space() = \"Spring 2030\"]").click();
  await page.getByRole('link', { name: "Save Changes" }).click();
  await page.waitForTimeout(3000);
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("Muuktest Mentor ` + textContent + `");
  await page.locator("BUTTON[aria-label=\"Search\"]").click();
  await page.getByRole('link', { name: "Test Student #0001" }).click();
  await page.waitForTimeout(5000);
  await page.getByRole('link', { name: "Profile" }).click();
  await page.getByRole('heading', { name: "Mentorships" }).hover();
  await page.locator("dl.dl-horizontal>dt.ng-binding.ng-scope").nth(38).hover();
  await page.getByRole('button', { name: "Edit" }).click();
  await page.getByRole('heading', { name: "Edit Mentorships" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Allow users to request me as a mentor\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Snooze Mentorship Availability\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(1).click();
  await page.getByPlaceholder("Mentorship Terms").fill("Please see that I have terms and this is a test text.");
  await page.getByRole('button', { name: "Save" }).click();
  await page.locator("dl.dl-horizontal>dt.ng-binding.ng-scope").nth(38).hover();
  await expect(page.locator("//dt[normalize-space()=\"Allow users to request me as a mentor\"]/following-sibling::dd")).toHaveText("Yes");
  await page.locator("//dt[normalize-space()=\"Snooze Mentorship Availability\"]").hover();
  await expect(page.locator("//dt[normalize-space()=\"Snooze Mentorship Availability\"]/following-sibling::dd")).toHaveText("No");
  await page.locator("//dt[normalize-space()=\"Mentorship Terms\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Please see that I have terms and this is a test text.\"]").hover();
  await page.locator("//a[normalize-space()=\"Site Management\"]/following-sibling::button").click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("e2e");
  await page.locator("BUTTON[aria-label=\"Search\"]").click();
  await page.locator("//a[normalize-space()=\"e2e Test Student\"]/ancestor::tr//button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Login as user..." }).click();
  await page.getByRole('heading', { name: "Login as e2e Test Student" }).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.waitForTimeout(2000);
  await page.locator("//DIV[normalize-space() = \"You\\'re currently logged in as e2e Test Student (Student). When you\\'re done, please log out.\"]").hover();
  await page.getByRole('link', { name: "Mentorship" }).click();
  await page.getByPlaceholder("Search by Name").fill("Muuktest Mentor ` + textContent + `");
  await page.locator("BUTTON[aria-label=\"Search\"]").click();
  await page.getByRole('link', { name: "Muuktest Mentor 83732" }).click();
  await page.getByRole('button', { name: "Request Muuktest as a mentor" }).click();
  await page.getByRole('heading', { name: "Request" }).hover();
  await page.locator("//SPAN[normalize-space() = \"Please see that I have terms and this is a test text.\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Message *\"]").click();
  await page.locator("SPAN[role='presentation']").nth(1).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: "Request" }).click();
  await page.locator("//SPAN[normalize-space() = \"Your request has been sent successfully.\"]").hover();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").click();
  await page.getByRole('link', { name: "Log Out" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("Muuktest Mentor ` + textContent + `");
  await page.locator("BUTTON[aria-label=\"Search\"]").click();
  await page.getByRole('link', { name: "Test Student #0001" }).click();
  await page.getByRole('link', { name: "More" }).click();
  await page.getByRole('link', { name: "Emails" }).click();
  await page.getByRole('link', { name: "New Mentorship Request" }).click();
  await page.getByRole('heading', { name: "Email Overview" }).hover();
  await page.getByRole('link', { name: "Ok" }).click();
  await page.locator("//a[normalize-space()=\"Site Management\"]/following-sibling::button").click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("Muuktest Mentor ` + textContent + `");
  await page.locator("BUTTON[aria-label=\"Search\"]").click();
  await page.locator("BUTTON[type='button']").nth(11).click();
  await page.getByRole('link', { name: "Login as user..." }).click();
  await page.getByRole('button', { name: "OK" }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: "Mentorship" }).click();
  await page.getByRole('heading', { name: "Manage Mentorship" }).hover();
  await page.getByRole('heading', { name: "Active" }).hover();
  await page.getByRole('heading', { name: "Requests" }).hover();
  await page.locator("//SPAN[normalize-space() = \"e2e Test Student\"]").nth(1).hover();
  await page.locator("//SPAN[normalize-space() = \"PENDING\"]").hover();
  await page.locator("//span[normalize-space()=\"e2e Test Student\"]/ancestor::tr//button").click();
  await page.getByRole('link', { name: "Accept" }).hover();
  await page.getByRole('link', { name: "Decline" }).hover();
  await page.getByRole('link', { name: "Accept" }).click();
  await page.getByRole('heading', { name: "Accept" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Message (Optional)\"]").hover();
  await page.locator("DIV[id='cke_editor2'][role='application']").click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: "Accept" }).click();
  await page.locator("//span[normalize-space()=\"e2e Test Student\"]//following::button").click();
  await page.getByRole('link', { name: "Send Email" }).click();
  await page.locator("//LABEL[normalize-space() = \"Message:\"]").hover();
  await page.locator("INPUT[type='text'][name='subject']").fill("Test Email");
  await page.locator("DIV[id='cke_ckeditor-email-dialog-1768424445190'][role='application']").click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: "Send" }).click();
  await page.getByRole('heading', { name: "Success!" }).hover();
  await page.locator("//DIV[normalize-space() = \"Your email has been sent.\"]").nth(1).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").click();
  await page.getByRole('link', { name: "Log Out" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("e2e");
  await page.locator("BUTTON[aria-label=\"Search\"]").click();
  await page.getByRole('link', { name: "e2e Test Student" }).click();
  await page.getByRole('link', { name: "More" }).click();
  await page.getByRole('link', { name: "Emails" }).click();
  await page.locator("//SPAN[normalize-space() = \"Date\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Custom Range\"]").click();
  await page.locator('input[type="radio"]').click();
  await page.locator("//LABEL[normalize-space() = \"Relative Range\"]").click();
  await page.locator('input[type="radio"]').click();
  await page.locator("SELECT[name='date_']").selectOption("number:7");
  await page.locator("//SPAN[normalize-space() = \"Date\"]").click();
  await page.getByRole('link', { name: "Muuktest Mentor 83732 has messaged you via E2E Tests Campuswide E2E-CPW - Test Email" }).click();
  await page.getByRole('heading', { name: "Email Overview" }).hover();
  await page.locator("//P[normalize-space() = \"Test\"]").hover();
  await page.getByRole('link', { name: "Ok" }).click();
  await page.getByRole('link', { name: "Mentorship" }).click();
  await page.locator("//SPAN[normalize-space() = \"e2e Test Student\"]").click();
  await page.getByRole('heading', { name: "Mentorship" }).hover();
  await page.getByRole('heading', { name: "Mentee" }).hover();
  await page.locator("//SPAN[normalize-space() = \"e2e Test Student\"]").nth(1).hover();
  await page.getByRole('heading', { name: "Mentor" }).hover();
  await page.locator("//SPAN[contains(normalize-space(),\"Muuktest Mentor\")]").hover();
  await page.getByRole('link', { name: "OK" }).click();
  await page.locator("//a[normalize-space()=\"Site Management\"]/following-sibling::button").click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("e2e");
  await page.locator("BUTTON[aria-label=\"Search\"]").click();
  await page.locator("//a[normalize-space()=\"e2e Test Student\"]/ancestor::tr//button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Login as user..." }).click();
  await page.getByRole('heading', { name: "Login as e2e Test Student" }).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.waitForTimeout(2000);
  await page.locator("//DIV[normalize-space() = \"You\\'re currently logged in as e2e Test Student (Student). When you\\'re done, please log out.\"]").hover();
  await page.getByRole('link', { name: "Mentorship" }).click();
  await page.getByRole('link', { name: "Manage" }).click();
  await page.locator("//SPAN[normalize-space() = \"e2e Test Student\"]").nth(1).click();
  await page.getByRole('heading', { name: "Tasks (0/3)" }).hover();
  await page.locator("//label[normalize-space()=\"Task 1\"]/following-sibling::div//input").click();
  await page.locator("//label[normalize-space()=\"Task 3\"]/following-sibling::div//input").click();
  await page.getByRole('heading', { name: "Tasks (2/3)" }).hover();
  await page.getByRole('link', { name: "OK" }).click();
  await page.locator("//SPAN[normalize-space() = \"e2e Test Student\"]").nth(1).click();
  await page.locator("//label[normalize-space()=\"Task 3\"]/following-sibling::div//input").click();
  await page.getByRole('heading', { name: "Tasks (1/3)" }).hover();
  await page.getByRole('link', { name: "OK" }).click();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").click();
  await page.getByRole('link', { name: "Log Out" }).click();
  await page.getByRole('link', { name: "More" }).click();
  await page.getByRole('link', { name: "Mentorships" }).click();
  await page.locator("//SPAN[normalize-space() = \"e2e Test Student\"]").click();
  await page.getByRole('heading', { name: "Tasks (1/3)" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Task 1\"]").hover();
  await page.getByRole('link', { name: "OK" }).click();
  await page.locator("//a[normalize-space()=\"Site Management\"]/following-sibling::button").click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("Muuktest Mentor ` + textContent + `");
  await page.locator("BUTTON[aria-label=\"Search\"]").click();
  await page.locator("BUTTON[type='button']").nth(11).click();
  await page.getByRole('link', { name: "Login as user..." }).click();
  await page.getByRole('button', { name: "OK" }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: "Mentorship" }).click();
  await page.locator("//a[normalize-space()=\"e2e Test Student\"]/following::button").click();
  await page.getByRole('link', { name: "Complete Mentorship Tasks" }).click();
  await page.getByRole('heading', { name: "Tasks (1/3)" }).hover();
  await page.locator("//label[normalize-space()=\"Task 3\"]/following-sibling::div//input").click();
  await page.getByRole('link', { name: "OK" }).click();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").click();
  await page.getByRole('link', { name: "Log Out" }).click();
  await page.getByRole('link', { name: "Mentorship" }).click();
  await page.locator("//SPAN[normalize-space() = \"e2e Test Student\"]").click();
  await page.getByRole('heading', { name: "Tasks (2/3)" }).hover();
  await page.locator("//SPAN[contains(normalize-space(),\"Muuktest Mentor\")]").click();
  await page.waitForTimeout(2000);
  await page.locator("//a[normalize-space()=\"Site Management\"]/following-sibling::button").click();
  await page.getByRole('link', { name: "Manage Users" }).click();
  await page.getByPlaceholder("Search by Name, Email Address or ID").fill("Muuktest Mentor ` + textContent + `");
  await page.locator("BUTTON[aria-label=\"Search\"]").click();
  await page.locator("BUTTON[type='button']").nth(11).click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Confirm Delete" }).hover();
  await page.locator("//LABEL[normalize-space() = \"I understand that deleting a student user will delete the user and all data associated with their account. This action can not be undone.\"]").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.getByRole('heading', { name: "Oops!" }).hover();
  await page.locator("//DIV[normalize-space() = \"This user can not be deleted as they are associated with a mentorship record. Please set the user to inactive status instead.\"]").hover();
  await page.getByRole('link', { name: "OK" }).click();
  await page.locator("BUTTON[type='button']").nth(11).click();
  await page.getByRole('link', { name: "Edit" }).click();
  await page.getByRole('heading', { name: "Student Account Information" }).hover();
  await page.locator("div.form-group.ng-pristine.ng-scope.ng-invalid.ng-invalid-required>label.control-label.ng-binding").hover();
  await page.locator("SELECT[name='IsEnrolled']").selectOption("number:2");
  await page.getByRole('link', { name: "Cancel" }).hover();
  await page.getByRole('link', { name: "Save Changes" }).click();
  await page.locator("//SPAN[normalize-space() = \"Student saved successfully\"]").hover();
});
