// TC: TC61658
// OCI - Admin registers for an Interview then deletes the record

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("OCI - Admin registers for an Interview then deletes the record", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Job Listings & Interviews" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Job Listings & Interviews" }).hover();
  await page.getByRole('link', { name: "Register for Interviews" }).click();
  await page.getByRole('heading', { name: "Register For Interviews" }).hover();
  await page.getByPlaceholder("Employer").fill("Duolingo");
  await page.waitForTimeout(3000);
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Enter');
  await page.locator("SELECT[name='OciRoundId']").click();
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Enter');
  await page.getByRole('heading', { name: "Interview Periods Please Note: Once period dates for individual OCI registrations have been customized, periods can no longer be added or removed from the round. OCI periods can be added or removed from a round, even if there are active OCI registrations, unless period dates have been customized for individual OCI registrations" }).hover();
  await page.locator("tr>th").hover();
  await page.locator("td>div.ng-binding").hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.day").click();
  await page.waitForTimeout(1000);
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(18).click();
  await page.waitForTimeout(1000);
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(22).click();
  await page.locator("SELECT[id='custom_attribute_800'][name='custom_attribute_800']").click();
  await page.locator("SELECT[id='custom_attribute_800'][name='custom_attribute_800']").selectOption("1180051101059");
  await page.getByRole('heading', { name: "Interview Preferences" }).hover();
  await page.locator("//LABEL[normalize-space() = \"# of Total Interview Slots*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"# of Interview Rooms Requested*\"]").hover();
  await page.getByPlaceholder("# of Total Interview Slots").fill("2");
  await page.locator("//LABEL[normalize-space() = \"Length of Interview*\"]").hover();
  await page.getByPlaceholder("# of Interview Rooms Requested").fill("3");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Rotating Schedule\"]").hover();
  await page.getByPlaceholder("Length of Interview").fill("1");
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Are you hiring for multiple positions?\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(1).click();
  await page.locator("//LABEL[normalize-space() = \"Please set the number of applications allowed per student across all positions\"]").hover();
  await page.getByRole('heading', { name: "Additional Information" }).hover();
  await page.locator("div.form-group>label.control-label").nth(12).hover();
  await page.getByPlaceholder("Please set the number of applications allowed per student across all positions").fill("7");
  await page.locator("div.form-group>label.control-label").nth(12).click();
  await page.getByPlaceholder("Visitation Description").fill("Visitation Description test");
  await page.locator("div.form-group>label.control-label").nth(13).click();
  await page.locator("//LABEL[contains(normalize-space(),\"Employer Presentation?\")]").hover();
  await page.getByPlaceholder("Special Request").fill("Special Request");
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(2).click();
  await page.locator("div.form-group>label.control-label").nth(15).click();
  await page.getByPlaceholder("Employer Presentation Details").fill("Employer Presentation Details");
  await page.locator("//LABEL[contains(normalize-space(),\"Office Hours?\")]").click();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(3).click();
  await page.locator("div.form-group>label.control-label").nth(17).click();
  await page.getByPlaceholder("Office Hour Details").fill("Office Hour Details");
  await page.getByRole('heading', { name: "Interview Contact" }).click();
  await page.getByRole('button', { name: "Use My Information" }).click();
  await page.getByPlaceholder("OCI Contact Phone").fill("9766336543");
  await page.getByPlaceholder("OCI Contact Title").fill("Accountant");
  await page.locator("//LABEL[normalize-space() = \"OCI Contact Address*\"]").click();
  await page.getByPlaceholder("OCI Contact Address").fill("Hyderabad 123");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Is Alumni\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(4).click();
  await page.locator("div.form-group>label.control-label").nth(24).hover();
  await page.locator("SELECT[id='ContactAlumniGraduationYear'][name='ContactAlumniGraduationYear']").selectOption("number:2021");
  await page.locator("div.form-group>label.control-label").nth(25).hover();
  await page.locator("SELECT[id='ContactAlumniGraduationProgramId'][name='ContactAlumniGraduationProgramId']").selectOption("number:14999901011484");
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save Draft" }).hover();
  await page.getByRole('button', { name: "Next" }).click();
  await page.getByRole('heading', { name: "On-Campus Interviews" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Ok" }).click();
  await page.waitForLoadState('load');
  await page.locator("div.sub-header.badges>span.badge").hover();
  await page.locator("div.sub-header.badges>span.badge").nth(1).hover();
  await page.locator("//SPAN[normalize-space() = \"Schedule Not Released\"]").hover();
  await page.locator("div.sub-header.badges>span.badge.badge-false.ng-scope").hover();
  await page.locator("div.sub-header.badges>span.badge.pending-approval.ng-binding.ng-scope").hover();
  await page.getByRole('link', { name: "Duolingo" }).hover();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.locator("ul.dropdown-menu.dropdown-menu-right>li.dropdown-header.ng-scope").hover();
  await page.getByRole('link', { name: "Link to Another OCI" }).hover();
  await page.getByRole('link', { name: "Delete" }).hover();
  await page.getByRole('link', { name: "Copy Student URL" }).hover();
  await page.getByRole('link', { name: "Copy Employer URL" }).hover();
  await page.getByRole('link', { name: "View Audit Log" }).hover();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Delete Job Posting" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
});
