// TC: TC65165
// 12TE Interviews - Create a meeting, post a job, add a schedule and add a interviewer - Employer

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("12TE Interviews - Create a meeting, post a job, add a schedule and add a interviewer - Employer", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;
  const text = msg.text();
  const timestamp = new Date().toLocaleString();

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(employerQA, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Email Address").fill("e2e.employeruser.subscription.admin@walmart.com");
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.waitForTimeout(2000);
  await page.locator("button.btn.btn-school.submit-login-form>span").click();
  await page.locator("div.nav-user-account-name-and-company>span.nav-user-account-name").hover();
  await page.getByRole('link', { name: "Interviews" }).click();
  await page.getByRole('heading', { name: "Interviews" }).hover();
  await page.locator("tr>th").hover();
  await page.getByRole('link', { name: "Interview Schedule" }).click();
  await page.getByRole('heading', { name: "General" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Interview Name*\"]").hover();
  await page.getByRole('heading', { name: "Interview Details" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Interview Format*\"]").hover();
  await page.locator("//DIV[normalize-space() = \"You will be able to add a virtual meeting URL when creating schedules\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Interview Plan*\"]").click();
  await page.locator("SELECT[name='CoreInterviewPlanTemplateId']").selectOption("number:31");
  await page.getByRole('heading', { name: "Interview Dates" }).hover();
  await page.locator("div.form-section-inputs>div.alert.alert-info").hover();
  await page.locator("//LABEL[normalize-space() = \"Interview Date Selection*\"]").hover();
  await page.getByPlaceholder("Interview Name").fill("Muuktest Automated Test");
  await page.locator("//LABEL[normalize-space() = \"Employer Selected\"]").click();
  await page.locator('input[type="radio"]').check();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Next" }).click();
  await page.getByRole('heading', { name: "Muuktest Automated Test" }).hover();
  await page.locator("div.header-main>div.sub-header.ng-binding").hover();
  await page.locator("//SPAN[normalize-space() = \"Date TBD\"]").hover();
  await page.locator("div.sub-header.badges>span.badge").hover();
  await page.locator("span.actionable-alert-message>span.ng-scope").hover();
  await page.getByRole('link', { name: "New Job" }).click();
  await page.getByRole('heading', { name: "Please select one or more program types..." }).hover();
  await page.getByRole('heading', { name: "Business" }).click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: "Continue" }).click();
  await page.locator("div.school-info>div.school-name.ng-binding").nth(5).click();
  await page.locator("span>policy.ng-scope").click();
  await page.getByRole('button', { name: "Continue" }).click();
  await page.locator("//LABEL[normalize-space() = \"Job Title *\"]").hover();
  await page.getByRole('heading', { name: "Details" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Type of Job *\"]").hover();
  await page.getByPlaceholder("Job Title").fill("Business job posting (Muuktest)");
  await page.locator("SELECT[name='CoreJobTypeId']").selectOption("number:1");
  await page.locator("//LABEL[normalize-space() = \"Industries *\"]").click();
  await page.getByRole('button', { name: "-- Please Select Industries --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Functions *\"]").click();
  await page.getByRole('button', { name: "-- Please Select Functions --" }).click();
  await page.getByPlaceholder("Search").fill("Information");
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Location Type *\"]").click();
  await page.locator("SELECT[name='LocationTypeId']").selectOption("number:3");
  await page.locator("div.form-group>label").nth(7).click();
  await page.getByRole('heading', { name: "Application Document Requirements Applicants will always be required to submit a resume." }).click();
  await page.locator("div>label").nth(47).click();
  await page.getByPlaceholder("Email Address").fill("test@gmail.com");
  await page.getByRole('heading', { name: "Job Dates" }).click();
  await page.locator("//LABEL[normalize-space() = \"I will review applicants as they come in, and may close the job posting early\"]").click();
  await page.getByRole('heading', { name: "Target Candidate Profile" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Candidate Population*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Students & Alumni\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Students only\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Alumni only\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Students & Alumni\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Work Authorization\"]").click();
  await page.getByRole('button', { name: "-- Please Select a Work Authorization --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Select all\"]").nth(2).click();
  await page.locator("div.form-group.ng-scope>label.control-label").nth(4).click();
  await page.getByPlaceholder("Work Auth Details").fill("Test");
  await page.getByRole('link', { name: "Back" }).hover();
  await page.getByRole('link', { name: "Continue" }).click();
  await page.waitForTimeout(2000);
  await page.getByRole('link', { name: "Continue" }).click();
  await page.locator("td.item-title>span.ng-binding").hover();
  await page.getByRole('link', { name: "Business job posting (Muuktest) | Remote/Telecommute" }).hover();
  await page.locator("tr.order-sub-item.ng-scope>td.sub-item-description.ng-binding").hover();
  await page.locator("tr.order-sub-item.ng-scope>td.sub-item-description.ng-binding").nth(1).hover();
  await page.getByRole('button', { name: "Submit Free Order" }).click();
  await page.getByRole('heading', { name: "Business job posting (Muuktest)" }).hover();
  await page.locator("//DIV[normalize-space() = \"Remote/Telecommute\"]").hover();
  await page.locator("div.badges>span.badge").nth(1).hover();
  await page.getByRole('link', { name: "Schedules" }).click();
  await page.locator("span.actionable-alert-message>span").nth(1).hover();
  await page.getByRole('link', { name: "Job Postings (1)" }).click();
  await page.getByRole('link', { name: "Schedules" }).click();
  await page.getByRole('link', { name: "Add Schedule" }).click();
  await page.getByRole('heading', { name: "Schedule" }).hover();
  await page.locator("//LABEL[normalize-space() = \"School\"]").hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Time Zone*\"]").click();
  await page.getByRole('button', { name: "-- Time Zone --" }).click();
  await page.locator("//LABEL[normalize-space() = \"Eastern Time (US & Canada) (UTC-05:00)\"]").click();
  await page.locator('input[type="radio"]').check();
  await page.locator("div.form-group>label.control-label").nth(2).hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(32).click();
  await page.locator("//LABEL[normalize-space() = \"Room Note\"]").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByPlaceholder("Room Note").fill("Automated test case by muuktest");
  await page.getByRole('button', { name: "Save" }).click();
  await page.locator("div.text-left.ng-scope>span.meeting-status-text.ng-binding").hover();
  await page.locator("div.text-right>span.meeting-status-text.ng-binding.ng-scope").hover();
  await page.locator("div.card-info>div.card-info-primary").nth(1).hover();
  await page.getByRole('button', { name: "Assign Interviewer" }).click();
  await page.getByRole('heading', { name: "Assign Interviewers" }).hover();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("div>label.checkbox").nth(1).click();
  await page.locator("//LABEL[normalize-space() = \"Interviewers*\"]").click();
  await page.getByRole('link', { name: "Select" }).click();
  await page.waitForTimeout(2000);
  await page.locator("BUTTON[type='button']").nth(8).click();
  await page.getByRole('link', { name: "12twenty" }).click();
  await page.locator("div.text-left.ng-scope>span.meeting-status-text.ng-binding").hover();
  await page.locator("a.meeting-join-link.ng-scope>span.meeting-join-link-text.ng-binding").hover();
  await page.getByRole('button', { name: "Action" }).click();
  await page.getByRole('link', { name: "Cancel Interview" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.locator("div.sub-header.badges>span.badge").hover();
});
