// TC: TC66686
// 12TE Job Postings - Employer user creates job posting for multiple schools and pays

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("12TE Job Postings - Employer user creates job posting for multiple schools and pays", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;
  const text = msg.text();
  const timestamp = new Date().toLocaleString();

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(employerQA, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Email Address").fill("e2e.employeruser.nosubscription@flemco.com");
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.waitForTimeout(2000);
  await page.locator("button.btn.btn-school.submit-login-form>span").click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Jobs" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Job Postings" }).hover();
  await page.getByRole('link', { name: "Post a Job" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Please select one or more program types..." }).hover();
  await page.getByRole('heading', { name: "Business" }).click();
  await page.locator("//P[normalize-space() = \"MBA, EMBA & PTMBA\"]").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Continue" }).click();
  await page.waitForLoadState('load');
  await page.locator("//SPAN[normalize-space() = \"School\"]").click();
  await page.getByPlaceholder("School").fill("e2e");
  await page.locator("//SPAN[normalize-space() = \"School\"]").click();
  await page.locator("div.school-info>div.school-name.ng-binding").nth(1).click();
  await page.locator("//DIV[normalize-space() = \"Students & Alumni from non-12twenty schools\"]").click();
  await page.getByRole('heading', { name: "Selected Schools" }).hover();
  await page.locator("//DIV[normalize-space() = \"Items: 2\"]").hover();
  await page.locator("//DIV[normalize-space() = \"Students & Alumni from non-12twenty schools\"]").nth(1).hover();
  await page.locator("li.order-item.ng-scope>div.order-name.ng-binding").nth(1).hover();
  await page.getByRole('button', { name: "Continue" }).click();
  await page.waitForLoadState('load');
  await page.locator("//LABEL[normalize-space() = \"Job Title *\"]").hover();
  await page.getByPlaceholder("Job Title").fill("Muuk Multiple Schools");
  await page.locator("//LABEL[normalize-space() = \"Employer *\"]").click();
  await page.getByPlaceholder("Employer").hover();
  await page.locator("//LABEL[normalize-space() = \"Type of Job *\"]").hover();
  await page.locator("SELECT[name='CoreJobTypeId']").selectOption("number:1");
  await page.locator("//LABEL[normalize-space() = \"Industries *\"]").hover();
  await page.getByRole('button', { name: "-- Please Select Industries --" }).click();
  await page.getByPlaceholder("Search").fill("Technology");
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Functions *\"]").click();
  await page.getByRole('button', { name: "-- Please Select Functions --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Location Type *\"]").click();
  await page.locator("SELECT[name='LocationTypeId']").selectOption("number:3");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Salary Range\"]").click();
  await page.getByPlaceholder("Min").fill("2000");
  await page.getByPlaceholder("Max").fill("40000");
  await page.locator("SELECT[name='CurrencyId']").selectOption("number:1");
  await page.locator("SELECT[name='PayFormatId']").selectOption("number:3");
  await page.locator("div.form-group>label").nth(8).click();
  await page.getByRole('heading', { name: "Attachments You will need to re-upload your attachments." }).click();
  await page.locator("//DIV[normalize-space() = \"Drop files to attach, or browse\"]").nth(7).hover();
  await page.getByRole('heading', { name: "Application Document Requirements Applicants will always be required to submit a resume." }).hover();
  await page.waitForLoadState('load');
  await page.locator("div.form-group>label.control-label").nth(9).click();
  await page.getByPlaceholder("Email Address").fill("test@gmail.com");
  await page.getByRole('heading', { name: "Job Dates" }).click();
  await page.locator("//LABEL[normalize-space() = \"How do you plan on reviewing your applicants?*\"]").click();
  await page.locator("//LABEL[normalize-space() = \"I will review applicants as they come in, and may close the job posting early\"]").click();
  await page.locator("div.form-group>label.control-label").nth(12).hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(32).click();
  await page.getByRole('heading', { name: "Target Candidate Profile" }).hover();
  await page.locator("//label[normalize-space()=\"Additional Candidate Requirements\"]").hover();
  await page.getByPlaceholder("Additional Candidate Requirements").fill("1st year MBA");
  await page.locator("//LABEL[normalize-space() = \"Years of Experience\"]").click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('button', { name: "-- Please Select a Work Authorization --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Candidate Population*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Students & Alumni\"]").click();
  await page.getByRole('heading', { name: "Primary Contact" }).click();
  await page.waitForLoadState('load');
  await page.locator("div.form-group>label.control-label").nth(19).hover();
  await page.locator("//LABEL[normalize-space() = \"Email Address *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Phone Number *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Address *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Country *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"City *\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Zip Code *\"]").hover();
  await page.getByRole('link', { name: "Back" }).hover();
  await page.getByRole('link', { name: "Continue" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('button', { name: "Add to Cart" }).click();
  await page.getByRole('link', { name: "Continue" }).click();
  await page.waitForLoadState('load');
  await page.waitForLoadState('load');
  await page.locator("td.item-title>span.ng-binding").hover();
  await page.getByRole('link', { name: "Muuk Multiple Schools | Remote/Telecommute" }).hover();
  await page.locator("tr.order-sub-item.ng-scope>td.sub-item-description.ng-binding").hover();
  await page.locator("tr.order-sub-item.ng-scope>td.sub-item-description.ng-binding").nth(1).hover();
  await page.locator("tr.order-sub-item.ng-scope>td.sub-item-description.ng-binding").nth(2).hover();
  await page.locator("tr.order-sub-item.ng-scope>td.sub-item-description.ng-binding").nth(3).hover();
  await page.locator("tr.order-item-option.ng-scope>td.order-item-option-description.ng-binding").hover();
  await page.getByRole('heading', { name: "Promo Code" }).hover();
  await page.getByRole('heading', { name: "Payment" }).hover();
  await page.getByRole('button', { name: "PAY NOW" }).click();
  await page.keyboard.press("Tab");
  await page.keyboard.press("Tab");
  await page.keyboard.press("Tab");
  await page.keyboard.press("Tab");
  await page.getByPlaceholder("1234 1234 1234 1234").fill("60000");
  await page.getByPlaceholder("MM / YY").fill("60000");
  await page.getByPlaceholder("CVC").fill("60000");
  await page.getByPlaceholder("Full name on card").fill("Xhang San");
  await page.locator("SELECT[name='billingCountry']").fill("60000");
  await page.getByPlaceholder("ZIP").fill("60000");
  await page.keyboard.press("Tab");
  await page.keyboard.press("Tab");
  await page.waitForTimeout(1000);
  await page.waitForTimeout(3000);
  const stripePass = page.locator('//input[@id="enableStripePass"]');
  if (await stripePass.isChecked()) {
  snippetLog("Checkbox is checked, clicking to uncheck...");
  await stripePass.click();
  } else {
  snippetLog("Checkbox is not checked, no action taken.");
  }
  await page.waitForTimeout(2000);
  await page.locator("button.SubmitButton>div.SubmitButton-IconContainer").click();
  await page.waitForLoadState('load');
  await page.waitForTimeout(4000);
  await page.getByRole('link', { name: "Orders" }).click();
  await page.getByRole('link', { name: "Paid" }).click();
  await page.getByRole('link', { name: "Jobs" }).click();
  await page.getByRole('link', { name: "Muuk Multiple Schools" }).click();
  await page.waitForTimeout(1000);
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Muuk Multiple Schools" }).hover();
  await page.locator("//dd[normalize-space()=\"Flemco\"]").hover();
  await page.locator("div.sub-header.badges>span.badge").hover();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Deactivate" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.waitForTimeout(2000);
  await page.getByRole('link', { name: "Jobs" }).click();
  await page.waitForTimeout(20000);
  selector = MK.onSetGV(`//A[normalize-space() = "Muuk Multiple Schools"]//ancestor::tr//span[contains(text(),"Application Open")]`, null);
  var isElementPresent = await page.locator(selector).count() > 0;
  if (!isElementPresent) {
  snippetLog('Element is not present.');
  } else {
  throw new Error('Element is present');
  }
  await page.getByPlaceholder("Job Title").fill("Muuk Multiple Schools");
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.active.day").click();
  await page.getByRole('button', { name: "Get Results" }).click();
  await page.waitForLoadState('load');
  await expect(page.getByRole('link', { name: "Muuk Multiple Schools" })).toHaveText("Muuk Multiple Schools");
  await expect(page.locator("//A[normalize-space() = \"Muuk Multiple Schools\"]//ancestor::tr//span[contains(text(),\"Inactive\")]")).toHaveText("Inactive");
});
