// TC: TC67381
// Events - Admin creates and edits an event, launches kiosk and checks a student in, deletes event

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Events - Admin creates and edits an event, launches kiosk and checks a student in, deletes event", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;
  const text = msg.text();
  const timestamp = new Date().toLocaleString();

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Events" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Events" }).hover();
  await page.getByRole('link', { name: "Host an Event" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Host an Event" }).hover();
  await page.getByRole('heading', { name: "General Info" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Event Name*\"]").click();
  await page.getByPlaceholder("Event Name").fill("Kiosk Check in Event - Muuktest");
  await page.locator("//LABEL[normalize-space() = \"Event Type*\"]").click();
  await page.locator("SELECT[id='EventTypeId'][name='EventTypeId']").selectOption("number:1499993124744");
  await page.locator("//LABEL[normalize-space() = \"Event Format\"]").click();
  await page.locator("SELECT[id='EventFormatId'][name='EventFormatId']").selectOption("number:1");
  await page.locator("//LABEL[normalize-space() = \"Location*\"]").click();
  await page.getByPlaceholder("Event Location").fill("Mexico");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Is Student Registration Required*\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").click();
  await page.locator("//LABEL[normalize-space() = \"# of Attendees Permitted*\"]").click();
  await page.getByPlaceholder("# of Attendees Permitted").fill("65");
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Enable Waitlist*\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(1).click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Auto-Promote Waitlisted Students*\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(2).click();
  await page.locator("//LABEL[normalize-space() = \"Target Audience\"]").click();
  await page.getByPlaceholder("Briefly describe who this event is meant for").fill("Audience");
  await page.locator("//LABEL[normalize-space() = \"Dress Attire*\"]").click();
  await page.locator("SELECT[id='DressAttireId'][name='DressAttireId']").selectOption("number:1");
  await page.locator("div.form-group>label.control-label").nth(10).click();
  await page.getByPlaceholder("Employer Name").fill("Walmart");
  await page.locator("//DIV[normalize-space() = \"Walmart\"]").nth(2).click();
  await page.locator("//LABEL[normalize-space() = \"Work Authorization Requirement*\"]").click();
  await page.getByRole('button', { name: "-- Work Authorization Requirement --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('heading', { name: "Event Dates" }).click();
  await page.locator("div.form-group.ng-isolate-scope>label.control-label").click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td").nth(4).click();
  await page.waitForTimeout(2000);
  await page.getByPlaceholder("H:MMpm").fill("2:05pm");
  await page.waitForTimeout(1000);
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td").nth(78).click();
  await page.waitForTimeout(1000);
  await page.getByPlaceholder("H:MMpm").fill("3:45pm");
  var today = new Date();
  var formattedDate = ("0" + (today.getMonth() + 1)).slice(-2) + '/' +
  ("0" + today.getDate()).slice(-2) + '/' +
  today.getFullYear();
  date = formattedDate;
  await page.locator("div.form-group>label.control-label").nth(9).click();
  await page.getByPlaceholder("MM/DD/YYYY").fill("` + date + `");
  await page.waitForTimeout(1000);
  await page.getByPlaceholder("H:MMpm").fill("12:00am");
  await page.waitForTimeout(1000);
  await page.getByPlaceholder("MM/DD/YYYY").fill("` + date + `");
  await page.waitForTimeout(1000);
  await page.locator("INPUT[id='searchInput'][name='search'][type='search']").fill("10:00pm");
  await page.locator("//LABEL[normalize-space() = \"Student Publish Date *\"]").click();
  await page.locator("INPUT[type='TEXT'][name='login']").fill("` + date + `");
  await page.locator("INPUT[type='text'][name='txt_Key_Captcha'][id='txt_Key_Captcha']").fill("12:00am");
  await page.getByRole('heading', { name: "Additional Registration Method" }).click();
  await page.locator("//LABEL[contains(text(),\"Register via Ot\")]//following::LABEL[normalize-space() = \"Yes\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Additional Registration Instructions\"]").click();
  await page.getByPlaceholder("Additional Registration Instructions").fill("Additional Registration Instructions");
  await page.getByRole('heading', { name: "Event Description" }).click();
  await page.locator("html").click();
  await page.locator("div.form-group>label.control-label").nth(24).click();
  await page.getByPlaceholder("Other Information").fill("Other Information");
  await page.getByRole('heading', { name: "Attachments" }).click();
  await page.getByRole('link', { name: "browse" }).click();
  fileName = MK.onSetGV(`Test_Resume_01.pdf`, null);
  var fileInput = await page.$("INPUT[type='file']");
  var filePath ="./test/"+fileName;
  if(fileInput){
  await fileInput.setInputFiles(filePath);
  }
  else{
  throw new Error('Element to upload file is not present.');
  }
  await page.getByRole('heading', { name: "Registration Document(s)" }).click();
  await page.waitForLoadState('load');
  await page.locator("div.form-section-header>span.form-section-header-help-text").nth(1).hover();
  await page.getByRole('link', { name: "Add Document Type" }).click();
  await page.locator("SELECT[name='CoreApplicationDocumentTypeId']").selectOption("number:1");
  await page.getByRole('heading', { name: "Eligibility" }).hover();
  await page.locator("div.form-section-header>div.form-section-header-help-text").hover();
  await page.locator("//LABEL[normalize-space() = \"Student Group*\"]").hover();
  await page.locator("INPUT[type='text'][name='DocumentTypeName']").fill("ResumeTest");
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.ng-scope>label.control-label.ng-binding").nth(1).click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.ng-scope>label.control-label.ng-binding").nth(2).click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.ng-scope>label.control-label.ng-binding").nth(3).click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator("//DIV[normalize-space() = \"Major 5\"]").click();
  await page.getByRole('heading', { name: "Primary Event Contact" }).click();
  await page.getByRole('button', { name: "Use My Information" }).click();
  await page.getByPlaceholder("Contact Phone").fill("9153455681");
  await page.getByRole('heading', { name: "Employers In Attendance" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Contact\"]").hover();
  await page.getByPlaceholder("Select a contact").fill("Adam ");
  await page.locator("SELECT[name='DressAttireId']").selectOption("number:2");
  await page.locator("//DIV[normalize-space() = \"Adam Elliott - McKesson - Recruiter\"]").click();
  await page.getByRole('heading', { name: "Admin" }).click();
  await page.getByRole('button', { name: "Save" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Kiosk Check in Event - Muuktest" }).hover();
  await page.getByRole('link', { name: "Walmart" }).hover();
  await page.locator("//DIV[normalize-space() = \"Career Center Workshop\"]").hover();
  await page.locator("div.sub-header>em.ng-binding").hover();
  await page.locator("div.actionable-alert-message>span.ng-scope").hover();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Edit Event" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('button', { name: "Save" }).click();
  await page.waitForLoadState('load');
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Launch Check-In Kiosk" }).click();
  await page.getByRole('heading', { name: "Please Select a Check-In Type" }).hover();
  await page.locator("label.radio-inline>b").click();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Ok" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Kiosk Check in Event - Muuktest" }).hover();
  await page.locator("div>p.ng-scope").hover();
  await page.locator("INPUT[type='text']").fill("e2e.student.fullacces@campuswide.com");
  await page.getByRole('button', { name: "Check-in" }).click();
  await page.getByRole('heading', { name: "Oops!" }).hover();
  await page.locator("//DIV[normalize-space() = \"User not found. Please ensure you are entering the correct student ID and/or email address.\"]").nth(1).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.waitForTimeout(3000);
  await page.waitForLoadState('load');
  await page.locator("INPUT[type='text']").fill("e2e.student.fullaccess@campuswide.com");
  await page.waitForTimeout(4000);
  await page.getByRole('button', { name: "Check-in" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Success!" }).hover();
  await page.locator("//DIV[contains(normalize-space(),\"you have successfully checked in!\")]").nth(1).hover();
  await page.locator("//DIV[normalize-space() = \"Kiosk Check in Event - Muuktest Please swipe your student ID to check in, or enter your details below Check-in\"]").nth(7).click();
  await page.locator("INPUT[id='emailOrStudentId'][type='text'][name='emailOrStudentId']").fill("%600957Emily.Smith1@campuswide.com31-4912120000000000000? ");
  await page.getByRole('button', { name: "Check-in" }).click();
  await page.getByRole('heading', { name: "Oops!" }).hover();
  await page.locator("//DIV[normalize-space() = \"User not found. Please ensure you are entering the correct student ID and/or email address.\"]").nth(1).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.locator("INPUT[id='emailOrStudentId'][type='text'][name='emailOrStudentId']").fill("%600957Emily.Smith@campuswide.com31-4912120000000000000?");
  await page.getByRole('button', { name: "Check-in" }).click();
  await page.getByRole('heading', { name: "Success!" }).hover();
  await page.locator("//DIV[normalize-space() = \"Thanks Emily, you have successfully checked in!\"]").nth(1).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.goto('https://e2e-tests-campuswide.admin.qa-12twenty.com/', { timeout: 90000 });
  await page.waitForLoadState('load');
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Events" }).click();
  await page.locator("a.event-name.primary-item.primary-item-with-icons>span.primary-item-text.ng-binding").click();
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Registered Students (1)" }).click();
  await page.getByRole('link', { name: "e2e Test Student" }).hover();
  await page.locator("tr.ng-scope>td.ng-binding.ng-scope").hover();
  await page.locator("I[title='Click to toggle']").hover();
  await page.locator("BUTTON[type='button']").nth(9).click();
  await page.getByRole('link', { name: "Cancel Registration" }).click();
  await page.waitForLoadState('load');
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  selector = MK.onSetGV(`//SPAN[contains(text(),"Muuktest Event")]`, null);
  var isElementPresent = await page.locator(selector).count() > 0;
  if (!isElementPresent) {
  snippetLog('Element is not present.');
  } else {
  throw new Error('Element is present');
  }
  await page.getByRole('link', { name: "Emily Smith" }).hover();
  await page.locator("small>em.clearfix.normal.ng-binding").hover();
  await page.locator("//span[normalize-space()=\"Emily.Smith@campuswide.com\"]").hover();
  await page.locator("//A[normalize-space() = \"Emily Smith\"]/ancestor::tr//button[@aria-label=\"Options\"]").click();
  await page.getByRole('link', { name: "Cancel Registration" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Edit Event" }).hover();
  await page.getByRole('link', { name: "Delete" }).hover();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete Event" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Event" }).click();
  await page.waitForLoadState('load');
  selector = MK.onSetGV(`//SPAN[contains(text(),"Muuktest Event")]`, null);
  var isElementPresent = await page.locator(selector).count() > 0;
  if (!isElementPresent) {
  snippetLog('Element is not present.');
  } else {
  throw new Error('Element is present');
  }
});
