// TC: TC75003
// Outcomes - Student creates Post Graduation Received Job

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Outcomes - Student creates Post Graduation Received Job", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideStudentURL, { timeout: 90000 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.student.fullaccess@campuswide.com");
  await page.getByPlaceholder("Password").fill("BoH5dORH7xg%");
  await page.getByRole('button', { name: "Student/Alumni Log In" }).click();
  await page.waitForTimeout(1000);
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Profile" }).click();
  await page.getByRole('link', { name: "Home" }).click();
  await page.getByRole('link', { name: "Add Experience or Status" }).click();
  await page.getByRole('heading', { name: "Add Experience or Status..." }).hover();
  await page.getByRole('button', { name: "Post Graduation" }).click();
  await page.getByRole('button', { name: "Received Job" }).click();
  await page.getByRole('heading', { name: "Job - Offer Received" }).hover();
  await page.getByPlaceholder("Employer").fill("Duolingo");
  await page.locator("DIV[id='ui-id-7']").click();
  await page.locator("div.inputRow>label.control-label").nth(2).hover();
  await page.locator("SELECT[name='Job.JobIndustryId'][id='Job.JobIndustryId']").selectOption("149999414151544");
  await page.locator("//LABEL[contains(normalize-space(),\"Job Title\")]").hover();
  await page.getByPlaceholder("Job Title").fill("Muuk Consultant");
  await page.locator("//LABEL[contains(normalize-space(),\"Detailed Function\")]").hover();
  await page.locator("SELECT[name='Job.JobFunctionId'][id='Job.JobFunctionId']").selectOption("100001010430351");
  await page.locator("div.inputRow>label.control-label").nth(4).hover();
  await page.locator("SELECT[id='Job_NumberOfEmployeesId'][name='Job.NumberOfEmployeesId']").selectOption("9");
  await page.locator("//LABEL[contains(normalize-space(),\"Location Type\")]").hover();
  await page.locator("SELECT[name='Job.LocationTypeId'][id='Job.LocationTypeId']").selectOption("2");
  await page.locator('input[type="checkbox"]').click();
  await page.getByPlaceholder("Country").hover();
  await page.locator("INPUT[id='Job_Address1'][name='Job.Address1'][type='text']").hover();
  await page.locator("INPUT[id='Job_Address2'][name='Job.Address2'][type='text']").hover();
  await page.locator("INPUT[id='Job_PostalCode'][name='Job.PostalCode'][type='text']").hover();
  await page.getByPlaceholder("City").hover();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.day").nth(1).click();
  await page.locator("//LABEL[contains(normalize-space(),\"Expected Commission\")]").hover();
  await page.locator("INPUT[type='text'][id='Job.Salary.BaseSalary'][name='Job.Salary.BaseSalary']").fill("90000");
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[contains(normalize-space(),\"Expected Bonus\")]").hover();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[contains(normalize-space(),\"Guaranteed Bonus\")]").hover();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[contains(normalize-space(),\"Other Guaranteed Compensation\")]").hover();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[contains(normalize-space(),\"Carried Interest\")]").hover();
  await page.locator('input[type="checkbox"]').click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[contains(normalize-space(),\"Relocation Reimbursement\")]").hover();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[contains(normalize-space(),\"Tuition Reimbursement\")]").hover();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[contains(normalize-space(),\"Stock or Equity Value\")]").hover();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[contains(normalize-space(),\"Does your compensation include health insurance?\")]").hover();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[contains(normalize-space(),\"Does your compensation include tuition reimbursement\")]").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(1).click();
  await page.locator('input[type="radio"]').check();
  await page.locator("SELECT[name='Job.CustomJobSourceId'][id='Job.CustomJobSourceId']").selectOption("100011010338750");
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a full-time position?\")]").hover();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(2).click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[contains(normalize-space(),\"Did this job come as a result of an internship you had with this employer?\")]").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(3).click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a freelance position?\")]").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(4).click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a faculty position?\")]").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(5).click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a temporary/contract job?\")]").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(7).click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[contains(normalize-space(),\"Is this a post-graduation internship?\")]").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(8).click();
  await page.locator('input[type="radio"]').check();
  await page.locator("//LABEL[contains(normalize-space(),\"Is the employer a startup?\")]").hover();
  await page.locator("//LABEL[normalize-space() = \"No\"]").nth(9).click();
  await page.locator('input[type="radio"]').check();
  await page.locator("div>label.control-label").nth(35).hover();
  await page.locator("TEXTAREA[id='Job_OptionalPertinentInformation'][name='Job.OptionalPertinentInformation']").fill("I received this offer.");
  await page.locator("//label[normalize-space() = \"Satisfaction\"]").hover();
  await page.locator("//label[contains(normalize-space(),\"Star Rating Attribute - Required\")]").hover();
  await page.locator("td.ant-table-cell.drag-visible.column-center.ant-table-cell-row-hover>div.ant-row.css-eqeg24").click();
  await page.getByRole('button', { name: "Submit" }).click();
  await page.getByRole('heading', { name: "Success" }).hover();
  await page.getByRole('link', { name: "No thanks. That's all for now!" }).click();
  await page.getByRole('link', { name: "Muuk Consultant" }).hover();
  await page.locator("//DIV[normalize-space() = \"Duolingo\"]").hover();
  await page.locator("div.badges>span.badge.ng-binding.ng-scope.offer-received").hover();
  await page.locator("div.badges>span.badge.ng-binding.ng-scope.alert").hover();
  await page.getByRole('link', { name: "Accept" }).hover();
  await page.getByRole('link', { name: "Reject" }).hover();
  await page.locator("BUTTON[type='button']").nth(3).click();
  await page.locator("//A[contains(text(),\"Muuk Consultant\")]//following::a[normalize-space()=\"Edit\"]").hover();
  await page.getByRole('link', { name: "Accept" }).hover();
  await page.getByRole('link', { name: "Reject" }).hover();
  await page.locator("//A[contains(text(),\"Muuk Consultant\")]//following::a[normalize-space()=\"Delete\"]").click();
  await page.getByRole('heading', { name: "Delete Entry" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Entry" }).click();
  await page.waitForTimeout(10000);
  await page.waitForLoadState('load');
});
