// TC: TC61664
// Job Postings - Admin posts and deletes a job

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Job Postings - Admin posts and deletes a job", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Job Listings & Interviews" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Job Listings & Interviews" }).hover();
  await page.getByRole('link', { name: "Post a Job" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Create Job Posting" }).hover();
  await page.getByPlaceholder("Employer").fill("State Farm Insurance");
  await page.getByPlaceholder("Job Title").fill("Manager");
  await page.getByRole('button', { name: "-- Type of Job --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Salary Range\"]").click();
  await page.getByPlaceholder("Min").fill("50000");
  await page.getByPlaceholder("Max").fill("70000");
  await page.locator("SELECT[name='CurrencyId']").selectOption("number:14");
  await page.locator("SELECT[name='PayFormatId']").selectOption("number:3");
  await page.locator("SELECT[id='LocationTypeId'][name='LocationTypeId']").selectOption("number:2");
  await page.getByRole('button', { name: "-- Industry --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Job Function*\"]").click();
  await page.getByRole('button', { name: "-- Job Function --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("//LABEL[normalize-space() = \"Preferred Years of Experience\"]").click();
  await page.getByPlaceholder("Preferred Years of Experience").fill("2");
  await page.locator("SELECT[id='InterviewFormatId'][name='InterviewFormatId']").selectOption("number:6");
  await page.getByRole('button', { name: "-- Work Authorization Requirement --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.getByRole('heading', { name: "Application Method(s)*" }).click();
  await page.locator("//LABEL[normalize-space(translate(., '\\u00A0', ' ')) = \"Apply via This Site*\"]").click();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").click();
  await page.locator('input[type="radio"]').check();
  await page.locator("div.form-group>label.control-label").nth(12).click();
  await page.locator("//LABEL[contains(text(),\"Apply via External Link\")]//following::label[normalize-space()=\"No\"]").click();
  await page.locator('input[type="radio"]').check();
  await page.locator("div.form-group>label.control-label").nth(13).click();
  await page.locator("//LABEL[contains(text(),\"Apply via Email\")]//following::LABEL[normalize-space() = \"Yes\"]").click();
  await page.locator('input[type="radio"]').check();
  await page.getByPlaceholder("e.g. sample@domain.com").fill("john123@12twenty.com");
  await page.getByRole('heading', { name: "Job Description" }).click();
  await page.locator("label.control-label>span").nth(15).click();
  textContent = MK.onSetGV(`Managing a portfolio of clients, developing strong relationships, and ensuring the successful delivery of our products and services.`, null);
  page.keyboard.type(textContent);
  await page.getByRole('heading', { name: "Attachments" }).click();
  fileName = MK.onSetGV(`Test_Resume_01.pdf`, null);
  var fileInput = await page.$("INPUT[type='file']");
  var filePath ="./test/"+fileName;
  if(fileInput){
  await fileInput.setInputFiles(filePath);
  }
  else{
  throw new Error('Element to upload file is not present.');
  }
  await page.locator("//LABEL[normalize-space() = \"Time Zone*\"]").click();
  await page.getByRole('button', { name: "Guadalajara, Mexico City, Monterrey (UTC-06:00)" }).click();
  await page.getByPlaceholder("Search").fill("Chennai");
  await page.locator("//LABEL[normalize-space() = \"Chennai, Kolkata, Mumbai, New Delhi (UTC+05:30)\"]").click();
  await page.locator('input[type="radio"]').check();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.today.active.day").click();
  await page.getByPlaceholder("MM/DD/YYYY").click();
  await page.locator("tr>td.active.day").click();
  await page.locator("//LABEL[normalize-space() = \"I will review applicants as they come in, and may close the job posting early\"]").click();
  await page.getByPlaceholder("MM/DD/YYYY").fill("03/01/2025");
  await page.locator("label.control-label>span.ng-binding").click();
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(3).click();
  await page.getByRole('button', { name: "Use My Information" }).click();
  await page.getByPlaceholder("Title").fill("Project Manager");
  await page.getByPlaceholder("Job Posting Contact Phone").fill("9766336543");
  await page.getByPlaceholder("Job Posting Contact Address").fill("Hyderabad 123");
  await page.locator("//LABEL[normalize-space() = \"Yes\"]").nth(4).click();
  await page.locator("SELECT[id='ContactAlumniGraduationYear'][name='ContactAlumniGraduationYear']").selectOption("number:2021");
  await page.locator("SELECT[id='ContactAlumniGraduationProgramId'][name='ContactAlumniGraduationProgramId']").selectOption("number:14999901011484");
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.ng-scope>label.control-label.ng-binding").nth(3).click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.ng-scope>label.control-label.ng-binding").nth(4).click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.ng-scope>label.control-label.ng-binding").nth(5).click();
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.locator('input[type="checkbox"]').click();
  await page.locator("div.ng-scope>label.control-label.ng-binding").nth(5).click();
  await page.locator("SELECT[id='JobPostingSourceId'][name='JobPostingSourceId']").selectOption("number:100063031018421");
  await page.locator("SELECT[id='custom_attribute_3'][name='custom_attribute_3']").click();
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Enter');
  await page.getByRole('button', { name: "Next" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Job Posting" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Ok" }).click();
  await page.getByRole('heading', { name: "Manager" }).hover();
  await page.getByRole('link', { name: "State Farm Insurance" }).hover();
  await page.locator("div.sub-header.ng-scope>text.ng-binding").hover();
  await page.locator("//SPAN[normalize-space() = \"Full-Time Job\"]").hover();
  await page.locator("//SPAN[normalize-space() = \"Apply Immediately\"]").nth(1).hover();
  await page.locator("div.sub-header.badges>span.badge").hover();
  await page.locator("//SPAN[normalize-space() = \"Job Posting Status: Application Open. Any edits will take effect immediately.\"]").hover();
  await page.locator("BUTTON[type='button']").nth(2).click();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete Job Posting" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Job Posting" }).click();
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Job Listings & Interviews" }).hover();
  await page.waitForLoadState('load');
  await page.waitForTimeout(2000);
  await page.reload();
  await page.waitForLoadState('load');
});
