// TC: TC60700
// Experiential Learning - Adding a new experience - Admin

import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test("Experiential Learning - Adding a new experience - Admin", async ({ page, context }) => {
  let e2eCampusWideAdminURL = `https://e2e-tests-campuswide.admin.qa-12twenty.com/Login`;
  let messageAnnouncement = `test`;
  let date = `8/24/2025`;
  let e2eCampusWideStudentURL = `https://e2e-tests-campuswide.qa-12twenty.com/Login`;
  let employerQA = `https://employer.qa-12twenty.com/`;
  let adminUserLoadTesting = `1`;
  let repeatEachParameter = `1`;
  let executionNum = `100`;
  let e2eLawQAStudentURL = `https://e2e-tests-law.qa-12twenty.com/`;

  // Handle new tabs
  context.on('page', async (newPage) => { page = newPage; });

  await page.goto(e2eCampusWideAdminURL, { timeout: 90000 });
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.admin.schooladministrator@campuswide.com");
  await page.getByPlaceholder("Password").fill("eQ%DEx%j6Cl9");
  await page.getByRole('button', { name: "Admin Log In" }).click();
  await page.getByRole('link', { name: "Home" }).hover();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: "Experiential Learning" }).click();
  await page.getByRole('heading', { name: "Experiential Learning" }).hover();
  await page.getByRole('link', { name: "New Experience" }).click();
  await page.waitForTimeout(1000);
  await page.waitForLoadState('load');
  await page.getByRole('heading', { name: "Create New Experience" }).hover();
  await page.getByRole('heading', { name: "Basics" }).hover();
  await page.getByPlaceholder("Student").fill("e2e Test Student");
  await page.locator("//div[normalize-space()=\"e2e Test Student (e2e.student.fullaccess@campuswide.com)\"]").click();
  await page.getByPlaceholder("Specify employer name").fill("Archer Daniels Midland");
  await page.locator("div.tt-suggestion.tt-selectable>strong.tt-highlight").nth(1).click();
  await page.locator("//LABEL[normalize-space() = \"Experiential Learning Type*\"]").hover();
  await page.locator("SELECT[name='TypeId']").selectOption("number:1001430512365");
  await page.locator("//LABEL[normalize-space() = \"Street Address*\"]").hover();
  await page.getByPlaceholder("Street Address").fill("Chiromo lane");
  await page.getByRole('button', { name: "-- Select a Value --" }).click();
  await page.getByPlaceholder("Search").fill("Kenya");
  await page.locator("//LABEL[normalize-space() = \"Kenya\"]").click();
  await page.getByPlaceholder("City").fill("Nairobi - Kenya");
  await page.locator("//DIV[normalize-space() = \"Nairobi - Kenya\"]").nth(2).click();
  await page.getByRole('heading', { name: "Supervisor" }).hover();
  await page.locator("//LABEL[normalize-space() = \"Contact*\"]").hover();
  await page.locator("//LABEL[normalize-space() = \"Contact*\"]/following-sibling::div//select").click();
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Enter');
  await page.locator("//LABEL[normalize-space() = \"Contact\"]").nth(2).hover();
  await page.getByPlaceholder("Employer Supervisor Phone").fill("6453643654");
  await page.getByPlaceholder("Select a contact").fill("Adam Elliott");
  await page.locator("//DIV[normalize-space() = \"Adam Elliott - McKesson - Recruiter\"]").click();
  await page.locator("ng-transclude>span.primary-item-text.ng-binding.ng-scope").nth(1).hover();
  await page.locator("div.entity-short-summary-primary>span.sub-info.ng-binding").nth(2).hover();
  await page.locator("div.entity-short-summary-primary>span.sub-info.ng-binding.ng-scope").nth(1).hover();
  await page.getByPlaceholder("MM/DD/YYYY").fill("10/07/2022");
  await page.locator("//LABEL[contains(normalize-space(), \"End Date\")]/following::input").fill("10/15/2024");
  await page.locator("//LABEL[normalize-space() = \"Academic Term*\"]").click();
  await page.locator("SELECT[name='AcademicTermId']").selectOption("number:190017010143207");
  await page.locator("//LABEL[normalize-space() = \"Class Year*\"]").hover();
  await page.locator("SELECT[name='SchoolYearId']").selectOption("number:21");
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Save" }).click();
  await page.getByRole('heading', { name: "Archer Daniels Midland" }).hover();
  await page.getByRole('link', { name: "e2e Test Student" }).hover();
  await page.locator("//DIV[normalize-space() = \"Summer 2022\"]").hover();
  await page.getByRole('link', { name: "Back to List" }).click();
  await page.locator("span.sub-info>tt-date-time-display.ng-binding").hover();
  await page.getByRole('link', { name: "e2e Test Student" }).hover();
  await page.locator("tr.ng-scope>td.ng-binding").hover();
  await page.locator("tr.ng-scope>td.ng-binding").nth(1).hover();
  await page.locator("td.status>span.badge").hover();
  await page.locator("tr.ng-scope>td.hours.ng-binding").hover();
  maxRetries = 0;
  while(!pageUpdated && maxRetries++ < 600){ await new Promise((resolve) => setTimeout(resolve, 100)); }
  await expect(await page.url()).toContain('e2e-tests-campuswide.qa-12twenty.com/');
  await page.waitForTimeout(4000);
  const authData = JSON.parse(fs.readFileSync('authCookie12Twenty.json', 'utf-8'));
  await context.addCookies(authData.cookies || []);
  await page.waitForTimeout(4000);
  await page.reload();
  await page.getByPlaceholder("Email Address").fill("e2e.student.fullaccess@campuswide.com");
  await page.getByPlaceholder("Password").fill("BoH5dORH7xg%");
  await page.getByRole('button', { name: "Student/Alumni Log In" }).click();
  await page.waitForTimeout(1000);
  await page.waitForLoadState('load');
  await page.getByRole('link', { name: "Home" }).hover();
  await page.getByRole('link', { name: "Experiential Learning" }).click();
  await page.getByRole('link', { name: "Archer Daniels Midland" }).click();
  await page.locator("div.sub-header.badges>span.badge.draft").hover();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.locator("BUTTON[type='button']").nth(8).click();
  await page.getByRole('link', { name: "Email Student" }).hover();
  await page.getByRole('link', { name: "Archer Daniels Midland" }).click();
  await page.getByRole('button', { name: "Submit" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.locator("div.sub-header.badges>span.badge").hover();
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForTimeout(1000);
  await page.reload();
  await page.locator("div.sub-header.badges>span.badge").hover();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.waitForTimeout(2000);
  await page.reload();
  await page.locator("div.sub-header.badges>span.badge.in-progress").hover();
  await page.getByRole('button', { name: "Submit" }).click();
  await page.getByRole('heading', { name: "Please Confirm" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "OK" }).click();
  await page.locator("div.sub-header.badges>span.badge").hover();
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.reload();
  await page.locator("div.sub-header.badges>span.badge.complete").hover();
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.locator("BUTTON[type='button']").nth(6).click();
  await page.getByRole('link', { name: "Back To In Progress" }).hover();
  await page.getByRole('link', { name: "Edit" }).hover();
  await page.getByRole('link', { name: "Delete" }).hover();
  await page.getByRole('link', { name: "View Audit Log" }).hover();
  await page.getByRole('link', { name: "Delete" }).click();
  await page.getByRole('heading', { name: "Delete Experience" }).hover();
  await page.locator("div.modal-body.ng-pristine.ng-valid.ng-scope>div.text-area-display.ng-binding.ng-scope").hover();
  await page.getByRole('button', { name: "Cancel" }).hover();
  await page.getByRole('button', { name: "Delete Experience" }).click();
  await page.waitForTimeout(2000);
  await page.getByRole('link', { name: "Experiential Learning" }).click();
  indexPages = MK.onSetGV(`1`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  await page.getByRole('link', { name: "Experiential Learning" }).click();
  selector = MK.onSetGV(`//A[contains(text(),"Archer Daniels Midland")]`, null);
  var isElementPresent = await page.locator(selector).count() > 0;
  if (!isElementPresent) {
  snippetLog('Element is not present.');
  } else {
  throw new Error('Element is present');
  }
  indexPages = MK.onSetGV(`0`, null);
  await page.waitForTimeout(2000);
  snippetLog('CHANGING TO PAGE #' + indexPages);
  newPages = context.pages();
  pagesAfterPopUp = await newPages[parseInt(indexPages)];
  selector = MK.onSetGV(`//H1[contains(text(),"Archer Daniels")]`, null);
  var isElementPresent = await page.locator(selector).count() > 0;
  if (!isElementPresent) {
  snippetLog('Element is not present.');
  } else {
  throw new Error('Element is present');
  }
});
